const D=[
['9','🌸','Lotofagii','The Lotus-Eaters','Lotusul îi face pe cercetași să uite de casă. Odiseu îi aduce înapoi la corăbii.','The lotus makes the scouts forget home. Odysseus brings them back to the ships.','Ce le răpește lotusul?','What does the lotus take away?',['Dorința de a reveni acasă','Corăbiile','Puterea de a vorbi'],['The wish to return home','Their ships','Their ability to speak']],
['9','👁','Ciclopul','The Cyclops','Odiseu se prezintă drept „Nimeni” și îl orbește pe Polifem. Dezvăluirea numelui său adevărat atrage blestemul.','Odysseus calls himself “Nobody” and blinds Polyphemus. Revealing his real name brings the curse.','Ce nume folosește în peșteră?','Which name does he use in the cave?',['Nimeni','Hermes','Zeus'],['Nobody','Hermes','Zeus']],
['10','🌬','Eol','Aeolus','Eol îi oferă un sac cu vânturi. Echipajul îl deschide când Itaca este deja aproape.','Aeolus gives him a bag of winds. The crew opens it when Ithaca is already close.','Ce deschide echipajul?','What does the crew open?',['Sacul cu vânturi','Porțile Itacăi','O carte'],['The bag of winds','The gates of Ithaca','A book']],
['10','🪨','Lestrigonii','The Laestrygonians','Uriașii distrug flota. Doar corabia lui Odiseu scapă.','The giants destroy the fleet. Only Odysseus’s ship escapes.','Câte corăbii scapă?','How many ships escape?',['Una','Șase','Douăsprezece'],['One','Six','Twelve']],
['10','🪄','Circe','Circe','Circe îi transformă pe oameni în porci. După salvarea lor, Odiseu rămâne un an pe insula Eea.','Circe turns the men into pigs. After rescuing them, Odysseus stays a year on Aeaea.','În ce sunt transformați oamenii?','What are the men turned into?',['Porci','Păsări','Pești'],['Pigs','Birds','Fish']],
['11','🕯','Lumea de dincolo','The Underworld','Odiseu întâlnește spiritul lui Tiresias, care îi prevestește drumul spre casă.','Odysseus meets the spirit of Tiresias, who foretells his way home.','Cine îi oferă profeția?','Who gives him the prophecy?',['Tiresias','Polifem','Nausicaa'],['Tiresias','Polyphemus','Nausicaa']],
['12','🎵','Sirenele','The Sirens','Echipajul își astupă urechile cu ceară. Odiseu ascultă cântecul legat de catarg.','The crew stops their ears with wax. Odysseus hears the song while tied to the mast.','Ce protejează echipajul?','What protects the crew?',['Ceara din urechi','Sacul cu vânturi','Un scut'],['Wax in their ears','The bag of winds','A shield']],
['12','🌊','Scila și Caribda','Scylla and Charybdis','Corabia trece între două primejdii. Scila smulge șase oameni de pe punte.','The ship passes between two dangers. Scylla snatches six men from the deck.','Câți oameni sunt luați de Scila?','How many men does Scylla take?',['Șase','Unul','Doisprezece'],['Six','One','Twelve']],
['12','☀','Trinacia','Thrinacia','Echipajul mănâncă vitele lui Helios. Zeus distruge corabia; numai Odiseu supraviețuiește.','The crew eats the cattle of Helios. Zeus wrecks the ship; only Odysseus survives.','Ale cui sunt vitele?','Whose cattle are they?',['Ale lui Helios','Ale lui Eol','Ale lui Tiresias'],['Helios’s','Aeolus’s','Tiresias’s']],
['5','🏝','Ogigia','Ogygia','Odiseu petrece șapte ani cu Calipso. Hermes îi transmite porunca de a-l elibera.','Odysseus spends seven years with Calypso. Hermes delivers the order to release him.','Cine aduce porunca?','Who delivers the order?',['Hermes','Circe','Nausicaa'],['Hermes','Circe','Nausicaa']],
['6–8','👑','Scheria','Scheria','Nausicaa îl găsește la țărm. La feaci, Odiseu își povestește aventurile.','Nausicaa finds him on the shore. Among the Phaeacians, Odysseus tells his adventures.','Cine îl găsește la țărm?','Who finds him on the shore?',['Nausicaa','Calipso','Scila'],['Nausicaa','Calypso','Scylla']],
['13–22','🏹','Itaca','Ithaca','Întors acasă și deghizat în cerșetor, Odiseu încordează arcul și îi învinge pe pețitori.','Home again and disguised as a beggar, Odysseus strings the bow and defeats the suitors.','Ce dovedește identitatea eroului în confruntare?','What reveals the hero’s skill in the confrontation?',['Încordarea arcului','Deschiderea sacului','Cântecul sirenelor'],['Stringing the bow','Opening the bag','The Sirens’ song']]
];
