/* Pure state and deterministic puzzle generation; also usable by Node tests. */
const Engine=(()=>{
const key='odyssey-quest-v2',modes=['story','explore','short','daily','challenge','tournament','zen','quiz','navigator','duo','workshop'];
const freshProfile=()=>({captain:'',ship:'',levels:Array(12).fill(0),wallet:0,earned:[],skins:['default'],skin:'default',daily:[],leaderboard:[],opinions:[],resources:{supplies:5,morale:3,hull:100}});
const fresh=()=>({app:'odyssey-quest',version:2,active:0,prefs:{lang:'ro',light:false,contrast:false,still:false,quiet:false,sound:false,haptic:false,scan:false,swipe:false,child:false,font:100,difficulty:'normal',edition:'faithful',timer:0,weather:'calm'},profiles:Array.from({length:3},freshProfile),workshop:[],route:Array.from({length:12},(_,i)=>i)});
function validate(s){if(!s||s.app!=='odyssey-quest'||s.version!==2||!Number.isInteger(s.active)||s.active<0||s.active>2||!Array.isArray(s.profiles)||s.profiles.length!==3)return false;
const p=s.prefs;if(!p||!['ro','en'].includes(p.lang)||![100,115,130].includes(p.font)||!['easy','normal','hard'].includes(p.difficulty)||!['faithful','whatif'].includes(p.edition)||![0,120,300,600].includes(p.timer)||!['calm','sunset','night','fog','storm'].includes(p.weather)||!['light','contrast','still','quiet','sound','haptic','scan','swipe','child'].every(k=>typeof p[k]==='boolean'))return false;
if(!validWorkshop(s.workshop)||!Array.isArray(s.route)||!s.route.length||s.route.length>24||!s.route.every(i=>Number.isInteger(i)&&i>=0&&i<12))return false;
return s.profiles.every(p=>p&&typeof p.captain==='string'&&p.captain.length<=32&&typeof p.ship==='string'&&p.ship.length<=32&&Array.isArray(p.levels)&&p.levels.length===12&&p.levels.every(n=>Number.isInteger(n)&&n>=0&&n<=10)&&p.levels.every((n,i)=>!n||!i||p.levels[i-1]===10)&&Number.isInteger(p.wallet)&&p.wallet>=0&&p.wallet<=100000&&Array.isArray(p.earned)&&p.earned.length<=2000&&new Set(p.earned).size===p.earned.length&&p.earned.every(x=>typeof x==='string'&&x.length<=100)&&Array.isArray(p.daily)&&p.daily.length<=400&&p.daily.every(x=>typeof x==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(x))&&Array.isArray(p.skins)&&p.skins.includes('default')&&p.skins.every(x=>['default','night','gold'].includes(x))&&p.skins.includes(p.skin)&&Array.isArray(p.opinions)&&p.opinions.length<=50&&p.opinions.every(x=>x&&typeof x.text==='string'&&x.text.length<=2000&&typeof x.date==='string'&&x.date.length<=40)&&Array.isArray(p.leaderboard)&&p.leaderboard.length<=30&&p.leaderboard.every(x=>x&&typeof x.mode==='string'&&modes.includes(x.mode)&&typeof x.date==='string'&&x.date.length<=40&&Number.isFinite(x.score)&&x.score>=0&&x.score<=100000)&&p.resources&&['supplies','morale','hull'].every(k=>Number.isInteger(p.resources[k])&&p.resources[k]>=0&&p.resources[k]<=100));}
function validWorkshop(q){return Array.isArray(q)&&q.length<=50&&q.every(x=>x&&['ro','en'].every(l=>typeof x[l]==='string'&&x[l].length>0&&x[l].length<=300)&&Number.isInteger(x.correct)&&x.correct>=0&&x.correct<3&&['answersRo','answersEn'].every(k=>Array.isArray(x[k])&&x[k].length===3&&x[k].every(a=>typeof a==='string'&&a.length>0&&a.length<=150)));}
function migrate(v){const s=fresh();if(v&&Array.isArray(v.done)&&v.done.every((n,i)=>n===i)&&v.done.length<=12){s.prefs.lang=v.lang==='en'?'en':'ro';s.prefs.light=!!v.light;s.prefs.contrast=!!v.contrast;s.prefs.still=!!v.still;v.done.forEach(i=>{s.profiles[0].levels[i]=10;for(let j=0;j<10;j++)s.profiles[0].earned.push(`story:${i}:${j}`)});s.profiles[0].wallet=v.done.length*100;}return s;}
function hash(s){let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let a=hash(seed);return()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function shuffle(a,r){const out=[...a];for(let i=out.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out}
function generate(chapter,stage,difficulty,seed){const r=rng(`${seed}:${chapter}:${stage}:${difficulty}`),size=difficulty==='easy'?3:difficulty==='hard'?5:4;return {r,size,sequence:Array.from({length:Math.min(6,size+Math.floor(stage/4))},()=>Math.floor(r()*4)),cards:shuffle(Array.from({length:size*2},(_,i)=>i%size),r),target:Math.floor(r()*4),heading:Math.floor(r()*4),lanes:Array.from({length:size+2},()=>Math.floor(r()*3)),order:shuffle([0,1,2,3],r),quiz:shuffle([0,1,2],r),pos:10*Math.floor(r()*11)}}
function award(p,id){if(p.earned.includes(id))return false;if(p.earned.length>=2000)p.earned.splice(p.earned.findIndex(x=>!x.startsWith('story:')),1);p.earned.push(id);p.wallet+=10;return true}
function progress(p,ch,stage){if(ch<0||ch>11||stage<0||stage>9||ch>0&&p.levels[ch-1]<10||stage!==p.levels[ch])return false;p.levels[ch]++;award(p,`story:${ch}:${stage}`);return true}
function buy(p,skin){const cost={default:0,night:100,gold:200}[skin];if(cost===undefined)return false;if(!p.skins.includes(skin)){if(p.wallet<cost)return false;p.wallet-=cost;p.skins.push(skin)}p.skin=skin;return true}
function plan(mode,seed,route){const r=rng(seed),count={short:3,daily:3,challenge:6,tournament:12,navigator:6,duo:6}[mode]||12;return Array.from({length:count},(_,i)=>({ch:mode==='navigator'?[2,3,7][i%3]:mode==='tournament'?i:route?route[i%route.length]:Math.floor(r()*12),stage:Math.floor(r()*10)}))}
function dateKey(d=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Bucharest',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
return {key,modes,fresh,freshProfile,validate,validWorkshop,migrate,hash,rng,shuffle,generate,award,progress,buy,plan,dateKey};})();if(typeof module!=='undefined')module.exports=Engine;
