'use strict';
(()=>{
const text=(ro,eng)=>en()?eng:ro;
const panel=node('section',undefined,'panel');panel.id='expedition';$('notice').before(panel);
let peer=null,channel=null,incoming=null,invitation=null,localWins=0,remoteWins=0;
let decisions={};try{const d=JSON.parse(localStorage.getItem('odyssey-choices-v1'));if(d&&typeof d==='object'&&!Array.isArray(d))decisions=d}catch{}
const choices=[
[0,'Îi aduci pe cercetași la corabie?','Bring the scouts back?','Îi salvez','Rescue them','Îi las pe insulă','Leave them on the island'],
[1,'Îți dezvălui numele ciclopului?','Reveal your name to the Cyclops?','Păstrez secretul','Keep it secret','Îmi spun numele','Reveal my name'],
[2,'Cum păstrezi sacul vânturilor?','How do you guard the wind bag?','Explic echipajului','Explain to the crew','Ascund secretul','Keep it secret'],
[4,'Când pleci de la Circe?','When do you leave Circe?','Pregătesc plecarea','Prepare to leave','Rămân încă un an','Stay another year'],
[8,'Respecți avertismentul lui Helios?','Heed Helios’s warning?','Protejez vitele','Protect the cattle','Ignor avertismentul','Ignore the warning']];
const key=i=>`${state.active}:${i}`;
function pick(i,value){decisions[key(i)]=value;try{localStorage.setItem('odyssey-choices-v1',JSON.stringify(decisions))}catch{notice(t('localError'))}draw()}
function ending(){const rescue=decisions[key(0)]===0,caution=decisions[key(1)]===0,trust=decisions[key(2)]===0,cattle=decisions[key(8)]===0;return !cattle?text('Final imaginar: corabia este pierdută; Odiseu continuă singur.','Imaginary ending: the ship is lost; Odysseus continues alone.'):rescue&&caution&&trust?text('Final imaginar: echipajul revine împreună, după o călătorie prudentă.','Imaginary ending: the crew returns together after a cautious voyage.'):text('Final imaginar: echipajul supraviețuiește, dar neîncrederea prelungește întoarcerea.','Imaginary ending: the crew survives, but distrust delays the return.')}
const story=node('div');const title=node('h2');panel.append(title,story);
function draw(){title.textContent=text('Expediție conectată și alegeri','Connected expedition and choices');story.replaceChildren();story.append(node('h3',text('Campanie imaginară','Imaginary campaign')),node('p',text('Alegerile de mai jos schimbă relatarea și finalul. Sunt ficțiune, separate de poem și de progresul probelor.','These choices change the account and ending. They are fiction, separate from the poem and trial progression.')));
for(const [i,ro,eng,a,ae,b,be] of choices){const row=node('div',undefined,'logentry');row.append(node('h4',`${D[i][en()?3:2]} · ${text(ro,eng)}`));[text(a,ae),text(b,be)].forEach((label,v)=>{const btn=button(label,()=>pick(i,v),row);btn.setAttribute('aria-pressed',String(decisions[key(i)]===v))});const v=decisions[key(i)];if(v!==undefined)row.append(node('p',v===0?text('Consecință: crește încrederea și scade riscul călătoriei.','Consequence: trust rises and the voyage becomes safer.'):text('Consecință: crește riscul și întoarcerea este întârziată.','Consequence: risk rises and the return is delayed.')));story.append(row)}
const selected=choices.filter(([i])=>decisions[key(i)]===0||decisions[key(i)]===1).length;story.append(node('p',selected===choices.length?ending()+(decisions[key(4)]===1?text(' Popasul la Circe adaugă un an.',' The stay with Circe adds a year.'):''):text(`Alege toate cele ${choices.length} decizii pentru final.`,`Make all ${choices.length} choices to reveal the ending.`)));}
const net=node('div');panel.append(net);net.append(node('h3',text('Duel WebRTC experimental și transfer între dispozitive','Experimental WebRTC duel and device transfer')),node('p',text('Conexiune directă WebRTC. Schimbați manual codurile printr-un canal privat. STUN folosește Cloudflare; nu există server TURN, deci unele rețele pot bloca legătura. Profilurile sunt trimise numai când alegi transferul.','Direct WebRTC connection. Exchange codes manually through a private channel. STUN uses Cloudflare; no TURN server is provided, so some networks may block connections. Profiles are sent only when you choose transfer.')));
const status=node('p');status.setAttribute('role','status');const score=node('p');net.append(status,score);
const output=node('textarea');output.id='connectionCode';output.readOnly=true;output.rows=4;output.setAttribute('aria-label',text('Codul tău de conexiune','Your connection code'));net.append(output);net.append(node('p',text('Backupul transmis include cele trei profiluri, preferințele și părerile locale. Alegerile narative rămân pe dispozitiv.','The transferred backup contains all three profiles, preferences and local opinions. Narrative choices remain on this device.')));
const input=node('textarea');input.id='remoteCode';input.rows=4;input.maxLength=30000;input.setAttribute('aria-label',text('Cod primit de la partener','Code received from partner'));net.append(input);
function setStatus(ro,eng){status.textContent=text(ro,eng)}
function reset(){channel?.close();peer?.close();peer=null;channel=null;incoming=null;invitation=null;localWins=remoteWins=0;output.value='';score.textContent='';setStatus('Deconectat.','Disconnected.')}
function updateScore(){score.textContent=text(`Tu: ${localWins} · Partener: ${remoteWins}`,`You: ${localWins} · Partner: ${remoteWins}`)}
function attach(c){channel=c;c.onopen=()=>{setStatus('Conectat. Alegeți aceeași sămânță și porniți provocarea.','Connected. Choose the same seed and start the challenge.');updateScore()};c.onclose=()=>setStatus('Legătura s-a închis.','Connection closed.');c.onerror=()=>setStatus('Eroare de conexiune.','Connection error.');c.onmessage=e=>{try{if(typeof e.data!=='string'||e.data.length>150000)return;const m=JSON.parse(e.data);if(m.type==='result'&&Number.isInteger(m.score)&&m.score>=0&&m.score<=100){remoteWins+=m.score;updateScore()}else if(m.type==='challenge'&&typeof m.seed==='string'&&m.seed.length<=80&&['easy','normal','hard'].includes(m.difficulty)){invitation=m;setStatus('Invitație primită. Acceptă pentru aceleași probe și dificultate.','Invitation received. Accept to play the same trials and difficulty.')}else if(m.type==='backup'&&Engine.validate(m.state)){incoming=m.state;setStatus('Backup primit. Verifică și acceptă pentru a înlocui profilurile locale.','Backup received. Review and accept to replace local profiles.')}}catch{setStatus('Mesaj invalid ignorat.','Invalid message ignored.')}}}
function create(){reset();if(!window.RTCPeerConnection)throw Error(text('WebRTC nu este disponibil.','WebRTC unavailable.'));peer=new RTCPeerConnection({iceServers:[{urls:'stun:stun.cloudflare.com:3478'}]});peer.ondatachannel=e=>attach(e.channel);peer.onconnectionstatechange=()=>{if(peer?.connectionState==='failed')setStatus('Conexiune blocată. Încearcă aceeași rețea sau folosește exportul JSON.','Connection blocked. Try the same network or use JSON export.')};return peer}
async function code(p){await new Promise(resolve=>{if(p.iceGatheringState==='complete')return resolve();const stop=()=>{p.removeEventListener('icegatheringstatechange',watch);resolve()};const watch=()=>{if(p.iceGatheringState==='complete')stop()};p.addEventListener('icegatheringstatechange',watch);setTimeout(stop,8000)});if(!p.localDescription.sdp.includes('a=candidate:'))throw Error(text('Browserul nu a oferit o rută de rețea. Conexiunea directă nu poate porni aici. Folosește export/import JSON.','The browser provided no network route. Direct connection cannot start here. Use JSON export/import.'));output.value=JSON.stringify(p.localDescription);setStatus('Cod pregătit. Copiază-l și trimite-l partenerului.','Code ready. Copy it and send it to your partner.')}
function parse(){let m=JSON.parse(input.value);if(!m||!['offer','answer'].includes(m.type)||typeof m.sdp!=='string'||m.sdp.length>29000)throw Error(text('Cod invalid.','Invalid code.'));return {type:m.type,sdp:m.sdp}}
function action(ro,eng,fn){const b=button(text(ro,eng),async()=>{b.disabled=true;try{await fn()}catch(e){status.textContent=e.message}finally{b.disabled=false}},net);return b}
action('1. Găzduiește','1. Host',async()=>{const p=create();attach(p.createDataChannel('odyssey'));await p.setLocalDescription(await p.createOffer());await code(p)});
action('2. Intră cu oferta primită','2. Join with received offer',async()=>{const m=parse();if(m.type!=='offer')throw Error('Expected offer');const p=create();await p.setRemoteDescription(m);await p.setLocalDescription(await p.createAnswer());await code(p)});
action('3. Gazda aplică răspunsul','3. Host applies answer',async()=>{const m=parse();if(!peer||m.type!=='answer')throw Error(text('Creează întâi oferta.','Create an offer first.'));await peer.setRemoteDescription(m)});
action('Invită la aceleași probe','Invite to identical trials',()=>{if(channel?.readyState!=='open')throw Error(text('Conectează întâi dispozitivele.','Connect devices first.'));const roundSeed=$('seed').value.trim().slice(0,80)||'ITHACA';channel.send(JSON.stringify({type:'challenge',seed:roundSeed,difficulty:state.prefs.difficulty}));localWins=remoteWins=0;start('challenge',roundSeed);updateScore()});
action('Acceptă provocarea','Accept challenge',()=>{if(!invitation)throw Error(text('Nu există invitație.','No invitation.'));state.prefs.difficulty=invitation.difficulty;save();localWins=remoteWins=0;start('challenge',invitation.seed);invitation=null;updateScore();setStatus('Provocarea comună a început.','Shared challenge started.')});
action('Trimite backupul','Send backup',()=>{if(channel?.readyState!=='open')throw Error(text('Conectează întâi dispozitivele.','Connect the devices first.'));channel.send(JSON.stringify({type:'backup',state}));setStatus('Backup trimis; așteaptă acceptarea pe celălalt dispozitiv.','Backup sent; accept it on the other device.')});
action('Acceptă backupul primit','Accept received backup',()=>{if(!incoming)throw Error(text('Nu există backup primit.','No received backup.'));if(!confirm(text('Înlocuiești profilurile locale cu backupul primit?','Replace local profiles with the received backup?')))return;state=incoming;incoming=null;save();start('story');draw();setStatus('Backup aplicat.','Backup applied.')});
action('Deconectează','Disconnect',reset);
document.addEventListener('odyssey-quest:result',e=>{if(channel?.readyState==='open'){const n=e.detail.score;channel.send(JSON.stringify({type:'result',score:n}));localWins+=n;updateScore()}});
const feedback=node('div');panel.append(feedback);feedback.append(node('h3',text('Trimite părerea către autor','Send feedback to the author')),node('p',text('Se deschide o cerere GitHub precompletată. Necesită cont GitHub; mesajul devine public numai după ce alegi Submit. Nu include date personale.','Opens a prefilled GitHub issue. A GitHub account is required; your message becomes public only after you choose Submit. Do not include personal information.')));
const link=node('a',text('Revizuiește și trimite pe GitHub','Review and send on GitHub'));link.target='_blank';link.rel='noopener noreferrer';link.href='https://github.com/LaurAndreea10/codepen-portfolio/issues/new';link.onclick=()=>{link.href='https://github.com/LaurAndreea10/codepen-portfolio/issues/new?title='+encodeURIComponent('Odyssey Quest — feedback')+'&body='+encodeURIComponent($('opinion').value.slice(0,2000)||text('Părerea mea despre Odyssey Quest:','My feedback on Odyssey Quest:'))};feedback.append(link);
$('language').addEventListener('change',()=>location.reload());$('profile').addEventListener('change',draw);draw();reset();
})();
