// Portofoliu — păreri aprobate, citite direct din GitHub Issues (etichetele „feedback” + „approved”).
// Nu are nevoie de server: aprobarea înseamnă doar adăugarea etichetei „approved” pe Issue.
(()=>{
const OWNER='LaurAndreea10',REPO='codepen-portfolio',CACHE='portfolio_testimonials_v1',TTL=10*60*1000;
const box=document.getElementById('testimonials');if(!box)return;const list=box.querySelector('[data-testimonials-list]');if(!list)return;
const en=(document.documentElement.lang||'ro').toLowerCase().startsWith('en');
const T=en?{roles:{parent:'parent',teacher:'teacher',developer:'developer',other:''},stars:'{n} of 5 stars',anon:'Anonymous visitor',projects:{'curious-garden':['Curious Garden','../curious-garden/']}}:{roles:{parent:'părinte',teacher:'profesor',developer:'dezvoltator',other:''},stars:'{n} din 5 stele',anon:'Vizitator anonim',projects:{'curious-garden':['Grădina Curioasă','curious-garden/']}};
if(!document.getElementById('testimonials-style')){const st=document.createElement('style');st.id='testimonials-style';st.textContent='.testimonial-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:16px;margin-top:18px}.testimonial{margin:0;padding:20px;border:1px solid var(--line,rgba(127,127,127,.35));border-radius:18px;background:var(--panel,transparent);display:flex;flex-direction:column;gap:10px}.testimonial blockquote{margin:0;color:var(--text,inherit);font-size:1.02rem;line-height:1.6}.testimonial blockquote::before{content:"„";color:var(--accent,currentColor);font-weight:900;margin-right:2px}.testimonial blockquote::after{content:"”";color:var(--accent,currentColor);font-weight:900}.testimonial .stars{color:var(--accent,#ffc978);letter-spacing:2px}.testimonial figcaption{color:var(--muted,inherit);font-size:.92rem}.testimonial figcaption a{color:inherit}';document.head.append(st)}
function parse(items){const out=[];for(const i of items||[]){if(i.pull_request||i.user?.login!==OWNER)continue;const labels=(i.labels||[]).map(l=>typeof l==='string'?l:l.name);if(!labels.includes('approved')||!labels.includes('feedback'))continue;const m=/```json\s*([\s\S]*?)```/.exec(i.body||'');if(!m)continue;let d;try{d=JSON.parse(m[1])}catch{continue}const text=String(d.text||'').replace(/\s+/g,' ').trim();if(text.length<10)continue;out.push({text:text.slice(0,600),name:String(d.name||'').trim().slice(0,60),role:String(d.role||''),rating:Math.max(0,Math.min(5,parseInt(d.rating,10)||0)),project:String(d.project||''),date:/^\d{4}-\d{2}-\d{2}$/.test(d.date)?d.date:''})}return out}
function render(items){if(!items.length){box.hidden=true;return}list.replaceChildren(...items.slice(0,9).map(t=>{const f=document.createElement('figure');f.className='testimonial';if(t.rating){const s=document.createElement('span');s.className='stars';s.textContent='★'.repeat(t.rating)+'☆'.repeat(5-t.rating);s.setAttribute('role','img');s.setAttribute('aria-label',T.stars.replace('{n}',t.rating));f.append(s)}const q=document.createElement('blockquote');q.textContent=t.text;f.append(q);const c=document.createElement('figcaption');const who=[t.name||T.anon,T.roles[t.role]||''].filter(Boolean).join(', ');c.append('— '+who);const p=T.projects[t.project];if(p){c.append(' · ');const a=document.createElement('a');a.href=p[1];a.textContent=p[0];c.append(a)}if(t.date){c.append(' · ');const time=document.createElement('time');time.dateTime=t.date;time.textContent=new Date(t.date+'T12:00:00').toLocaleDateString(en?'en-GB':'ro-RO',{month:'long',year:'numeric'});c.append(time)}f.append(c);return f}));box.hidden=false}
try{const c=JSON.parse(sessionStorage.getItem(CACHE)||'null');if(c&&Date.now()-c.at<TTL){render(c.items);return}}catch{}
fetch(`https://api.github.com/repos/${OWNER}/${REPO}/issues?labels=feedback,approved&state=all&per_page=30&sort=created&direction=desc`,{headers:{Accept:'application/vnd.github+json'}}).then(r=>r.ok?r.json():[]).then(items=>{const parsed=parse(items);try{sessionStorage.setItem(CACHE,JSON.stringify({at:Date.now(),items:parsed}))}catch{}render(parsed)}).catch(()=>{box.hidden=true});
})();
