const {chromium}=require('playwright');const assert=require('node:assert/strict');const path=require('node:path');
(async()=>{
const browser=await chromium.launch({headless:true,...(process.env.BOOSCARY_BROWSER?{executablePath:process.env.BOOSCARY_BROWSER}:{}),...(process.env.BOOSCARY_ARGS?{args:JSON.parse(process.env.BOOSCARY_ARGS)}:{})});const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true});await page.addInitScript(()=>{window.__booscaryTestNoGate=true});const errors=[];page.on('pageerror',e=>errors.push(e.message));const url=process.env.BOOSCARY_URL||'file://'+path.resolve(__dirname,'index.html');await page.goto(url);assert.match(await page.locator('header .badge').innerText(),/(3\.1\.0|4\.\d\.0)/);
await page.click('[data-activity="workshop"]');await page.locator('[data-part="left"]').click();const before=await page.evaluate(()=>JSON.stringify(pumpkin));await page.click('#quick-undo');assert.equal(await page.evaluate(()=>pumpkin.parts.length),0);await page.click('#redo');assert.equal(await page.evaluate(()=>JSON.stringify(pumpkin)),before);await page.click('#quick-undo');await page.locator('[data-part="right"]').click();assert.equal(await page.locator('#redo').isDisabled(),true);
await page.locator('#work-zoom').evaluate(el=>{el.value='2';el.dispatchEvent(new Event('input'))});assert.equal(await page.locator('#pumpkin-stage svg').getAttribute('viewBox'),'100 97 200 160');await page.locator('[data-part="nose"]').click();assert.equal(await page.locator('#pumpkin-stage svg').getAttribute('viewBox'),'100 97 200 160');
await page.locator('#work-zoom').evaluate(el=>{el.value='1';el.dispatchEvent(new Event('input'))});await page.click('[data-quick="contour"]');await page.locator('#pumpkin-stage svg').evaluate(el=>el.scrollIntoView({block:'center'}));const box=await page.locator('#pumpkin-stage svg').boundingBox();await page.mouse.move(box.x+box.width*.4,box.y+box.height*.4);await page.mouse.down();await page.mouse.move(box.x+box.width*.6,box.y+box.height*.5,{steps:8});assert.equal(await page.evaluate(()=>contourPreview),true);assert.equal(await page.locator('#pumpkin-stage [stroke-dasharray]').count(),1);await page.mouse.move(box.x+box.width*.5,box.y+box.height*.65,{steps:8});await page.mouse.up();assert.equal(await page.evaluate(()=>contourPreview),false);assert.equal(await page.locator('#pumpkin-stage [stroke-dasharray]').count(),0);assert.match(await page.locator('#pumpkin-stage svg').innerHTML(),/ Q/);
await page.locator('#sound-volume').evaluate(el=>{el.value='15';el.dispatchEvent(new Event('input'))});assert.equal(await page.evaluate(()=>volume),.15);await page.click('#activity-sound');await page.click('#light');assert.equal(await page.evaluate(()=>soundOn),true);
await page.click('#exit-activity');await page.click('[data-activity="faces"]');for(let i=0;i<5;i++){const index=await page.evaluate(()=>mini.options.indexOf(mini.target));await page.locator('#mini-content button').nth(index).click()}assert.equal(await page.evaluate(()=>records.faces.best),5);assert.deepEqual(await page.evaluate(()=>records.faces.completed),[1]);await page.click('#exit-activity');await page.click('[data-activity="collection"]');const backup=await page.evaluate(()=>JSON.stringify({version:3,gallery,progress:career,best,records}));const unchanged=await page.evaluate(()=>JSON.stringify(records));const invalid=JSON.parse(backup);invalid.records.faces.best=null;assert.equal(await page.evaluate(text=>{try{importBackupText(text);return false}catch{return true}},JSON.stringify(invalid)),true);assert.equal(await page.evaluate(()=>JSON.stringify(records)),unchanged);await page.evaluate(text=>importBackupText(text),backup);
await page.reload();assert.equal(await page.evaluate(()=>volume),.15);assert.equal(await page.evaluate(()=>records.faces.best),5);await page.click('[data-activity="workshop"]');await page.locator('#light-intensity').scrollIntoViewIfNeeded();const stageRect=await page.locator('#pumpkin-stage').boundingBox();assert(stageRect.y>=0&&stageRect.y<300);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.click('#exit-activity');await page.click('#lang');assert.match(await page.locator('#records-title').innerText(),/Progress/);await page.setViewportSize({width:360,height:800});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.setViewportSize({width:1280,height:900});await page.click('[data-activity="workshop"]');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.resolve(__dirname,'preview-v31.png'),fullPage:false});assert.deepEqual(errors,[]);await browser.close();console.log('PASS v3.1: undo/redo and branch reset, zoom retained during changes, smooth contour preview/finalization, volume persistence, per-game best/completion persistence, backup records validation/roundtrip, sticky mobile stage, RO/EN, 360/390/1280px, no JS errors'+(process.env.BOOSCARY_URL?' (LIVE)':''));
})().catch(e=>{console.error(e);process.exit(1)});
