const {chromium}=require('playwright');const assert=require('node:assert/strict');const path=require('node:path');
(async()=>{
const browser=await chromium.launch({headless:true,...(process.env.BOOSCARY_BROWSER?{executablePath:process.env.BOOSCARY_BROWSER}:{}),...(process.env.BOOSCARY_ARGS?{args:JSON.parse(process.env.BOOSCARY_ARGS)}:{})});const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('file://'+path.resolve(__dirname,'index.html'));
await page.click('[data-activity="workshop"]');assert.equal(await page.locator('#activity-hub').isVisible(),false);assert.equal(await page.locator('#workshop').isVisible(),true);
await page.click('[data-tool="brush"]');await page.locator('#pumpkin-stage svg').evaluate(el=>el.scrollIntoView({block:'center'}));let box=await page.locator('#pumpkin-stage svg').boundingBox();await page.mouse.move(box.x+box.width*.3,box.y+box.height*.4);await page.mouse.down();await page.mouse.move(box.x+box.width*.5,box.y+box.height*.5,{steps:10});await page.mouse.move(box.x+box.width*.65,box.y+box.height*.6,{steps:10});await page.mouse.up();assert.equal(await page.evaluate(()=>pumpkin.strokes.length),1);assert((await page.evaluate(()=>pumpkin.strokes[0].points.length))>10);
await page.click('[data-tool="contour"]');await page.locator('#pumpkin-stage svg').evaluate(el=>el.scrollIntoView({block:'center'}));box=await page.locator('#pumpkin-stage svg').boundingBox();await page.mouse.move(box.x+box.width*.4,box.y+box.height*.4);await page.mouse.down();await page.mouse.move(box.x+box.width*.55,box.y+box.height*.4,{steps:6});await page.mouse.move(box.x+box.width*.5,box.y+box.height*.6,{steps:6});await page.mouse.up();assert.equal(await page.evaluate(()=>pumpkin.strokes[1].kind),'contour');
await page.click('[data-tool="erase"]');await page.locator('#pumpkin-stage svg').tap({position:{x:box.width*.45,y:box.height*.45}});assert((await page.evaluate(()=>pumpkin.strokes.length))<2);await page.click('#undo');assert.equal(await page.evaluate(()=>pumpkin.strokes.length),2);
await page.selectOption('#pattern','stripes');await page.click('#apply-pattern');assert.equal(await page.evaluate(()=>pumpkin.strokes.length),7);await page.click('#carve-template');assert.equal(await page.evaluate(()=>pumpkin.parts.length),4);
await page.fill('#pumpkin-name','Luna');await page.locator('#pumpkin-name').press('Tab');await page.click('#save-pumpkin');await page.reload();assert.equal(await page.evaluate(()=>gallery[0].name),'Luna');assert.equal(await page.evaluate(()=>gallery[0].strokes.length),7);
await page.click('[data-activity="workshop"]');await page.locator('#pumpkin-gallery button').first().click();const pngPromise=page.waitForEvent('download');await page.click('#export-png');const png=await pngPromise;assert.equal(png.suggestedFilename(),'booscary-pumpkin.png');const pngPath=await png.path();assert.equal(require('fs').readFileSync(pngPath).subarray(1,4).toString(),'PNG');await page.click('#exit-activity');
await page.click('[data-activity="memory"]');const cards=await page.evaluate(()=>mini.cards);const pairs={};cards.forEach((icon,i)=>(pairs[icon]??=[]).push(i));for(const indexes of Object.values(pairs))for(const i of indexes)await page.locator('#mini-content button').nth(i).click();assert.equal(await page.evaluate(()=>mini.done),true);assert.equal(await page.evaluate(()=>career.wins),1);await page.click('#exit-activity');
await page.click('[data-activity="faces"]');for(let i=0;i<5;i++){const index=await page.evaluate(()=>mini.options.indexOf(mini.target));await page.locator('#mini-content button').nth(index).click()}assert.equal(await page.evaluate(()=>mini.done),true);await page.click('#exit-activity');await page.click('#claim-daily');assert.equal(await page.evaluate(()=>career.claimed),true);const coins=await page.evaluate(()=>career.coins);await page.click('#claim-daily');assert.equal(await page.evaluate(()=>career.coins),coins);
await page.click('[data-activity="maze"]');for(const level of ['1','2','3']){await page.selectOption('#mini-level',level);const steps=await page.evaluate(()=>{const map=mini.map;let pos=mini.pos;const steps=[];for(const target of [...mini.lanterns,{x:5,y:3}]){const q=[{p:pos,path:[]}],seen=new Set();while(q.length){const {p,path}=q.shift();if(p.x===target.x&&p.y===target.y){steps.push(...path);pos=target;break}const key=p.x+','+p.y;if(seen.has(key))continue;seen.add(key);for(const [name,dx,dy] of [['up',0,-1],['down',0,1],['left',-1,0],['right',1,0]]){const x=p.x+dx,y=p.y+dy;if(map[y]?.[x]==='.')q.push({p:{x,y},path:[...path,name]})}}}return steps});for(const dir of steps)await page.click(`[data-direction="${dir}"]`);assert.equal(await page.evaluate(()=>mini.done),true)}await page.click('#exit-activity');
await page.click('[data-activity="model"]');await page.evaluate(()=>{pumpkin=normalizePumpkin(model);workRender()});await page.click('#check-model');assert.match(await page.locator('#work-status').innerText(),/20 XP/);await page.click('#exit-activity');
await page.click('[data-activity="collection"]');await page.locator('#accessory-shop button').nth(2).click();assert.equal(await page.evaluate(()=>career.owned.includes('hat')),true);assert.equal(await page.evaluate(()=>pumpkin.accessory),'hat');
const backupPromise=page.waitForEvent('download');await page.click('#backup-export');const backup=await backupPromise;const backupText=require('fs').readFileSync(await backup.path(),'utf8');const exported=JSON.parse(backupText);assert.equal(exported.version,3);
const before=await page.evaluate(()=>JSON.stringify({gallery,career}));for(const modify of [x=>x.progress.coins=null,x=>x.gallery[0].strokes=null,x=>x.gallery[0].parts=null,x=>x.gallery[0].strokes[0].points[0].x=10000,x=>x.progress.owned=['bad']]){const invalid=JSON.parse(backupText);modify(invalid);await page.locator('#backup-import').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(invalid))});await page.waitForFunction(()=>document.getElementById('backup-import').value==='');assert.match(await page.locator('#backup-status').innerText(),/invalid/i);assert.equal(await page.evaluate(()=>JSON.stringify({gallery,career})),before)}
await page.locator('#backup-import').setInputFiles({name:'good.json',mimeType:'application/json',buffer:Buffer.from(backupText)});await page.waitForFunction(()=>document.getElementById('backup-import').value==='');assert.match(await page.locator('#backup-status').innerText(),/importat/);
assert.equal(await page.evaluate(()=>{const old=Storage.prototype.setItem,keys=['booscary-gallery-v2','booscary-progress-v3','booscary-best-v1'],before=keys.map(k=>localStorage.getItem(k)),beforeMemory=JSON.stringify({gallery,career,best});let failed=false;Storage.prototype.setItem=function(k,v){if(k==='booscary-progress-v3'&&!failed){failed=true;throw Error('quota simulation')}return old.call(this,k,v)};let rejected=false;try{importBackupText(JSON.stringify({version:3,gallery,progress:career,best}))}catch{rejected=true}finally{Storage.prototype.setItem=old}return rejected&&beforeMemory===JSON.stringify({gallery,career,best})&&keys.every((k,i)=>before[i]===localStorage.getItem(k))}),true);
await page.click('#exit-activity');await page.click('#lang');await page.click('[data-activity="workshop"]');assert.match(await page.locator('.v3-controls h3').innerText(),/Advanced/);await page.click('#steady-light');assert.equal(await page.locator('#steady-light').getAttribute('aria-pressed'),'true');await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.evaluate(()=>{const e=document.querySelector('.lantern-fire');return !e||getComputedStyle(e).animationName==='none'}),true);
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.setViewportSize({width:360,height:800});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.locator('#workshop').screenshot({path:path.resolve(__dirname,'preview-v3.png')});await page.setViewportSize({width:1280,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const xp=await page.evaluate(()=>career.xp);await page.reload();assert.equal(await page.evaluate(()=>career.xp),xp);assert.deepEqual(errors,[]);await browser.close();console.log('PASS v3: drawing, contours, eraser, undo, patterns, names, gallery reload, PNG, Memory, face match, 3 solvable mazes, model game, XP/coins persistence, daily reward once, shop, JSON export/import and 5 invalid nested backups, storage failure rollback, focused view, RO/EN, steady/reduced motion, 360/390/1280px, no JS errors.');
})().catch(e=>{console.error(e);process.exit(1)});
