const assert=require('node:assert/strict');const fs=require('fs');const path=require('path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const BASE=process.env.BASE_URL||'http://localhost:8000';
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox','--disable-dev-shm-usage']});const p=await b.newPage({viewport:{width:1440,height:1000}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(BASE+'/');await p.waitForFunction(()=>typeof puzzle!=='undefined');
async function clickControls(i){await p.locator('#controls button').nth(i).click()}
async function solve(){const ch=await p.evaluate(()=>window.ch??ch);const isQuiz=await p.evaluate(()=>mode==='quiz'||mode==='workshop');if(isQuiz){const i=await p.evaluate(()=>puzzle.quizOrder.indexOf(mode==='workshop'?state.workshop[run.index].correct:0));await p.locator('#task button').nth(i).click();return}
if(ch===0){const cards=await p.evaluate(()=>puzzle.cards);for(const value of [...new Set(cards)])for(let i=0;i<cards.length;i++)if(cards[i]===value)await p.locator('#task button').nth(i).click()}
if(ch===1){for(let i=0;i<4;i++)await clickControls(2);for(let i=0;i<4;i++)await clickControls(3)}
if(ch===2){const [a,z]=await p.evaluate(()=>[puzzle.heading,puzzle.target]);for(let i=0;i<(z-a+4)%4;i++)await clickControls(0);await clickControls(1)}
if(ch===3){for(const lane of await p.evaluate(()=>puzzle.lanes))await clickControls(lane)}
if(ch===4||ch===6){for(const i of await p.evaluate(()=>puzzle.sequence))await clickControls(i)}
if(ch===5){for(let i=0;i<3;i++){const idx=await p.evaluate(i=>puzzle.order.filter(x=>x<3).indexOf(i),i);await clickControls(idx)}}
if(ch===7){const target=await p.evaluate(()=>6+stage%5);for(let i=0;i<target;i++)await clickControls(1)}
if(ch===8){const supply=await p.evaluate(()=>puzzle.supplies);for(let i=supply;i<5;i++)await clickControls(0);for(let i=0;i<3;i++)await clickControls(1)}
if(ch===9){for(let i=0;i<4;i++){const idx=await p.evaluate(i=>puzzle.order.indexOf(i),i);await clickControls(idx)}}
if(ch===10){const list=await p.evaluate(()=>puzzle.orderItems);for(const value of list){const idx=await p.evaluate(value=>Engine.shuffle(puzzle.orderItems,Engine.rng(seed+stage)).indexOf(value),value);await clickControls(idx)}}
if(ch===11){await p.locator('#task input').fill('50');await clickControls(2)}}
for(let trial=0;trial<120;trial++){await solve();assert(await p.locator('#next').isEnabled(),`trial ${trial}`);if(trial<119)await p.locator('#next').click()}
await p.evaluate(()=>{state.prefs.scan=true;scanIndex=0;scanTick()});assert.equal(await p.evaluate(()=>scanned.id),'next');await p.evaluate(()=>{state.prefs.scan=false});assert.equal(await p.locator('#completed').textContent(),'120 / 120');assert.equal(await p.locator('#coins').textContent(),'1200');await p.locator('#retry').click();await solve();assert.equal(await p.locator('#coins').textContent(),'1200');await p.reload();assert.equal(await p.locator('#completed').textContent(),'120 / 120');
await p.selectOption('#language','en');await p.selectOption('#mode','explore');await p.locator('#chapterList button').nth(0).click();await p.locator('#pause').click();const before=await p.evaluate(()=>puzzle.flipped.length);await p.locator('#task button').first().click();assert.equal(await p.evaluate(()=>puzzle.flipped.length),before);await p.locator('#pause').click();
await p.selectOption('#timer','120');await p.evaluate(()=>remaining=.15);await p.waitForTimeout(500);assert.match(await p.locator('#feedback').textContent(),/Time is up/);await p.locator('#extend').click();assert((await p.evaluate(()=>remaining))>100);await p.selectOption('#timer','0');
for(const mode of ['short','daily','challenge','tournament','zen','quiz','navigator','duo']){await p.selectOption('#mode',mode);await solve();assert(await p.locator('#next').isEnabled(),mode);assert.equal(await p.locator('#mode').inputValue(),mode)}
await p.locator('#workshopSave').click();assert.equal(await p.locator('#mode').inputValue(),'workshop');await solve();await p.selectOption('#mode','daily');const daily=await p.evaluate(()=>JSON.stringify(run.plan));await p.selectOption('#mode','explore');await p.selectOption('#mode','daily');assert.equal(await p.evaluate(()=>JSON.stringify(run.plan)),daily);
await p.locator('#settings').click();await p.selectOption('#profile',{value:'1'});assert.equal(await p.locator('#completed').textContent(),'0 / 120');await p.locator('#highContrast').check();await p.locator('#reduceMotion').check();await p.selectOption('#font','130');await p.selectOption('#profile',{value:'0'});assert.equal(await p.locator('#completed').textContent(),'120 / 120');const dl=p.waitForEvent('download');await p.locator('#backup').click();const download=await dl;const backup=JSON.parse(fs.readFileSync(await download.path(),'utf8'));assert.equal(backup.version,2);const bad=Buffer.from('{"app":"odyssey-quest","version":2}');await p.setInputFiles('#backupFile',{name:'bad.json',mimeType:'application/json',buffer:bad});assert.equal(await p.locator('#completed').textContent(),'120 / 120');await p.selectOption('#font','100');await p.locator('#highContrast').uncheck();await p.locator('#reduceMotion').uncheck();await p.locator('#closeSettings').click();await p.selectOption('#mode','explore');await p.locator('#chapterList button').nth(11).click();await p.locator('#theme').click();
const out=path.join(__dirname,'../qa');fs.mkdirSync(out,{recursive:true});await p.screenshot({path:path.join(out,'desktop.png'),fullPage:false});await p.setViewportSize({width:390,height:844});await p.screenshot({path:path.join(out,'mobile.png'),fullPage:false});assert(!(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth)),'mobile overflow');await p.emulateMedia({reducedMotion:'reduce'});await p.locator('#settings').click();await p.selectOption('#font','130');await p.locator('#closeSettings').click();assert(!(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth)),'large text overflow');await p.setViewportSize({width:320,height:800});assert(!(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth)),'320px overflow');await p.locator('#settings').click();await p.selectOption('#font','100');await p.locator('#closeSettings').click();
if(process.env.AXE_MODULE){await p.addScriptTag({path:require.resolve(process.env.AXE_MODULE+'/axe.min.js')});const axe=await p.evaluate(async()=>await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));fs.writeFileSync(path.join(out,'axe.json'),JSON.stringify(axe.violations,null,2));assert.equal(axe.violations.length,0,JSON.stringify(axe.violations.map(x=>({id:x.id,nodes:x.nodes.map(n=>n.target)}))))}
await p.evaluate(async()=>{await navigator.serviceWorker.ready});await p.reload();await p.waitForFunction(()=>navigator.serviceWorker.controller!==null);await p.context().setOffline(true);await p.reload();assert.equal(await p.locator('#completed').textContent(),'120 / 120');await p.context().setOffline(false);assert.deepEqual(errors,[]);await b.close();console.log('PASS: 120 interactive trials; duplicate prevention; reload; pause; timer; all modes; seeded daily; workshop; profiles; preferences; backup; 390/320px layout; optional axe; offline reload; no runtime errors.');})();
