const sports=['basket','football','volley','handball','polo','golf','bowling','target'];
const allowed=new Set(['https://slidestorm-arena.plugaru-laura10.chatgpt.site','https://laurandreea10.github.io']);
const failure=(status,message)=>Object.assign(new Error(message),{status});
const json=(data,status=200,origin='')=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...(allowed.has(origin)?{'Access-Control-Allow-Origin':origin,'Vary':'Origin'}:{})}});
async function hash(token){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token)))].map(v=>v.toString(16).padStart(2,'0')).join('')}
function name(input){if(typeof input!=='string'||input.trim().length<1||input.trim().length>24||/[\x00-\x1f]/.test(input))throw failure(400,'Pseudonim invalid / Invalid nickname');return input.trim()}
function code(){return [...crypto.getRandomValues(new Uint8Array(6))].map(v=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[v%32]).join('')}
async function body(request){if(Number(request.headers.get('Content-Length'))>4096)throw failure(413,'Request too large');const raw=await request.text();if(raw.length>4096)throw failure(413,'Request too large');try{const b=JSON.parse(raw);if(!b||typeof b!=='object'||Array.isArray(b))throw Error();return b}catch(e){throw failure(400,'JSON invalid / Invalid JSON')}}
async function getRoom(db,id){const room=await db.prepare('SELECT code,sport,level,seed,created,expires FROM rooms WHERE code = ? AND expires > ?').bind(id,Date.now()).first();if(!room)throw failure(404,'Camera a expirat / Room not found or expired');const {results}=await db.prepare('SELECT id,name,seat,score,won,elapsed FROM players WHERE room = ? ORDER BY seat').bind(id).all();return{...room,players:results}}
async function member(db,request,id){const token=request.headers.get('X-Room-Token');if(!token||token.length>100)throw failure(401,'Token required');const player=await db.prepare('SELECT id,room,score FROM players WHERE token_hash = ? AND room = ?').bind(await hash(token),id).first();if(!player)throw failure(403,'Not a room member');return player}
export async function api(request,env){const url=new URL(request.url),origin=request.headers.get('Origin')||'';if(origin&&!allowed.has(origin))return json({error:'Origin not allowed'},403);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{'Access-Control-Allow-Origin':allowed.has(origin)?origin:url.origin,'Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type,X-Room-Token','Access-Control-Max-Age':'600','Vary':'Origin'}});try{if(!env.DB)throw failure(503,'Online storage unavailable');const db=env.DB,path=url.pathname;
if(path==='/api/health'&&request.method==='GET'){await db.prepare('SELECT 1 AS ok').first();return json({ok:true,version:'2.0.0'},200,origin)}
if(path==='/api/rooms'&&request.method==='POST'){const b=await body(request),nickname=name(b.name);if(!sports.includes(b.sport))throw failure(400,'Invalid sport');const roomCode=code(),token=crypto.randomUUID()+crypto.randomUUID(),id=crypto.randomUUID(),now=Date.now(),seed=crypto.getRandomValues(new Uint32Array(1))[0];const level=seed%100+1;await db.batch([db.prepare('INSERT INTO rooms(code,sport,level,seed,created,expires) VALUES(?,?,?,?,?,?)').bind(roomCode,b.sport,level,seed,now,now+86400000),db.prepare('INSERT INTO players(id,room,seat,name,token_hash) VALUES(?,?,?,?,?)').bind(id,roomCode,1,nickname,await hash(token))]);return json({room:await getRoom(db,roomCode),token,player:id},201,origin)}
let match=path.match(/^\/api\/rooms\/([A-Z2-9]{6})(?:\/(join|score))?$/);if(match){const [,id,action]=match;let room=await getRoom(db,id);if(action==='join'&&request.method==='POST'){const b=await body(request),nickname=name(b.name);if(room.players.length>=2)throw failure(409,'Camera este plină / Room is full');const token=crypto.randomUUID()+crypto.randomUUID(),player=crypto.randomUUID();try{await db.prepare('INSERT INTO players(id,room,seat,name,token_hash) VALUES(?,?,?,?,?)').bind(player,id,2,nickname,await hash(token)).run()}catch(e){if(String(e).includes('UNIQUE'))throw failure(409,'Room is full');throw e}return json({room:await getRoom(db,id),token,player},201,origin)}const player=await member(db,request,id);if(!action&&request.method==='GET')return json(room,200,origin);if(action==='score'&&request.method==='POST'){if(room.players.length<2)throw failure(409,'Așteaptă jucătorul al doilea / Wait for player 2');const b=await body(request);if(!Number.isInteger(b.score)||b.score<0||b.score>2000||typeof b.won!=='boolean'||!Number.isInteger(b.elapsed)||b.elapsed<1000||b.elapsed>180000)throw failure(400,'Invalid score');await db.prepare('UPDATE players SET score=?,won=?,elapsed=?,submitted=? WHERE id=? AND score IS NULL').bind(b.score,b.won?1:0,b.elapsed,Date.now(),player.id).run();return json({room:await getRoom(db,id)},200,origin)}}
if(path==='/api/leaderboard'&&request.method==='GET'){const {results}=await db.prepare('SELECT p.name,p.score,r.sport,r.level FROM players p JOIN rooms r ON p.room=r.code WHERE p.score IS NOT NULL AND p.won=1 AND r.created>? ORDER BY p.score DESC,p.elapsed ASC LIMIT 20').bind(Date.now()-30*86400000).all();return json({rows:results,selfReported:true},200,origin)}throw failure(404,'Not found');
}catch(e){if(!e.status)console.error('SlideStorm online error',String(e));return json({error:e.status?e.message:'Online storage unavailable'},e.status||503,origin)}}
export default{async fetch(request,env,ctx){const url=new URL(request.url);if(url.pathname.startsWith('/api/'))return api(request,env);const key=url.pathname==='/'?'/index.html':url.pathname;const asset=ASSET_MAP[key];if(!asset)return new Response('Not found',{status:404});return new Response(asset.binary?Uint8Array.from(atob(asset.content),c=>c.charCodeAt(0)):asset.content,{headers:{'Content-Type':asset.type,'Cache-Control':key==='/sw.js'?'no-cache':'public,max-age=0,must-revalidate','X-Content-Type-Options':'nosniff'}})}};
