// Grădina Curioasă — Ateliere și meserii: desen, muzică, olărit, croșetat, grădinărit, construcții, doctor, service, gătit.
// Fiecare atelier are pași de ordonat, unelte de ales și calcule pe vârstă. Textele sunt în RO / EN / HU / UK.
(()=>{
const LANGS=['ro','en','hu','uk'],li=()=>{const i=LANGS.indexOf(lang);return i<0?1:i},L=a=>Array.isArray(a)?(a[li()]??a[1]):a;
const fmt=(s,v={})=>String(s).replace(/\{(\w+)\}/g,(_,x)=>v[x]??'');
const U={
title:['Ateliere și meserii','Workshops and jobs','Műhelyek és mesterségek','Майстерні та професії'],
intro:['Alege un atelier și încearcă o meserie. Fiecare are provocări potrivite vârstei tale.','Pick a workshop and try a job. Each one has challenges right for your age.','Válassz egy műhelyt, és próbálj ki egy mesterséget. Mindegyikben korodnak való feladatok várnak.','Обери майстерню й спробуй професію. У кожній є завдання для твого віку.'],
back:['← Toate atelierele','← All workshops','← Összes műhely','← Усі майстерні'],
listen:['🔊 Ascultă','🔊 Listen','🔊 Meghallgatom','🔊 Послухати'],
another:['➡️ Încă una','➡️ Another one','➡️ Még egyet','➡️ Ще одне'],
tabSteps:['🪜 Pașii','🪜 Steps','🪜 Lépések','🪜 Кроки'],tabTools:['🧰 Unelte','🧰 Tools','🧰 Eszközök','🧰 Інструменти'],tabMath:['🔢 Calcule','🔢 Maths','🔢 Számolás','🔢 Обчислення'],
orderHelp:['Pune pașii în ordine: atinge pasul care urmează.','Put the steps in order: tap the step that comes next.','Tedd sorba a lépéseket: érintsd meg a következőt.','Розстав кроки по черзі: торкнися наступного кроку.'],
orderWrong:['Hmm, mai întâi vine altceva. Ce se face înainte?','Hmm, something else comes first. What happens before?','Hmm, előbb valami más jön. Mi történik előtte?','Хм, спершу буде щось інше. Що робимо раніше?'],
orderDone:['Gata! Ai făcut totul în ordinea bună. 🎉','Done! You did everything in the right order. 🎉','Kész! Mindent jó sorrendben csináltál. 🎉','Готово! Ти все зробив(-ла) у правильному порядку. 🎉'],
toolHelp:['Ce alegi ca să rezolvi problema?','What do you choose to solve the problem?','Mit választasz, hogy megoldd a gondot?','Що обереш, щоб розв’язати проблему?'],
toolWrong:['Nu chiar. Gândește-te ce trebuie rezolvat.','Not quite. Think about what needs to be solved.','Nem egészen. Gondold végig, mit kell megoldani.','Не зовсім. Подумай, що треба розв’язати.'],
good:['Corect! 🎉','Correct! 🎉','Helyes! 🎉','Правильно! 🎉'],nearly:['Aproape! Mai încearcă.','Nearly! Try again.','Majdnem! Próbáld újra.','Майже! Спробуй ще.'],
yes:['Da','Yes','Igen','Так'],no:['Nu','No','Nem','Ні'],
safety:['Siguranță','Safety','Biztonság','Безпека']};
const u=(k,v)=>fmt(L(U[k]),v);
const E=(tag,text='',cls='')=>{const e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;return e},B=(text,fn,cls)=>{const b=E('button',text,cls);b.type='button';b.onclick=fn;return b};
const NS='http://www.w3.org/2000/svg',S=(tag,attrs={})=>{const e=document.createElementNS(NS,tag);for(const k in attrs)e.setAttribute(k,attrs[k]);return e};
const uid=()=>localStorage.getItem('garden_active')||'default',key=()=>`garden_crafts_${uid()}`,read=()=>{try{return JSON.parse(localStorage.getItem(key()))||{}}catch{return {}}},save=d=>{try{localStorage.setItem(key(),JSON.stringify(d))}catch{}};
const age=()=>ageOf(profile.dob),rand=n=>Math.floor(Math.random()*n),pick=a=>a[rand(a.length)],mix=a=>shuffle([...a]);

// ——— Conținutul atelierelor. Pașii: [icon, text, icon-rezultat?]; minAge/young aleg varianta pe vârstă.
const TOOLS={
can:['🚿',['Stropitoarea','Watering can','Locsoló','Лійка']],shears:['✂️',['Foarfeca de grădină','Garden shears','Metszőolló','Садові ножиці']],broom:['🧹',['Grebla','Rake','Gereblye','Граблі']],gloves:['🧤',['Mănușile','Gloves','Kesztyű','Рукавиці']],spade:['⛏️',['Cazmaua','Spade','Ásó','Лопата']],
hammer:['🔨',['Ciocanul','Hammer','Kalapács','Молоток']],screwdriver:['🪛',['Șurubelnița','Screwdriver','Csavarhúzó','Викрутка']],saw:['🪚',['Fierăstrăul','Saw','Fűrész','Пилка']],tape:['📏',['Ruleta','Tape measure','Mérőszalag','Рулетка']],helmet:['⛑️',['Casca de protecție','Safety helmet','Védősisak','Захисна каска']],brush:['🖌️',['Pensula','Paintbrush','Ecset','Пензель']],
thermo:['🌡️',['Termometrul','Thermometer','Lázmérő','Термометр']],plaster:['🩹',['Plasturele','Plaster','Sebtapasz','Пластир']],stetho:['🩺',['Stetoscopul','Stethoscope','Sztetoszkóp','Стетоскоп']],ice:['🧊',['Compresa rece','Cold pack','Hideg borogatás','Холодний компрес']],eyes:['👓',['Testul de vedere','Eye test','Látásvizsgálat','Перевірка зору']],dentist:['🦷',['Dentistul','The dentist','Fogorvos','Стоматолог']],tissue:['🧻',['Șervețelele','Tissues','Papír zsebkendő','Серветки']],
charger:['🔌',['Încărcătorul','Charger','Töltő','Зарядка']],screen:['📲',['Ecranul nou','New screen','Új kijelző','Новий екран']],pump:['💨',['Pompa','Pump','Pumpa','Насос']],oil:['🛢️',['Uleiul pentru lanț','Chain oil','Láncolaj','Мастило для ланцюга']],wheel:['🛞',['Roata de rezervă','Spare wheel','Pótkerék','Запасне колесо']],bulb:['💡',['Becul nou','New bulb','Új izzó','Нова лампочка']],fuel:['⛽',['Benzinăria','Petrol station','Benzinkút','Заправка']],sponge:['🧽',['Buretele și lichidul de parbriz','Sponge and screen wash','Szivacs és ablakmosó','Губка й омивач']],
spoon:['🥄',['Lingura / telul','Spoon / whisk','Kanál / habverő','Ложка / вінчик']],knife:['🔪',['Cuțitul (cu un adult)','Knife (with an adult)','Kés (felnőttel)','Ніж (з дорослим)']],cup:['🥛',['Cana gradată','Measuring jug','Mérőpohár','Мірна склянка']],scale:['⚖️',['Cântarul','Kitchen scale','Konyhai mérleg','Кухонні ваги']],mitts:['🧤',['Mănușile de bucătărie (cu un adult)','Oven gloves (with an adult)','Edényfogó kesztyű (felnőttel)','Кухонні рукавиці (з дорослим)']]};
const C={
garden:{icon:'🌱',name:['Grădinărit','Gardening','Kertészkedés','Садівництво'],desc:['Semințe, plante, unelte de grădină','Seeds, plants, garden tools','Magok, növények, kerti eszközök','Насіння, рослини, садові інструменти'],
intro:['Pune semințe, îngrijește plantele și vezi-le crescând.','Plant seeds, look after the plants and watch them grow.','Vess magokat, gondozd a növényeket, és nézd, ahogy nőnek.','Сій насіння, доглядай за рослинами й дивись, як вони ростуть.'],
seqs:[{title:['Plantăm o sămânță','Planting a seed','Magot vetünk','Садимо насінину'],young:[0,1,2,3],steps:[['⛏️',['Sapă o gropiță','Dig a small hole','Áss egy kis gödröt','Викопай ямку'],'🕳️'],['🌰',['Pune sămânța','Put in the seed','Tedd bele a magot','Поклади насінину'],'🌰'],['🟫',['Acoperă cu pământ','Cover it with soil','Takard be földdel','Присип землею'],'🟫'],['💧',['Udă','Water it','Öntözd meg','Полий'],'🌱'],['☀️',['Pune ghiveciul la soare','Put the pot in the sun','Tedd a cserepet napra','Постав горщик на сонце'],'🌻']]},
{title:['Mutăm un răsad în grădină','Moving a seedling to the garden','Palántát ültetünk ki','Пересаджуємо розсаду'],minAge:8,steps:[['⛏️',['Sapă o groapă mai mare decât ghiveciul','Dig a hole bigger than the pot','Áss a cserépnél nagyobb gödröt','Викопай ямку, більшу за горщик'],'🕳️'],['🪴',['Scoate răsadul cu pământ cu tot','Lift the seedling out with its soil','Emeld ki a palántát a földjével együtt','Вийми розсаду разом із землею'],'🪴'],['🌱',['Pune răsadul în groapă','Put the seedling in the hole','Tedd a palántát a gödörbe','Постав розсаду в ямку'],'🌱'],['🟫',['Umple cu pământ și apasă ușor','Fill with soil and press gently','Töltsd fel földdel, és nyomkodd meg','Засип землею й злегка притисни'],'🟫'],['💧',['Udă bine','Water it well','Öntözd meg alaposan','Добре полий'],'🌿']]}],
cases:[['🥀',['Planta e ofilită, iar pământul e uscat.','The plant is drooping and the soil is dry.','A növény lekókadt, a föld száraz.','Рослина зів’яла, а земля суха.'],'can'],['🌿',['Tufa a crescut peste potecă.','The bush has grown over the path.','A bokor ránőtt az ösvényre.','Кущ заріс стежку.'],'shears'],['🍂',['Pe gazon sunt multe frunze căzute.','There are lots of fallen leaves on the lawn.','Sok lehullott levél van a gyepen.','На газоні багато опалого листя.'],'broom'],['🌹',['Vrei să tai un trandafir cu spini.','You want to cut a thorny rose.','Egy tüskés rózsát akarsz levágni.','Хочеш зрізати колючу троянду.'],'gloves'],['🥔',['Vrei să faci un strat nou pentru cartofi.','You want to make a new potato bed.','Új ágyást készítesz a krumplinak.','Хочеш зробити нову грядку для картоплі.'],'spade']],
pool:['can','shears','broom','gloves','spade'],
math:a=>{if(a<=5){const n=3+rand(5);return {text:['Câte flori ai plantat?','How many flowers did you plant?','Hány virágot ültettél?','Скільки квітів ти посадив(-ла)?'],show:'🌷'.repeat(n),answer:n}}if(a<=8){const r=2+rand(3),c=2+rand(4);return {text:[`Ai ${r} rânduri cu câte ${c} răsaduri. Câte răsaduri ai?`,`You have ${r} rows with ${c} seedlings each. How many seedlings?`,`${r} sorod van, mindegyikben ${c} palánta. Hány palánta van?`,`У тебе ${r} рядки по ${c} розсадин. Скільки всього?`],show:Array.from({length:r},()=>'🌱'.repeat(c)).join('\n'),answer:r*c}}const g=2+rand(4),h=5+rand(10),w=2+rand(4);return {text:[`O floarea-soarelui are ${h} cm și crește ${g} cm pe săptămână. Câți cm are după ${w} săptămâni?`,`A sunflower is ${h} cm tall and grows ${g} cm a week. How tall is it after ${w} weeks?`,`Egy napraforgó ${h} cm magas, és hetente ${g} cm-t nő. Milyen magas ${w} hét múlva?`,`Соняшник має ${h} см і росте на ${g} см щотижня. Яким він буде через ${w} тижні?`],answer:h+g*w}}},
build:{icon:'🏗️',name:['Construcții','Building','Építkezés','Будівництво'],desc:['Casa pas cu pas, unelte, materiale','A house step by step, tools, materials','Ház lépésről lépésre, eszközök, anyagok','Будинок крок за кроком, інструменти, матеріали'],
intro:['Construiește o casă, alege uneltele potrivite și calculează materialele.','Build a house, choose the right tools and work out the materials.','Építs házat, válaszd ki a megfelelő eszközöket, és számold ki az anyagokat.','Збудуй будинок, обери правильні інструменти й порахуй матеріали.'],
safe:['Pe un șantier adevărat intri doar cu un adult și cu cască de protecție.','You only go on a real building site with an adult and a safety helmet.','Igazi építkezésre csak felnőttel és védősisakban mehetsz.','На справжнє будівництво можна лише з дорослим і в захисній касці.'],
seqs:[{title:['Construim o casă','Building a house','Házat építünk','Будуємо будинок'],young:[1,2,3,4],visual:'house',steps:[['📐',['Desenează planul casei','Draw the plan of the house','Rajzold meg a ház tervét','Намалюй план будинку'],'plan'],['🚜',['Sapă și toarnă fundația','Dig and pour the foundation','Ásd ki és öntsd ki az alapot','Викопай і залий фундамент'],'found'],['🧱',['Ridică pereții','Build the walls','Húzd fel a falakat','Зведи стіни'],'walls'],['🪟',['Pune ferestrele și ușa','Fit the windows and the door','Tedd be az ablakokat és az ajtót','Встав вікна й двері'],'windows'],['🏠',['Pune acoperișul','Put on the roof','Tedd fel a tetőt','Поклади дах'],'roof'],['🎨',['Vopsește pereții','Paint the walls','Fesd ki a falakat','Пофарбуй стіни'],'paint']]}],
cases:[['🪵',['Trebuie bătut un cui în scândură.','A nail needs hammering into a plank.','Egy szöget kell beverni a deszkába.','Треба забити цвях у дошку.'],'hammer'],['🔩',['Un șurub de la raft s-a slăbit.','A screw on the shelf has come loose.','Kilazult egy csavar a polcon.','Розкрутився гвинт на полиці.'],'screwdriver'],['🪵',['O scândură e prea lungă și trebuie tăiată.','A plank is too long and needs cutting.','Egy deszka túl hosszú, le kell vágni.','Дошка задовга, її треба відпиляти.'],'saw'],['🧱',['Vrei să afli cât de lung e peretele.','You want to know how long the wall is.','Meg akarod tudni, milyen hosszú a fal.','Хочеш дізнатися, яка довжина стіни.'],'tape'],['🏗️',['Macaraua ridică materiale deasupra ta.','A crane is lifting materials above you.','A daru anyagokat emel föléd.','Кран піднімає матеріали над тобою.'],'helmet'],['🏠',['Pereții sunt gata, dar sunt gri și triști.','The walls are finished but grey and dull.','A falak készen vannak, de szürkék.','Стіни готові, але сірі й сумні.'],'brush']],
pool:['hammer','screwdriver','saw','tape','helmet','brush'],
math:a=>{if(a<=5){const r=2,c=2+rand(3);return {text:['Câte cărămizi are zidul?','How many bricks are in the wall?','Hány tégla van a falban?','Скільки цеглин у стіні?'],show:Array.from({length:r},()=>'🧱'.repeat(c)).join('\n'),answer:r*c}}if(a<=8){const r=2+rand(4),c=3+rand(4);return {text:[`Un zid are ${r} rânduri cu câte ${c} cărămizi. Câte cărămizi are?`,`A wall has ${r} rows of ${c} bricks. How many bricks?`,`Egy fal ${r} sorból áll, soronként ${c} téglával. Hány tégla?`,`У стіні ${r} ряди по ${c} цеглин. Скільки цеглин?`],answer:r*c}}if(Math.random()<.5){const l=3+rand(5),w=2+rand(4);return {text:[`O cameră are ${l} m pe ${w} m. Câți metri pătrați de parchet trebuie?`,`A room is ${l} m by ${w} m. How many square metres of flooring are needed?`,`Egy szoba ${l} m × ${w} m. Hány négyzetméter parketta kell?`,`Кімната має ${l} м на ${w} м. Скільки квадратних метрів паркету потрібно?`],answer:l*w}}const l=3+rand(5),w=2+rand(4);return {text:[`O cameră are ${l} m pe ${w} m. Câți metri de plintă trebuie pe tot conturul?`,`A room is ${l} m by ${w} m. How many metres of skirting board go all the way round?`,`Egy szoba ${l} m × ${w} m. Hány méter szegélyléc kell körbe?`,`Кімната має ${l} м на ${w} м. Скільки метрів плінтуса потрібно по всьому периметру?`],answer:2*(l+w)}}},
doctor:{icon:'🩺',name:['Doctor','Doctor','Orvos','Лікар'],desc:['Ursulețul Tedi, instrumente, sănătate','Teddy the bear, instruments, health','Teddy maci, eszközök, egészség','Ведмедик Тедді, інструменти, здоров’я'],
intro:['Ursulețul Tedi nu se simte bine. Ascultă-l, alege instrumentul potrivit și învață ce ne ține sănătoși.','Teddy the bear isn’t feeling well. Listen, choose the right instrument and learn what keeps us healthy.','Teddy maci nem érzi jól magát. Hallgasd meg, válaszd ki a megfelelő eszközt, és tanuld meg, mi tart egészségesen.','Ведмедик Тедді нездужає. Вислухай його, обери потрібний інструмент і дізнайся, що допомагає бути здоровим.'],
safe:['E un joc de-a doctorul. Când cineva e bolnav cu adevărat, spune unui adult. Medicamentele le dă doar un adult sau medicul.','This is pretend play. When someone is really ill, tell an adult. Only an adult or a doctor gives medicine.','Ez szerepjáték. Ha valaki tényleg beteg, szólj egy felnőttnek. Gyógyszert csak felnőtt vagy orvos adhat.','Це гра в лікаря. Якщо хтось справді захворів, скажи дорослому. Ліки дає лише дорослий або лікар.'],
seqs:[{title:['Ne spălăm pe mâini','Washing our hands','Kezet mosunk','Миємо руки'],young:[0,1,2,3],steps:[['💧',['Udă mâinile','Wet your hands','Vizezd be a kezed','Намочи руки']],['🧼',['Pune săpun','Add soap','Tegyél rá szappant','Візьми мило']],['👐',['Freacă 20 de secunde, și printre degete','Rub for 20 seconds, between the fingers too','Dörzsöld 20 másodpercig, az ujjak között is','Три 20 секунд, і між пальцями теж']],['🚿',['Clătește','Rinse','Öblítsd le','Змий']],['🧻',['Șterge-te cu prosopul','Dry with a towel','Töröld meg törölközővel','Витри рушником']]]},
{title:['Ne spălăm pe dinți','Brushing our teeth','Fogat mosunk','Чистимо зуби'],minAge:6,steps:[['🪥',['Pune puțină pastă pe periuță','Put a little toothpaste on the brush','Tegyél kevés fogkrémet a kefére','Нанеси трохи пасти на щітку']],['🦷',['Periază toți dinții 2 minute','Brush all your teeth for 2 minutes','Mosd 2 percig az összes fogad','Чисть усі зуби 2 хвилини']],['💦',['Scuipă pasta și clătește gura','Spit out and rinse your mouth','Köpd ki, és öblítsd ki a szád','Виплюнь пасту й прополощи рот']],['🚰',['Spală periuța','Rinse the toothbrush','Öblítsd el a fogkefét','Помий щітку']]]}],
cases:[['🤒',['„Sunt fierbinte și obosit.”','“I feel hot and tired.”','„Forró vagyok és fáradt.”','«Я гарячий і втомлений.»'],'thermo'],['🦵',['„M-am zgâriat la genunchi. Rana e deja spălată.”','“I scraped my knee. It’s already been washed.”','„Lehorzsoltam a térdem. A sebet már kimostuk.”','«Я подряпав коліно. Ранку вже промили.»'],'plaster'],['💓',['„Doctorul vrea să-mi asculte inima.”','“The doctor wants to listen to my heart.”','„Az orvos meg akarja hallgatni a szívemet.”','«Лікар хоче послухати моє серце.»'],'stetho'],['🤕',['„M-am lovit la mână și s-a umflat puțin.”','“I bumped my arm and it’s a bit swollen.”','„Beütöttem a kezem, és kicsit megdagadt.”','«Я вдарив руку, і вона трохи набрякла.»'],'ice'],['👀',['„Nu văd bine literele de pe tablă.”','“I can’t see the letters on the board well.”','„Nem látom jól a betűket a táblán.”','«Я погано бачу літери на дошці.»'],'eyes'],['😬',['„Mă doare un dinte când mănânc.”','“A tooth hurts when I eat.”','„Fáj egy fogam, amikor eszem.”','«У мене болить зуб, коли я їм.»'],'dentist'],['🤧',['„Strănut întruna!”','“I keep sneezing!”','„Folyton tüsszögök!”','«Я весь час чхаю!»'],'tissue']],
pool:['thermo','plaster','stetho','ice','eyes','dentist','tissue'],
math:a=>{if(a<=5){const q=pick([['👂',['Cu ce auzim?','What do we hear with?','Mivel hallunk?','Чим ми чуємо?']],['👃',['Cu ce mirosim?','What do we smell with?','Mivel szagolunk?','Чим ми нюхаємо?']],['👁️',['Cu ce vedem?','What do we see with?','Mivel látunk?','Чим ми бачимо?']],['👅',['Cu ce simțim gustul?','What do we taste with?','Mivel ízlelünk?','Чим ми відчуваємо смак?']]]);return {text:q[1],answer:q[0],options:['👂','👃','👁️','👅']}}if(a<=8){const fever=Math.random()<.5,t=fever?(38+rand(10)/10).toFixed(1):(36.4+rand(8)/10).toFixed(1),tl=lang==='en'?t:t.replace('.',',');return {text:[`Termometrul arată ${tl} °C. Tedi are febră?`,`The thermometer shows ${tl} °C. Does Teddy have a fever?`,`A lázmérő ${tl} °C-ot mutat. Lázas Teddy?`,`Термометр показує ${tl} °C. У Тедді гарячка?`],answer:fever?u('yes'):u('no'),options:[u('yes'),u('no')],hint:['Peste 38 °C înseamnă febră.','Above 38 °C means a fever.','38 °C felett láz van.','Понад 38 °C — це гарячка.']}}if(Math.random()<.5){const b=15+rand(11);return {text:[`Inima lui Tedi bate de ${b} ori în 15 secunde. De câte ori bate într-un minut?`,`Teddy’s heart beats ${b} times in 15 seconds. How many times in a minute?`,`Teddy szíve 15 másodperc alatt ${b}-at dobban. Hányat egy perc alatt?`,`Серце Тедді б’ється ${b} разів за 15 секунд. Скільки разів за хвилину?`],answer:b*4}}const s=7+rand(3),e=6+rand(3);return {text:[`Tedi se culcă la ${s+12}:00 și se trezește la ${e}:00. Câte ore doarme?`,`Teddy goes to bed at ${s+12}:00 and wakes up at ${e}:00. How many hours does he sleep?`,`Teddy ${s+12}:00-kor fekszik le, és ${e}:00-kor kel. Hány órát alszik?`,`Тедді лягає о ${s+12}:00 і прокидається о ${e}:00. Скільки годин він спить?`],answer:12-s+e}}},
service:{icon:'🔧',name:['Service','Repair shop','Szerviz','Сервіс'],desc:['Telefon, bicicletă, mașină','Phone, bike, car','Telefon, bicikli, autó','Телефон, велосипед, автомобіль'],
intro:['Repară un telefon, o bicicletă sau o mașină: găsește problema și alege piesa ori unealta potrivită.','Fix a phone, a bike or a car: find the problem and choose the right part or tool.','Javíts meg egy telefont, egy biciklit vagy egy autót: találd meg a hibát, és válaszd ki a megfelelő alkatrészt vagy eszközt.','Полагодь телефон, велосипед або автомобіль: знайди несправність і обери потрібну деталь чи інструмент.'],
safe:['În joc poți repara orice. În realitate, bateriile, curentul și mașinile le repară doar adulții sau mecanicii.','In the game you can fix anything. In real life, batteries, electricity and cars are fixed only by adults or mechanics.','A játékban bármit megjavíthatsz. A valóságban akkumulátort, áramot és autót csak felnőtt vagy szerelő javít.','У грі можна полагодити що завгодно. Насправді батареї, електрику й автомобілі ремонтують лише дорослі або механіки.'],
seqs:[{title:['Umflăm roata bicicletei','Pumping up a bike tyre','Felfújjuk a bicikli kerekét','Накачуємо колесо велосипеда'],max:7,steps:[['🔍',['Găsește ventilul roții','Find the tyre valve','Keresd meg a szelepet','Знайди ніпель колеса']],['💨',['Pune pompa pe ventil','Put the pump on the valve','Tedd a pumpát a szelepre','Приєднай насос до ніпеля']],['💪',['Pompează','Pump','Pumpálj','Качай']],['👍',['Apasă roata: e tare?','Squeeze the tyre: is it firm?','Nyomd meg a kereket: kemény?','Натисни на колесо: тверде?']]]},
{title:['Schimbăm roata mașinii (cu un adult)','Changing a car wheel (with an adult)','Autókereket cserélünk (felnőttel)','Міняємо колесо автомобіля (з дорослим)'],minAge:8,steps:[['⚠️',['Pune triunghiul reflectorizant','Put out the warning triangle','Tedd ki az elakadásjelző háromszöget','Постав аварійний трикутник']],['🔧',['Slăbește puțin prezoanele','Loosen the wheel nuts a little','Lazítsd meg kicsit a kerékanyákat','Трохи послаб колісні гайки']],['⬆️',['Ridică mașina cu cricul','Raise the car with the jack','Emeld meg az autót az emelővel','Підніми авто домкратом']],['🛞',['Pune roata de rezervă','Fit the spare wheel','Tedd fel a pótkereket','Постав запасне колесо']],['⬇️',['Coboară mașina','Lower the car','Engedd le az autót','Опусти авто']],['🔩',['Strânge bine prezoanele','Tighten the wheel nuts well','Húzd meg jól a kerékanyákat','Добре затягни гайки']]]},
{title:['Încărcăm telefonul','Charging the phone','Feltöltjük a telefont','Заряджаємо телефон'],minAge:6,max:7,steps:[['🔌',['Conectează cablul la telefon','Plug the cable into the phone','Dugd a kábelt a telefonba','Під’єднай кабель до телефону']],['🔋',['Așteaptă să se încarce','Wait for it to charge','Várd meg, hogy feltöltődjön','Зачекай, поки зарядиться']],['🔓',['Scoate cablul','Unplug the cable','Húzd ki a kábelt','Від’єднай кабель']],['📱',['Pornește telefonul','Switch the phone on','Kapcsold be a telefont','Увімкни телефон']]]}],
cases:[['📱',['Telefonul nu pornește: bateria e goală.','The phone won’t switch on: the battery is flat.','A telefon nem kapcsol be: lemerült.','Телефон не вмикається: батарея розряджена.'],'charger'],['📱',['Ecranul telefonului e crăpat.','The phone screen is cracked.','Megrepedt a telefon kijelzője.','Екран телефону тріснув.'],'screen'],['🚲',['Roata bicicletei e moale.','The bike tyre is soft.','Puha a bicikli kereke.','Колесо велосипеда м’яке.'],'pump'],['🚲',['Lanțul bicicletei scârțâie.','The bike chain squeaks.','Nyikorog a bicikli lánca.','Ланцюг велосипеда скрипить.'],'oil'],['🚗',['Mașina are o roată spartă.','The car has a flat tyre.','Defektes az autó egyik kereke.','В автомобіля пробите колесо.'],'wheel'],['🚗',['Farul mașinii nu mai luminează.','The car headlight doesn’t work.','Nem világít az autó fényszórója.','Фара автомобіля не світить.'],'bulb'],['🚗',['Mașina a rămas fără benzină.','The car has run out of petrol.','Kifogyott az autóból a benzin.','В автомобіля закінчився бензин.'],'fuel'],['🚗',['Parbrizul e plin de noroi.','The windscreen is covered in mud.','Sáros a szélvédő.','Лобове скло в болоті.'],'sponge']],
pool:['charger','screen','pump','oil','wheel','bulb','fuel','sponge'],
math:a=>{if(a<=5){const n=1+rand(3);return {text:[`Câte roți au ${n} biciclete?`,`How many wheels do ${n} bikes have?`,`Hány kereke van ${n} biciklinek?`,`Скільки коліс у ${n} велосипедів?`],show:'🚲'.repeat(n),answer:n*2}}if(a<=8){const n=2+rand(4);return {text:[`În service sunt ${n} mașini, fiecare cu 4 roți. Câte roți sunt?`,`There are ${n} cars in the workshop, each with 4 wheels. How many wheels?`,`A szervizben ${n} autó van, mindegyiknek 4 kereke. Hány kerék van?`,`У сервісі ${n} автомобілі, у кожного 4 колеса. Скільки коліс?`],show:'🚗'.repeat(n),answer:n*4}}const p=10*(1+rand(4)),r=5*(1+rand(3)),m=10*(2+rand(4));return {text:[`Telefonul are ${p}% și se încarcă ${r}% la fiecare 10 minute. Câte procente are după ${m} de minute?`,`The phone is at ${p}% and charges ${r}% every 10 minutes. What percentage after ${m} minutes?`,`A telefon ${p}%-on áll, és 10 percenként ${r}%-ot töltődik. Hány százalékon lesz ${m} perc múlva?`,`Телефон має ${p}% і заряджається на ${r}% кожні 10 хвилин. Скільки відсотків буде через ${m} хвилин?`],answer:Math.min(100,p+r*m/10)}}},
cooking:{icon:'🍳',name:['Gătit','Cooking','Főzés','Кулінарія'],desc:['Rețete, ustensile, măsurători','Recipes, utensils, measuring','Receptek, eszközök, mérés','Рецепти, начиння, вимірювання'],
intro:['Urmează rețeta, măsoară ingredientele și gătește ceva bun.','Follow the recipe, measure the ingredients and cook something tasty.','Kövesd a receptet, mérd ki a hozzávalókat, és főzz valami finomat.','Дотримуйся рецепта, відміряй інгредієнти та приготуй щось смачне.'],
safe:['Cuțitul, aragazul și cuptorul se folosesc doar împreună cu un adult. Spală-te pe mâini înainte!','Knives, the hob and the oven are used only with an adult. Wash your hands first!','Kést, tűzhelyet és sütőt csak felnőttel együtt használj. Előtte moss kezet!','Ніж, плиту й духовку використовуй лише разом із дорослим. Спершу помий руки!'],
seqs:[{title:['Salată de fructe','Fruit salad','Gyümölcssaláta','Фруктовий салат'],young:[0,1,3,4],steps:[['🧼',['Spală-te pe mâini','Wash your hands','Moss kezet','Помий руки']],['🍓',['Spală fructele','Wash the fruit','Mosd meg a gyümölcsöt','Помий фрукти']],['🔪',['Taie fructele (cu un adult)','Cut the fruit (with an adult)','Vágd fel a gyümölcsöt (felnőttel)','Наріж фрукти (з дорослим)']],['🥣',['Pune-le în bol','Put them in a bowl','Tedd őket egy tálba','Поклади їх у миску']],['🥄',['Amestecă ușor','Stir gently','Keverd össze óvatosan','Обережно перемішай']]]},
{title:['Sandviș','Sandwich','Szendvics','Сендвіч'],minAge:5,steps:[['🧼',['Spală-te pe mâini','Wash your hands','Moss kezet','Помий руки']],['🍞',['Ia două felii de pâine','Take two slices of bread','Vegyél két szelet kenyeret','Візьми два скибки хліба']],['🧈',['Unge o felie cu unt','Butter one slice','Kenj meg egy szeletet vajjal','Намасти скибку маслом']],['🧀',['Pune brânza și roșia','Add cheese and tomato','Tegyél rá sajtot és paradicsomot','Поклади сир і помідор']],['🥪',['Acoperă cu a doua felie','Cover with the second slice','Fedd be a második szelettel','Накрий другою скибкою']]]},
{title:['Clătite','Pancakes','Palacsinta','Млинці'],minAge:9,steps:[['🥚',['Sparge ouăle în bol','Crack the eggs into a bowl','Üsd a tojásokat egy tálba','Розбий яйця в миску']],['🥛',['Adaugă laptele','Add the milk','Add hozzá a tejet','Додай молоко']],['🌾',['Adaugă făina puțin câte puțin','Add the flour a little at a time','Add hozzá a lisztet apránként','Додавай борошно потроху']],['🥄',['Amestecă până nu mai are cocoloașe','Whisk until smooth','Keverd csomómentesre','Збивай, доки не зникнуть грудочки']],['🍳',['Coace pe tigaie (cu un adult)','Cook in the pan (with an adult)','Süsd ki serpenyőben (felnőttel)','Смаж на пательні (з дорослим)']],['🍯',['Pune dulceață și rulează','Spread jam and roll up','Kend meg lekvárral, és tekerd fel','Намасти варенням і згорни']]]}],
cases:[['🥣',['Trebuie să amesteci aluatul.','You need to mix the batter.','Össze kell keverni a tésztát.','Треба перемішати тісто.'],'spoon'],['🍞',['Trebuie tăiată pâinea.','The bread needs slicing.','Fel kell szeletelni a kenyeret.','Треба нарізати хліб.'],'knife'],['🥛',['Rețeta cere 250 ml de lapte.','The recipe needs 250 ml of milk.','A recept 250 ml tejet kér.','У рецепті 250 мл молока.'],'cup'],['🌾',['Rețeta cere 200 g de făină.','The recipe needs 200 g of flour.','A recept 200 g lisztet kér.','У рецепті 200 г борошна.'],'scale'],['🔥',['Tava fierbinte trebuie scoasă din cuptor.','The hot tray has to come out of the oven.','A forró tepsit ki kell venni a sütőből.','Гарячу деко треба вийняти з духовки.'],'mitts']],
pool:['spoon','knife','cup','scale','mitts'],
math:a=>{if(a<=5){const n=2+rand(5);return {text:[`Rețeta cere ${n} căpșuni. Câte sunt aici?`,`The recipe needs ${n} strawberries. How many are here?`,`A recept ${n} epret kér. Hány van itt?`,`У рецепті ${n} полуниць. Скільки їх тут?`],show:'🍓'.repeat(n),answer:n}}if(a<=8){const x=2+rand(3),k=2+rand(4);return {text:[`Pentru o clătită trebuie ${x} linguri de făină. Câte linguri pentru ${k} clătite?`,`One pancake needs ${x} spoons of flour. How many spoons for ${k} pancakes?`,`Egy palacsintához ${x} kanál liszt kell. Hány kanál kell ${k} palacsintához?`,`Для одного млинця треба ${x} ложки борошна. Скільки ложок на ${k} млинці?`],answer:x*k}}const base=pick([2,4]),to=base===2?pick([4,6]):pick([2,8]),g=pick([100,150,200,250]);return {text:[`Rețeta e pentru ${base} persoane și cere ${g} g de făină. Câte grame trebuie pentru ${to} persoane?`,`The recipe serves ${base} and needs ${g} g of flour. How many grams for ${to} people?`,`A recept ${base} főre szól, és ${g} g lisztet kér. Hány gramm kell ${to} főre?`,`Рецепт на ${base} особи, потрібно ${g} г борошна. Скільки грамів треба на ${to} осіб?`],answer:g*to/base}}}};
// ——— Ferma, cules fructe și animale
Object.assign(TOOLS,{tractor:['🚜',['Tractorul cu plugul','Tractor and plough','Traktor ekével','Трактор із плугом']],combine:['🌾',['Combina','Combine harvester','Kombájn','Комбайн']],pail:['🪣',['Găleata de muls','Milking pail','Fejővödör','Дійниця']],basket:['🧺',['Coșul','Basket','Kosár','Кошик']],clipper:['✂️',['Foarfeca de tuns oi','Sheep shears','Juhnyíró olló','Ножиці для стрижки овець']],trailer:['🛻',['Remorca','Trailer','Pótkocsi','Причіп']]});
C.farm={icon:'🚜',name:['Ferma','Farm','Farm','Ферма'],desc:['De la grâu la pâine, lapte, ouă, utilaje','Wheat to bread, milk, eggs, machines','Búzától kenyérig, tej, tojás, gépek','Від зерна до хліба, молоко, яйця, техніка'],
intro:['Lucrează la fermă: de la câmp la pâine, de la vacă la brânză și de la găină la ouă.','Work on the farm: from field to bread, from cow to cheese and from hen to eggs.','Dolgozz a farmon: a földtől a kenyérig, a tehéntől a sajtig, a tyúktól a tojásig.','Працюй на фермі: від поля до хліба, від корови до сиру й від курки до яєць.'],
safe:['Utilajele agricole și animalele mari sunt periculoase: stai departe de ele și mergi la fermă doar cu un adult.','Farm machines and big animals are dangerous: keep away from them and only visit a farm with an adult.','A mezőgazdasági gépek és a nagy állatok veszélyesek: maradj távol tőlük, és csak felnőttel menj a farmra.','Сільгосптехніка й великі тварини небезпечні: тримайся подалі й ходи на ферму лише з дорослим.'],
seqs:[{title:['De la grâu la pâine','From wheat to bread','A búzától a kenyérig','Від зерна до хліба'],young:[1,3,4,6],steps:[['🚜',['Tractorul ară câmpul','The tractor ploughs the field','A traktor felszántja a földet','Трактор оре поле'],'🟫'],['🌱',['Fermierul seamănă grâul','The farmer sows the wheat','A gazda elveti a búzát','Фермер сіє пшеницю'],'🌱'],['🌧️',['Ploaia udă câmpul','The rain waters the field','Az eső megöntözi a földet','Дощ поливає поле'],'🌧️'],['☀️',['Grâul crește și se coace','The wheat grows and ripens','A búza megnő és beérik','Пшениця росте й достигає'],'🌾'],['🌾',['Combina strânge grâul','The combine harvests the wheat','A kombájn learatja a búzát','Комбайн збирає пшеницю'],'🌾'],['🏭',['Moara face făină','The mill grinds flour','A malom lisztet őröl','Млин меле борошно'],'🏭'],['🍞',['Brutarul coace pâinea','The baker bakes the bread','A pék megsüti a kenyeret','Пекар пече хліб'],'🍞']]},
{title:['De la vacă la brânză','From cow to cheese','A tehéntől a sajtig','Від корови до сиру'],minAge:6,steps:[['🐄',['Vaca paște iarbă proaspătă','The cow grazes on fresh grass','A tehén friss füvet legel','Корова пасеться на свіжій траві']],['🪣',['Fermierul mulge vaca','The farmer milks the cow','A gazda megfeji a tehenet','Фермер доїть корову']],['❄️',['Laptele se răcește','The milk is cooled','A tejet lehűtik','Молоко охолоджують']],['🚚',['Camionul duce laptele la fabrică','The lorry takes the milk to the dairy','A teherautó a tejüzembe viszi a tejet','Вантажівка везе молоко на завод']],['🧀',['Din lapte se face brânză','Cheese is made from the milk','A tejből sajt készül','З молока роблять сир']]]},
{title:['Ouăle de la găini','Eggs from the hens','Tojás a tyúkoktól','Яйця від курей'],steps:[['🌽',['Dă grăunțe găinilor','Feed the hens some grain','Adj magot a tyúkoknak','Дай курям зерна']],['🐔',['Găina se așază în cuibar','The hen sits in the nest','A tyúk a fészekbe ül','Курка сідає в гніздо']],['🥚',['Găina face un ou','The hen lays an egg','A tyúk tojik egy tojást','Курка несе яйце']],['🧺',['Adună ouăle în coș','Collect the eggs in a basket','Szedd össze a tojásokat egy kosárba','Збери яйця в кошик']]]}],
cases:[['🟫',['Câmpul trebuie arat înainte de semănat.','The field needs ploughing before sowing.','A földet vetés előtt fel kell szántani.','Поле треба зорати перед сівбою.'],'tractor'],['🌾',['Grâul s-a copt și trebuie strâns.','The wheat is ripe and must be harvested.','Beérett a búza, le kell aratni.','Пшениця достигла, її треба зібрати.'],'combine'],['🐄',['E dimineață și vaca trebuie mulsă.','It’s morning and the cow needs milking.','Reggel van, meg kell fejni a tehenet.','Ранок, корову треба подоїти.'],'pail'],['🥚',['Găinile au ouat în cuibar.','The hens have laid eggs in the nest.','A tyúkok tojtak a fészekbe.','Кури знесли яйця в гнізді.'],'basket'],['🐑',['Oile au prea multă lână pentru vară.','The sheep have too much wool for the summer.','A juhoknak túl sok a gyapjúja nyárra.','У овець забагато вовни на літо.'],'clipper'],['🌽',['Porumbul cules trebuie dus la hambar.','The picked corn has to go to the barn.','A leszedett kukoricát a csűrbe kell vinni.','Зібрану кукурудзу треба відвезти в комору.'],'trailer'],['🪵',['O scândură din gard s-a desprins și oile pot fugi.','A fence board came loose and the sheep could get out.','Leesett egy léc a kerítésről, és a juhok kiszökhetnek.','Від паркану відірвалася дошка, і вівці можуть утекти.'],'hammer']],
pool:['tractor','combine','pail','basket','clipper','trailer','hammer'],
math:a=>{if(a<=5){const n=3+rand(6);return {text:['Câte ouă ai adunat?','How many eggs did you collect?','Hány tojást szedtél össze?','Скільки яєць ти зібрав(-ла)?'],show:'🥚'.repeat(n),answer:n}}if(a<=8){const k=2+rand(3),t=6*k;return {text:[`Ai ${t} ouă. Într-un cofraj încap 6. Câte cofraje umpli?`,`You have ${t} eggs. A box holds 6. How many boxes do you fill?`,`${t} tojásod van. Egy dobozba 6 fér. Hány dobozt töltesz meg?`,`У тебе ${t} яєць. У лоток уміщається 6. Скільки лотків заповниш?`],show:Array.from({length:k},()=>'🥚'.repeat(6)).join('\n'),answer:k}}if(Math.random()<.5){const x=2+rand(5);return {text:[`Din 10 kg de grâu se obțin 8 kg de făină. Câte kg de făină se obțin din ${10*x} kg de grâu?`,`10 kg of wheat make 8 kg of flour. How many kg of flour do ${10*x} kg of wheat make?`,`10 kg búzából 8 kg liszt lesz. Hány kg liszt lesz ${10*x} kg búzából?`,`З 10 кг пшениці виходить 8 кг борошна. Скільки кг борошна вийде з ${10*x} кг пшениці?`],answer:8*x}}const r=6+rand(7),n=3+rand(6);return {text:[`Un rând are ${r} plante de porumb. Câte plante sunt în ${n} rânduri?`,`A row has ${r} corn plants. How many plants are in ${n} rows?`,`Egy sorban ${r} kukoricatő van. Hány tő van ${n} sorban?`,`У ряду ${r} рослин кукурудзи. Скільки рослин у ${n} рядах?`],answer:r*n}}};
const SEASONS={help:['În ce anotimp?','In which season?','Melyik évszakban?','У яку пору року?'],game:'picking',
cases:[['🍒',['Când culegem cireșele?','When do we pick cherries?','Mikor szedjük a cseresznyét?','Коли збираємо черешні?'],'summer'],['🍑',['Când culegem piersicile?','When do we pick peaches?','Mikor szedjük a barackot?','Коли збираємо персики?'],'summer'],['🍇',['Când culegem strugurii?','When do we pick grapes?','Mikor szüreteljük a szőlőt?','Коли збираємо виноград?'],'autumn'],['🍎',['Când culegem merele de iarnă?','When do we pick winter apples?','Mikor szedjük a téli almát?','Коли збираємо зимові яблука?'],'autumn'],['🌸',['Când înfloresc pomii fructiferi?','When do fruit trees blossom?','Mikor virágoznak a gyümölcsfák?','Коли цвітуть фруктові дерева?'],'spring'],['🌳',['Când se odihnesc pomii, fără frunze și fără fructe?','When do the trees rest, with no leaves or fruit?','Mikor pihennek a fák, levél és gyümölcs nélkül?','Коли дерева відпочивають без листя й плодів?'],'winter'],['🎃',['Când culegem dovlecii?','When do we harvest pumpkins?','Mikor szüreteljük a tököt?','Коли збираємо гарбузи?'],'autumn']],
pool:['spring','summer','autumn','winter'],dict:{spring:['🌸',['Primăvara','Spring','Tavasszal','Навесні']],summer:['☀️',['Vara','Summer','Nyáron','Улітку']],autumn:['🍂',['Toamna','Autumn','Ősszel','Восени']],winter:['❄️',['Iarna','Winter','Télen','Узимку']]}};
const PK={pickTab:['🧺 Culege','🧺 Pick','🧺 Szedd','🧺 Збирай'],seasonTab:['📅 Anotimpuri','📅 Seasons','📅 Évszakok','📅 Пори року'],
young:['Culege toate merele roșii, coapte. Pe cele verzi lasă-le să mai crească.','Pick all the red, ripe apples. Leave the green ones to grow a little more.','Szedd le az összes piros, érett almát. A zöldeket hagyd még nőni.','Збери всі червоні стиглі яблука. Зелені нехай ще підростуть.'],
unripe:['Acesta e încă verde. Mai lasă-l să crească! 🌱','This one is still green. Let it grow a bit longer! 🌱','Ez még zöld. Hagyd még nőni! 🌱','Це ще зелене. Нехай підросте! 🌱'],
mid:['Culege exact {n} × {icon} ({name}).','Pick exactly {n} × {icon} ({name}).','Szedj pontosan {n} × {icon} ({name}).','Збери рівно {n} × {icon} ({name}).'],
wrongFruit:['Nu e fructul cerut. Caută {icon}.','That’s not the fruit we need. Look for {icon}.','Nem ez a kért gyümölcs. Keresd ezt: {icon}.','Це не той фрукт. Шукай {icon}.'],enough:['Ai deja destule în coș!','You already have enough in the basket!','Már elég van a kosárban!','У кошику вже досить!'],
old:['Umple coșul cu fructe care cântăresc exact {w} g. Atinge un fruct din coș ca să-l pui înapoi.','Fill the basket with fruit weighing exactly {w} g. Tap a fruit in the basket to put it back.','Tölts a kosárba pontosan {w} g gyümölcsöt. Ha megérintesz egy gyümölcsöt a kosárban, visszakerül.','Наповни кошик фруктами вагою рівно {w} г. Торкнися фрукта в кошику, щоб повернути його.'],
over:['Prea greu! Scoate ceva din coș.','Too heavy! Take something out of the basket.','Túl nehéz! Vegyél ki valamit a kosárból.','Заважко! Вийми щось із кошика.'],count:['În coș: {n}','In the basket: {n}','A kosárban: {n}','У кошику: {n}'],weight:['În coș: {w} g din {t} g','In the basket: {w} g of {t} g','A kosárban: {w} g / {t} g','У кошику: {w} г з {t} г'],
full:['Coșul e plin! Bravo! 🧺','The basket is full! Well done! 🧺','Tele a kosár! Ügyes! 🧺','Кошик повний! Молодець! 🧺'],tree:['Pomul cu fructe','Fruit tree','Gyümölcsfa','Фруктове дерево'],basket:['Coșul','Basket','Kosár','Кошик'],back:['Pune înapoi: {f}','Put back: {f}','Vissza: {f}','Повернути: {f}']};
const FRUIT={apple:['🍎',150,['măr','apple','alma','яблуко']],green:['🍏',150,['măr necopt','unripe apple','éretlen alma','незріле яблуко']],pear:['🍐',200,['pară','pear','körte','груша']],peach:['🍑',100,['piersică','peach','barack','персик']],cherry:['🍒',50,['cireșe','cherries','cseresznye','черешні']],grapes:['🍇',250,['strugure','grapes','szőlő','виноград']]};
C.picking={icon:'🍎',name:['Cules fructe','Fruit picking','Gyümölcsszedés','Збір фруктів'],desc:['Livada, coșul, anotimpurile','Orchard, basket, seasons','Gyümölcsös, kosár, évszakok','Сад, кошик, пори року'],
intro:['Culege fructe coapte din livadă și pune-le în coș.','Pick ripe fruit in the orchard and put it in the basket.','Szedj érett gyümölcsöt a gyümölcsösben, és tedd a kosárba.','Збирай стиглі фрукти в саду й клади їх у кошик.'],
acts:[['pick',PK.pickTab,'pick'],['season',PK.seasonTab,'match',SEASONS]]};
function pickGame(){const a=age(),kind=a<=5?'ripe':a<=8?'count':'weight';let tree=[],bag=[],done=false,target=0,want=null;
if(kind==='ripe'){const r=4+rand(4),g=3+rand(3);tree=mix([...Array(r).fill('apple'),...Array(g).fill('green')]);target=r}
else if(kind==='count'){want=pick(['apple','pear','peach','cherry']);target=3+rand(4);const others=['apple','pear','peach','cherry','grapes'].filter(f=>f!==want);tree=mix([...Array(target+2+rand(2)).fill(want),...Array.from({length:5+rand(3)},()=>pick(others))])}
else{tree=mix(Array.from({length:11},()=>pick(['apple','pear','peach','cherry','grapes'])));const sub=mix([...tree.keys()]).slice(0,3+rand(3));target=sub.reduce((s,i)=>s+FRUIT[tree[i]][1],0)}
stage.dataset.mode=kind;stage.dataset.target=target;if(want)stage.dataset.want=want;
help(kind==='ripe'?L(PK.young):kind==='count'?fmt(L(PK.mid),{n:target,icon:FRUIT[want][0],name:L(FRUIT[want][2])}):fmt(L(PK.old),{w:target}));
const orchard=E('div','','orchard');orchard.setAttribute('role','group');orchard.setAttribute('aria-label',L(PK.tree));const basketBox=E('div','','fruit-basket');basketBox.setAttribute('role','group');basketBox.setAttribute('aria-label',L(PK.basket));const info=E('p','','versus-pairs');
const sum=()=>bag.reduce((s,i)=>s+FRUIT[tree[i]][1],0);
const btns=tree.map((f,i)=>{const [ic,w,nm]=FRUIT[f];const b=B('',()=>take(i),'fruit');b.dataset.fruit=f;b.dataset.i=i;if(kind==='weight'){b.dataset.w=w;b.append(E('span',ic),E('small',`${w} g`))}else b.append(E('span',ic));b.setAttribute('aria-label',kind==='weight'?`${L(nm)}, ${w} g`:L(nm));orchard.append(b);return b});
const paint=()=>{info.textContent=kind==='weight'?fmt(L(PK.weight),{w:sum(),t:target}):fmt(L(PK.count),{n:bag.length});basketBox.replaceChildren(...bag.map(i=>{const [ic,w,nm]=FRUIT[tree[i]],b=B(ic,()=>back(i),'fruit in-basket');b.setAttribute('aria-label',fmt(L(PK.back),{f:L(nm)}));b.disabled=done||kind!=='weight';return b}));btns.forEach((b,i)=>{b.hidden=bag.includes(i);b.disabled=done})};
function finish(){done=true;paint();gardenCelebrate('craft-picking');say(L(PK.full));stage.append(nextBtn(render))}
function take(i){if(done||bag.includes(i))return;const f=tree[i];
if(kind==='ripe'&&f==='green'){gardenMiss('craft-picking');say(L(PK.unripe),false);return}
if(kind==='count'){if(f!==want){gardenMiss('craft-picking');say(fmt(L(PK.wrongFruit),{icon:FRUIT[want][0]}),false);return}if(bag.length>=target){say(L(PK.enough),false);return}}
bag.push(i);window.gardenSound?.('pop');status.textContent='';paint();
if(kind==='weight'){const s=sum();if(s>target){gardenMiss('craft-picking');say(L(PK.over),false)}else if(s===target)finish()}else if(bag.length===target)finish()}
function back(i){if(done)return;bag=bag.filter(x=>x!==i);status.textContent='';paint()}
stage.append(orchard,info,basketBox);paint()}
const ANIM_FOOD={help:['Ce îi dai să mănânce?','What do you give it to eat?','Mit adsz neki enni?','Чим його нагодуєш?'],
cases:[['🐄',['Vaca e flămândă.','The cow is hungry.','A tehén éhes.','Корова голодна.'],'hay'],['🐔',['Găinile așteaptă mâncare.','The hens are waiting for food.','A tyúkok ennivalóra várnak.','Кури чекають на їжу.'],'corn'],['🐇',['Iepurașul vrea o gustare.','The bunny wants a snack.','A nyuszi nassolna valamit.','Кролик хоче перекусити.'],['carrot','hay']],['🐈',['Pisica miaună lângă castron.','The cat is meowing by its bowl.','A cica nyávog a tálja mellett.','Кішка нявкає біля миски.'],'fish'],['🐕',['Cățelul vrea ceva de ros.','The puppy wants something to chew.','A kutyus rágni szeretne valamit.','Цуценя хоче щось погризти.'],'bone'],['🐝',['Albina caută hrană.','The bee is looking for food.','A méhecske élelmet keres.','Бджілка шукає їжу.'],'flower'],['🐿️',['Veverița face provizii pentru iarnă.','The squirrel is storing food for winter.','A mókus télire gyűjt.','Білка робить запаси на зиму.'],'nut'],['🐴',['Calul a muncit și e flămând.','The horse has worked hard and is hungry.','A ló dolgozott, és megéhezett.','Кінь попрацював і зголоднів.'],['hay','apple','carrot']]],
pool:['hay','corn','carrot','fish','bone','flower','nut','apple'],dict:{hay:['🌾',['Fân','Hay','Széna','Сіно']],corn:['🌽',['Grăunțe de porumb','Corn','Kukoricaszemek','Зерно кукурудзи']],carrot:['🥕',['Morcov','Carrot','Répa','Морква']],fish:['🐟',['Pește','Fish','Hal','Риба']],bone:['🦴',['Os de ros','Chew bone','Rágócsont','Кісточка']],flower:['🌸',['Nectar din flori','Flower nectar','Virágnektár','Нектар квітів']],nut:['🌰',['Nuci și ghinde','Nuts and acorns','Dió és makk','Горіхи й жолуді']],apple:['🍎',['Măr','Apple','Alma','Яблуко']]}};
const ANIM_BABY={help:['Cum se numește puiul?','What is the baby called?','Hogy hívják a kicsinyét?','Як звуть маля?'],
cases:[['🐄',['Vaca și puiul ei:','The cow and her baby:','A tehén és a kicsinye:','Корова і її маля:'],'calf'],['🐑',['Oaia și puiul ei:','The sheep and her baby:','A juh és a kicsinye:','Вівця і її маля:'],'lamb'],['🐔',['Găina și puiul ei:','The hen and her baby:','A tyúk és a kicsinye:','Курка і її маля:'],'chick'],['🐴',['Iapa și puiul ei:','The mare and her baby:','A kanca és a kicsinye:','Кобила і її маля:'],'foal'],['🐕',['Cățeaua și puiul ei:','The dog and her baby:','A kutya és a kicsinye:','Собака і її маля:'],'puppy'],['🐈',['Pisica și puiul ei:','The cat and her baby:','A macska és a kicsinye:','Кішка і її маля:'],'kitten'],['🐖',['Scroafa și puiul ei:','The sow and her baby:','A koca és a kicsinye:','Свиня і її маля:'],'piglet'],['🐐',['Capra și puiul ei:','The goat and her baby:','A kecske és a kicsinye:','Коза і її маля:'],'kid']],
pool:['calf','lamb','chick','foal','puppy','kitten','piglet','kid'],dict:{calf:['',['vițel','calf','borjú','теля']],lamb:['',['miel','lamb','bárány','ягня']],chick:['',['puișor','chick','csibe','курча']],foal:['',['mânz','foal','csikó','лоша']],puppy:['',['cățeluș','puppy','kiskutya','цуценя']],kitten:['',['pisoi','kitten','kiscica','кошеня']],piglet:['',['purcel','piglet','malac','порося']],kid:['',['ied','kid','gida','козеня']]}};
const ANIM_SOUND={help:['Ce sunet face?','What sound does it make?','Milyen hangot ad?','Який звук видає?'],speak:true,
cases:[['🐄',['Vaca','The cow','A tehén','Корова'],'moo'],['🐑',['Oaia','The sheep','A juh','Вівця'],'baa'],['🐔',['Găina','The hen','A tyúk','Курка'],'cluck'],['🐕',['Câinele','The dog','A kutya','Собака'],'woof'],['🐈',['Pisica','The cat','A macska','Кішка'],'meow'],['🦆',['Rața','The duck','A kacsa','Качка'],'quack'],['🐖',['Porcul','The pig','A disznó','Свиня'],'oink'],['🐴',['Calul','The horse','A ló','Кінь'],'neigh']],
pool:['moo','baa','cluck','woof','meow','quack','oink','neigh'],dict:{moo:['',['Muuu!','Moo!','Búú!','Му-у!']],baa:['',['Beee!','Baa!','Bee!','Ме-е!']],cluck:['',['Cot-cot-codac!','Cluck-cluck!','Kot-kot-kodács!','Ко-ко-ко!']],woof:['',['Ham-ham!','Woof!','Vau-vau!','Гав-гав!']],meow:['',['Miau!','Meow!','Miaú!','Няв!']],quack:['',['Mac-mac!','Quack!','Háp-háp!','Кря-кря!']],oink:['',['Groh-groh!','Oink!','Röf-röf!','Рох-рох!']],neigh:['',['Ihahaha!','Neigh!','Nyihaha!','Іго-го!']]}};
C.animals={icon:'🐾',name:['Animale','Animals','Állatok','Тварини'],desc:['Hrană, pui, sunete, îngrijire','Food, babies, sounds, care','Eleség, kicsinyek, hangok, gondozás','Їжа, малята, звуки, догляд'],
intro:['Hrănește animalele, află cum se numesc puii lor și ce sunete fac.','Feed the animals, learn what their babies are called and the sounds they make.','Etesd meg az állatokat, tudd meg, hogy hívják a kicsinyeiket, és milyen hangot adnak.','Нагодуй тварин, дізнайся, як звуть їхніх малят і які звуки вони видають.'],
safe:['Animalele adevărate le atingi doar cu voia stăpânului și cu un adult alături. După joacă, spală-te pe mâini.','Only touch real animals with the owner’s permission and an adult nearby. Wash your hands afterwards.','Igazi állatot csak a gazdája engedélyével és felnőtt jelenlétében simogass. Utána moss kezet.','Справжніх тварин можна гладити лише з дозволу господаря й поруч із дорослим. Потім помий руки.'],
acts:[['food',['🥕 Hrană','🥕 Food','🥕 Eleség','🥕 Їжа'],'match',ANIM_FOOD],['baby',['🐣 Puii','🐣 Babies','🐣 Kicsinyek','🐣 Малята'],'match',ANIM_BABY],['sound',['🔊 Sunete','🔊 Sounds','🔊 Hangok','🔊 Звуки'],'match',ANIM_SOUND],['math',U.tabMath,'math']],
math:a=>{if(a<=5){const n=2+rand(6);return {text:['Câte oițe sunt pe pajiște?','How many sheep are in the meadow?','Hány bárány van a réten?','Скільки овечок на лузі?'],show:'🐑'.repeat(n),answer:n}}if(a<=8){const h=1+rand(4),c=1+rand(3);return {text:[`În curte sunt ${h} găini și ${c} vaci. Câte picioare au împreună?`,`There are ${h} hens and ${c} cows in the yard. How many legs altogether?`,`Az udvaron ${h} tyúk és ${c} tehén van. Hány lábuk van összesen?`,`У дворі ${h} кури й ${c} корови. Скільки в них разом ніг?`],show:'🐔'.repeat(h)+'\n'+'🐄'.repeat(c),answer:h*2+c*4}}if(Math.random()<.5){const n=3+rand(6),d=pick([5,7,10]);return {text:[`O găină face cam un ou pe zi. Câte ouă fac ${n} găini în ${d} zile?`,`A hen lays about one egg a day. How many eggs do ${n} hens lay in ${d} days?`,`Egy tyúk naponta körülbelül egy tojást tojik. Hány tojást tojik ${n} tyúk ${d} nap alatt?`,`Курка несе приблизно одне яйце на день. Скільки яєць знесуть ${n} курей за ${d} днів?`],answer:n*d}}const k=pick([8,10,12]),n=2+rand(3);return {text:[`O vacă mănâncă ${k} kg de fân pe zi. Câte kg mănâncă ${n} vaci într-o săptămână?`,`A cow eats ${k} kg of hay a day. How many kg do ${n} cows eat in a week?`,`Egy tehén naponta ${k} kg szénát eszik. Hány kg-ot eszik ${n} tehén egy hét alatt?`,`Корова з’їдає ${k} кг сіна на день. Скільки кг з’їдять ${n} корови за тиждень?`],answer:k*n*7}}};
const HUB=[['drawing','🎨',['Desen','Drawing','Rajz','Малювання'],['Desen liber, colorează, puncte, pixel art','Free drawing, colouring, dots, pixel art','Szabad rajz, színező, pontok, pixelkép','Малювання, розмальовки, крапки, піксель-арт']],['music','🎵',['Muzică','Music','Zene','Музика'],['Xilofon, cântece, ritmuri','Xylophone, songs, rhythms','Xilofon, dalok, ritmusok','Ксилофон, пісні, ритми']],
['pottery','🏺',['Olărit','Pottery','Fazekasság','Гончарство'],['Vase pe roata olarului, glazuri, comenzi','Pots on the wheel, glazes, orders','Edények a korongon, mázak, rendelések','Посуд на крузі, глазур, замовлення']],['crochet','🧶',['Croșetat','Crochet','Horgolás','В’язання гачком'],['Fulare cu modele de culori','Scarves with colour patterns','Sálak színmintákkal','Шарфи з кольоровими візерунками']],
...['garden','farm','picking','animals','build','doctor','service','cooking'].map(k=>[k,C[k].icon,C[k].name,C[k].desc])];
const nameOf=k=>L(HUB.find(h=>h[0]===k)[2]);

// ——— Ecranul
const section=E('section','','card studio crafts');section.id='studio';section.dataset.view='studio';$('app').insertBefore(section,$('birthday'));
let craft=null,act=null,stage,status,token=0;const rot={};
const say=(msg,good=true)=>{status.textContent=msg;status.classList.toggle('bad',!good)};
const listen=text=>B(u('listen'),()=>gardenSpeak(text,true),'speak-btn');
const help=text=>{stage.append(E('p',text,'studio-help'));if(age()<=6)stage.append(listen(text))};
const nextBtn=fn=>{const b=B(u('another'),fn,'primary craft-next');return b};
function numOptions(ans){const s=new Set([ans]);const step=ans>=200?50:ans>=40?10:1;let k=1;while(s.size<4&&k<30){[ans+k*step,ans-k*step].forEach(v=>{if(v>=0&&s.size<4)s.add(v)});k++}return mix([...s])}

// Pași în ordine
function orderGame(c){const a=age(),avail=c.seqs.filter(s=>a>=(s.minAge||0)&&a<=(s.max||99));const r=rot[craft+'o']=(rot[craft+'o']??rand(avail.length));const s=avail[r%avail.length];const steps=(a<=5&&s.young?s.young.map(i=>s.steps[i]):s.steps);let done=0;
help(u('orderHelp'));stage.append(E('h3',L(s.title),'craft-seq-title'));const scene=E('div','','craft-scene');scene.setAttribute('aria-hidden','true');const list=E('ol','','craft-done');const choices=E('div','','craft-choices');stage.append(scene,list,choices);
const draw=()=>{scene.replaceChildren();if(s.visual==='house')scene.append(houseSVG(steps.slice(0,done).map(x=>x[2])));else{const big=E('span',done?(steps[done-1][2]||steps[done-1][0]):'✨','craft-big');scene.append(big)}};
const btns=mix(steps.map((st,i)=>[st,i])).map(([st,i])=>{const b=B(`${st[0]} ${L(st[1])}`,()=>tap(i,b),'craft-choice');b.dataset.step=i;choices.append(b);return b});
function tap(i,b){if(done>=steps.length)return;if(i!==done){gardenMiss('craft-'+craft);say(u('orderWrong'),false);b.classList.remove('shake');b.getBoundingClientRect();b.classList.add('shake');return}done++;b.disabled=true;b.hidden=true;list.append(E('li',`${steps[i][0]} ${L(steps[i][1])}`));window.gardenSound?.('pop');status.textContent='';draw();if(done===steps.length){gardenCelebrate('craft-'+craft);say(u('orderDone'));stage.append(nextBtn(()=>{rot[craft+'o']++;render()}))}}
draw()}
function houseSVG(ids){const has=k=>ids.includes(k),svg=S('svg',{viewBox:'0 0 200 150',class:'house-svg'});svg.append(S('rect',{x:0,y:0,width:200,height:150,fill:has('plan')&&!has('found')?'#2f6fb0':'#bfe3ff'}));
if(has('plan')&&!has('found')){for(let x=10;x<200;x+=20)svg.append(S('line',{x1:x,y1:0,x2:x,y2:150,stroke:'#ffffff44'}));svg.append(S('rect',{x:55,y:60,width:90,height:70,fill:'none',stroke:'#fff','stroke-width':2,'stroke-dasharray':'5 4'}),S('polyline',{points:'50,62 100,28 150,62',fill:'none',stroke:'#fff','stroke-width':2,'stroke-dasharray':'5 4'}))}
svg.append(S('rect',{x:0,y:130,width:200,height:20,fill:'#7cb342'}));if(has('found'))svg.append(S('rect',{x:48,y:124,width:104,height:10,fill:'#9e9e9e',stroke:'#555'}));
if(has('walls')){svg.append(S('rect',{x:55,y:64,width:90,height:60,fill:has('paint')?'#ffd166':'#c8a27a',stroke:'#6d4c41','stroke-width':2}));if(!has('paint'))for(let y=72;y<124;y+=10)svg.append(S('line',{x1:55,y1:y,x2:145,y2:y,stroke:'#6d4c4155'}))}
if(has('windows'))svg.append(S('rect',{x:64,y:78,width:22,height:18,fill:'#90caf9',stroke:'#37474f','stroke-width':2}),S('rect',{x:114,y:78,width:22,height:18,fill:'#90caf9',stroke:'#37474f','stroke-width':2}),S('rect',{x:90,y:96,width:20,height:28,fill:'#8d6e63',stroke:'#37474f','stroke-width':2}));
if(has('roof'))svg.append(S('polygon',{points:'46,66 100,26 154,66',fill:'#e53935',stroke:'#7f1d1d','stroke-width':2}));if(has('paint'))svg.append(S('circle',{cx:30,cy:126,r:5,fill:'#f48fb1'}),S('circle',{cx:170,cy:126,r:5,fill:'#fdd835'}));return svg}

// Unealta potrivită
function toolGame(c){matchGame(c)}
function matchGame(c,spec){spec=spec||{cases:c.cases,pool:c.pool,dict:TOOLS,help:U.toolHelp};const rk=craft+act,r=rot[rk]=(rot[rk]??rand(spec.cases.length));const [icon,text,ansRaw]=spec.cases[r%spec.cases.length],answers=[].concat(ansRaw),ans=answers[0];let solved=false;
stage.append(E('p',L(spec.help),'studio-help'));const scene=E('div','','craft-problem');scene.append(E('span',icon,'craft-big'),E('p',L(text),'craft-say'));stage.append(scene);if(age()<=6)stage.append(listen(L(text)));
const opts=mix([ans,...mix(spec.pool.filter(k=>!answers.includes(k))).slice(0,age()<=5?2:3)]),row=E('div','',spec.dict===TOOLS?'craft-tools':'craft-tools craft-words');stage.dataset.answer=ans;
opts.forEach(k=>{const [ti,tl]=spec.dict[k],b=B('',()=>{if(solved)return;if(answers.includes(k)){solved=true;b.classList.add('right');gardenCelebrate('craft-'+(spec.game||craft));say(`${u('good')} ${ti} ${L(tl)}`.replace(/  +/g,' '));if(spec.speak)gardenSpeak(L(tl),true);stage.append(nextBtn(()=>{rot[rk]++;render()}))}else{gardenMiss('craft-'+(spec.game||craft));b.classList.add('wrong-pick');say(u(spec.dict===TOOLS?'toolWrong':'nearly'),false)}},'craft-tool');b.dataset.tool=k;if(ti)b.append(E('span',ti,'craft-tool-icon'));b.append(E('span',L(tl)));row.append(b)});stage.append(row)}

// Calcule pe vârstă
function mathGame(c){const q=c.math(age());let solved=false;const text=L(q.text);help(text);if(q.show){const v=E('div',q.show,'craft-show');v.setAttribute('aria-hidden','true');stage.append(v)}
const opts=q.options?mix(q.options):numOptions(q.answer),row=E('div','','craft-answers');stage.dataset.answer=q.answer;
opts.forEach(o=>{const b=B(String(o),()=>{if(solved)return;if(String(o)===String(q.answer)){solved=true;b.classList.add('right');gardenCelebrate('craft-math');say(u('good'));stage.append(nextBtn(render))}else{gardenMiss('craft-math');b.classList.add('wrong-pick');say(q.hint?`${u('nearly')} ${L(q.hint)}`:u('nearly'),false)}},'craft-answer');row.append(b)});stage.append(row)}

// ——— Olărit: roata olarului, glazură, model, cuptor
const GLAZE=[['terra','#c8693f',['teracotă','terracotta','terrakotta','теракота']],['blue','#3f7fd1',['albastru','blue','kék','синя']],['green','#4f9f5a',['verde','green','zöld','зелена']],['yellow','#e6b83c',['galben','yellow','sárga','жовта']],['white','#f3efe6',['alb','white','fehér','біла']],['purple','#8a5cc2',['mov','purple','lila','фіолетова']]];
const POT={height:[['low',70,['scund','short','alacsony','низька']],['mid',100,['mijlociu','medium','közepes','середня']],['tall',128,['înalt','tall','magas','висока']]],belly:[['thin',26,['subțire','slim','karcsú','вузька']],['mid',36,['potrivit','medium','közepes','середня']],['round',46,['rotund','round','kerek','кругла']]],neck:[['wide',30,['larg','wide','széles','широка']],['narrow',13,['îngust','narrow','keskeny','вузька']]],pattern:[['none','',['fără model','plain','minta nélkül','без візерунка']],['stripes','',['dungi','stripes','csíkos','смужки']],['dots','',['buline','dots','pöttyös','горошок']],['waves','',['valuri','waves','hullámos','хвильки']]]};
const PU={intro:['Modelează un vas pe roata olarului, alege glazura și coace-l în cuptor.','Shape a pot on the potter’s wheel, choose a glaze and fire it in the kiln.','Formázz edényt a fazekaskorongon, válassz mázat, és égesd ki a kemencében.','Виліпи посудину на гончарному крузі, обери глазур і випали її в печі.'],
free:['🏺 Atelier liber','🏺 Free workshop','🏺 Szabad műhely','🏺 Вільна майстерня'],order:['📋 Comenzi','📋 Orders','📋 Rendelések','📋 Замовлення'],
height:['Înălțime','Height','Magasság','Висота'],belly:['Burtică','Body','Has','Черевце'],neck:['Gât','Neck','Nyak','Шийка'],glaze:['Glazură','Glaze','Máz','Глазур'],pattern:['Model','Pattern','Minta','Візерунок'],
bake:['🔥 Coace în cuptor','🔥 Fire in the kiln','🔥 Kiégetés','🔥 Випалити в печі'],baked:['Vasul e gata și e pe raft! 🏺','Your pot is finished and on the shelf! 🏺','Kész az edény, már a polcon van! 🏺','Посудина готова й стоїть на полиці! 🏺'],shelf:['Raftul meu','My shelf','A polcom','Моя полиця'],empty:['Vasele coapte apar aici.','Fired pots appear here.','A kiégetett edények itt jelennek meg.','Тут з’являться випалені посудини.'],
wants:['Comanda: un vas {height}, cu burtică {belly}, gât {neck}, glazură {glaze} și {pattern}.','Order: a {height} pot with a {belly} body, a {neck} neck, {glaze} glaze and {pattern}.','Rendelés: {height} edény, {belly} hassal, {neck} nyakkal, {glaze} mázzal, {pattern}.','Замовлення: {height} посудина, {belly} черевце, {neck} шийка, {glaze} глазур і {pattern}.'],
miss:['Aproape! Clientul voia altceva la: {list}.','Nearly! The customer wanted something else for: {list}.','Majdnem! A vevő mást kért ennél: {list}.','Майже! Клієнт хотів інше: {list}.'],orderOk:['Exact ce a cerut clientul! 🎉','Exactly what the customer asked for! 🎉','Pontosan ezt kérte a vevő! 🎉','Саме те, що замовив клієнт! 🎉']};
let pot={height:'mid',belly:'mid',neck:'wide',glaze:'terra',pattern:'none'},potMode='free',potOrder=null;
function potPath(p,sc=1){const H=POT.height.find(x=>x[0]===p.height)[1],W=POT.belly.find(x=>x[0]===p.belly)[1],N=POT.neck.find(x=>x[0]===p.neck)[1],b=22,y0=172,top=y0-H,by=y0-H*.42,ny=y0-H*.86;
return `M${100-b} ${y0} L${100+b} ${y0} C${100+W+4} ${y0-6} ${100+W} ${by+14} ${100+W} ${by} C${100+W} ${by-18} ${100+N} ${ny+10} ${100+N} ${ny} L${100+N+6} ${top} L${100-N-6} ${top} L${100-N} ${ny} C${100-N} ${ny+10} ${100-W} ${by-18} ${100-W} ${by} C${100-W} ${by+14} ${100-W-4} ${y0-6} ${100-b} ${y0} Z`}
function potSVG(p,small){const svg=S('svg',{viewBox:'0 0 200 190',class:small?'pot-mini':'pot-svg'}),id='c'+Math.random().toString(36).slice(2,8),col=GLAZE.find(g=>g[0]===p.glaze)[1],d=potPath(p);
if(!small){svg.append(S('ellipse',{cx:100,cy:178,rx:78,ry:10,fill:'#6d4c41'}),S('ellipse',{cx:100,cy:174,rx:70,ry:8,fill:'#8d6e63',class:'wheel-top'}))}
const cp=S('clipPath',{id});cp.append(S('path',{d}));svg.append(cp,S('path',{d,fill:col,stroke:'#3b2a20','stroke-width':2.5}));const g=S('g',{'clip-path':`url(#${id})`}),dark='#00000040',light='#ffffff99';
if(p.pattern==='stripes')for(let y=30;y<175;y+=16)g.append(S('rect',{x:0,y,width:200,height:6,fill:p.glaze==='white'?'#3f7fd1':light}));
if(p.pattern==='dots')for(let y=34;y<172;y+=16)for(let x=40+(y/16%2)*8;x<170;x+=16)g.append(S('circle',{cx:x,cy:y,r:3.5,fill:p.glaze==='white'?'#c8693f':light}));
if(p.pattern==='waves')for(let y=40;y<172;y+=20)g.append(S('path',{d:`M20 ${y} q10 -8 20 0 t20 0 t20 0 t20 0 t20 0 t20 0 t20 0 t20 0`,fill:'none',stroke:p.glaze==='white'?'#4f9f5a':light,'stroke-width':3}));
g.append(S('rect',{x:100,y:0,width:100,height:190,fill:dark,opacity:.35}));svg.append(g);return svg}
const potLabel=(k,v)=>L((k==='glaze'?GLAZE:POT[k]).find(x=>x[0]===v)[2]);
function pottery(){const a=age();const tabs=E('div','','learning-tabs page-picker');[['free',PU.free],['order',PU.order]].forEach(([k,t])=>{if(k==='order'&&a<6)return;const b=B(L(t),()=>{potMode=k;if(k==='order'&&!potOrder)potOrder=newOrder();render()});b.setAttribute('aria-pressed',potMode===k);tabs.append(b)});if(a>=6)stage.append(tabs);else potMode='free';
help(L(PU.intro));if(potMode==='order'){if(!potOrder)potOrder=newOrder();const o={};for(const k in potOrder)o[k]=potLabel(k,potOrder[k]);stage.dataset.order=JSON.stringify(potOrder);const w=E('p',fmt(L(PU.wants),o),'craft-order');stage.append(w);if(a<=6)stage.append(listen(w.textContent))}
const wrap=E('div','','pot-wrap'),view=E('div','','pot-view');wrap.append(view);const ctrl=E('div','','pot-controls');wrap.append(ctrl);stage.append(wrap);
const draw=()=>{view.replaceChildren(potSVG(pot));view.setAttribute('role','img');view.setAttribute('aria-label',Object.keys(pot).map(k=>`${L(PU[k])}: ${potLabel(k,pot[k])}`).join(', '))};
const group=(k,items,swatch)=>{const box=E('div','','pot-group'),row=E('div','','draw-tools');row.setAttribute('role','group');row.setAttribute('aria-label',L(PU[k]));box.append(E('strong',L(PU[k])),row);items.forEach(it=>{const b=B(swatch?'':L(it[2]),()=>{pot[k]=it[0];row.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',x.dataset.v===pot[k]));draw()},swatch?'swatch':'');b.dataset.v=it[0];if(swatch){b.style.setProperty('--sw',it[1]);b.setAttribute('aria-label',L(it[2]));b.title=L(it[2])}b.setAttribute('aria-pressed',pot[k]===it[0]);row.append(b)});ctrl.append(box)};
group('height',POT.height);group('belly',POT.belly);group('neck',POT.neck);group('glaze',GLAZE,true);group('pattern',POT.pattern);draw();
const bake=B(L(PU.bake),()=>{if(potMode==='order'){const wrong=Object.keys(potOrder).filter(k=>pot[k]!==potOrder[k]);if(wrong.length){gardenMiss('craft-pottery');say(fmt(L(PU.miss),{list:wrong.map(k=>L(PU[k]).toLowerCase()).join(', ')}),false);return}}
view.classList.add('firing');bake.disabled=true;setTimeout(()=>{view.classList.remove('firing');bake.disabled=false;const d=read();d.shelf=[{...pot},...(d.shelf||[])].slice(0,10);save(d);gardenCelebrate('craft-pottery');say(potMode==='order'?L(PU.orderOk):L(PU.baked));if(potMode==='order')potOrder=newOrder();drawShelf();if(potMode==='order'){const w=stage.querySelector('.craft-order');if(w){const o={};for(const k in potOrder)o[k]=potLabel(k,potOrder[k]);w.textContent=fmt(L(PU.wants),o);stage.dataset.order=JSON.stringify(potOrder)}}},document.body.classList.contains('quiet')||window.gardenMusicFast?50:1200)},'primary pot-bake');stage.append(bake);
const shelf=E('div','','pot-shelf');stage.append(E('h3',L(PU.shelf)),shelf);const drawShelf=()=>{const list=read().shelf||[];shelf.replaceChildren(...(list.length?list.map(p=>potSVG(p,true)):[E('p',L(PU.empty),'small')]))};drawShelf()}
function newOrder(){const o={};['height','belly','neck','pattern'].forEach(k=>o[k]=pick(POT[k])[0]);o.glaze=pick(GLAZE)[0];if(age()<9){o.neck='wide';o.pattern='none'}return o}

// ——— Croșetat: continuă modelul de culori
const YARN=[['#e53935','●',['roșu','red','piros','червоний']],['#1e88e5','▲',['albastru','blue','kék','синій']],['#fdd835','■',['galben','yellow','sárga','жовтий']],['#43a047','◆',['verde','green','zöld','зелений']],['#8e24aa','★',['mov','purple','lila','фіолетовий']],['#f48fb1','♥',['roz','pink','rózsaszín','рожевий']]];
const CU={intro:['Croșetează un fular: continuă modelul de culori, ochi cu ochi. Fiecare rând terminat se adaugă la fular.','Crochet a scarf: continue the colour pattern stitch by stitch. Each finished row is added to the scarf.','Horgolj sálat: folytasd a színmintát szemenként. Minden kész sor a sálhoz kerül.','В’яжи шарф: продовжуй кольоровий візерунок петля за петлею. Кожен готовий ряд додається до шарфа.'],
wrong:['Uită-te la model: ce culoare urmează?','Look at the pattern: which colour comes next?','Nézd a mintát: melyik szín jön?','Поглянь на візерунок: який колір далі?'],row:['Rând gata! 🧶','Row finished! 🧶','Kész a sor! 🧶','Ряд готовий! 🧶'],done:['Fularul e gata! L-ai pus în dulap. 🧣','The scarf is finished! It’s in your wardrobe. 🧣','Kész a sál! A szekrényedbe került. 🧣','Шарф готовий! Він у твоїй шафі. 🧣'],
rows:['Rânduri: {n} din {t}','Rows: {n} of {t}','Sorok: {n} / {t}','Ряди: {n} з {t}'],yarn:['Ghemele','Yarn','Fonalak','Клубки'],stitch:['Ochiul {n}: {c}','Stitch {n}: {c}','{n}. szem: {c}','Петля {n}: {c}'],emptySt:['gol','empty','üres','порожня'],scarves:['Fulare terminate: {n}','Scarves finished: {n}','Kész sálak: {n}','Готових шарфів: {n}'],
count:['Fularul are {r} rânduri a câte {n} ochiuri. Câte ochiuri ai croșetat în total?','The scarf has {r} rows of {n} stitches. How many stitches did you crochet in total?','A sál {r} sorból áll, soronként {n} szemmel. Hány szemet horgoltál összesen?','У шарфі {r} ряди по {n} петель. Скільки петель ти зв’язав(-ла) загалом?']};
let scarf=[],rowSt=null;
function crochet(){const a=age(),total=a<=5?3:4,len=a<=5?6:a<=8?8:10;
const units=a<=5?[[0,1],[0,0,1]]:a<=8?[[0,1,2],[0,0,1,1],[0,1,1],[0,1,0,2]]:[[0,1,2,3],[0,0,1,2],[0,1,2,1],[0,1,1,2,2]];
if(!rowSt){const unit=pick(units),cols=mix([0,1,2,3,4,5]).slice(0,4),seq=Array.from({length:len},(_,i)=>cols[unit[i%unit.length]]),given=Math.min(len-3,unit.length+(a<=5?1:0));rowSt={seq,given,filled:given,cols:[...new Set(unit.map(x=>cols[x]))],extra:cols.find(c=>!unit.map(x=>cols[x]).includes(c))}}
help(L(CU.intro));const info=E('p',fmt(L(CU.rows),{n:scarf.length,t:total}),'versus-pairs');stage.append(info);
const sc=E('div','','scarf');sc.setAttribute('aria-hidden','true');scarf.forEach(r=>{const rw=E('div','','scarf-row');r.forEach(c=>rw.append(stitchEl(c)));sc.append(rw)});
const row=E('div','','scarf-row active');row.setAttribute('role','group');const cells=rowSt.seq.map((c,i)=>{const s=stitchEl(i<rowSt.filled?c:null);s.setAttribute('aria-label',fmt(L(CU.stitch),{n:i+1,c:i<rowSt.filled?L(YARN[c][2]):L(CU.emptySt)}));s.setAttribute('role','img');row.append(s);return s});
stage.append(sc,row);const pal=E('div','','draw-tools yarn');pal.setAttribute('role','group');pal.setAttribute('aria-label',L(CU.yarn));
const options=mix([...rowSt.cols,...(a>=6&&rowSt.extra!=null?[rowSt.extra]:[])]);stage.dataset.next=rowSt.seq[rowSt.filled];
options.forEach(c=>{const b=B('',()=>put(c,b),'yarn-btn');b.dataset.c=c;b.style.setProperty('--sw',YARN[c][0]);b.append(E('span',YARN[c][1]));b.setAttribute('aria-label',L(YARN[c][2]));b.title=L(YARN[c][2]);pal.append(b)});stage.append(pal);
function put(c,b){if(!rowSt||rowSt.filled>=rowSt.seq.length)return;const i=rowSt.filled;if(rowSt.seq[i]!==c){gardenMiss('craft-crochet');say(L(CU.wrong),false);cells[i].classList.remove('shake');cells[i].getBoundingClientRect();cells[i].classList.add('shake');return}
rowSt.filled++;const s=stitchEl(c);s.setAttribute('role','img');s.setAttribute('aria-label',fmt(L(CU.stitch),{n:i+1,c:L(YARN[c][2])}));cells[i].replaceWith(s);cells[i]=s;window.gardenSound?.('pop');status.textContent='';stage.dataset.next=rowSt.seq[rowSt.filled]??'';
if(rowSt.filled===rowSt.seq.length){scarf.push(rowSt.seq);rowSt=null;gardenCelebrate('craft-crochet');if(scarf.length>=total){const d=read();d.scarves=(d.scarves||0)+1;save(d);const finished=scarf.length,n=len;scarf=[];render();say(L(CU.done));if(a>=8){const q={text:fmt(L(CU.count),{r:finished,n}),answer:finished*n};const p=E('p',q.text,'studio-help');const r=E('div','','craft-answers');numOptions(q.answer).forEach(o=>{const bb=B(String(o),()=>{if(o===q.answer){gardenCelebrate('craft-math');say(u('good'));r.querySelectorAll('button').forEach(x=>x.disabled=true);bb.classList.add('right')}else{gardenMiss('craft-math');bb.classList.add('wrong-pick');say(u('nearly'),false)}},'craft-answer');r.append(bb)});stage.prepend(p,r);stage.dataset.answer=q.answer}}else{render();say(L(CU.row))}}}
stage.append(E('p',fmt(L(CU.scarves),{n:read().scarves||0}),'small'))}
function stitchEl(c){const s=E('span','','stitch');if(c==null){s.classList.add('empty');return s}s.style.setProperty('--y',YARN[c][0]);s.append(E('i',YARN[c][1]));return s}

// ——— Randare
function render(){if(!profile||$('app').hidden)return;token++;section.replaceChildren();delete section.dataset.craft;
if(!craft||!(craft in C)&&craft!=='pottery'&&craft!=='crochet'){craft=null;const head=E('div','','versus-head');head.append(E('span','🧰','craft-head-icon'),E('div'));head.lastChild.append(E('h2',u('title')),E('p',u('intro')));section.append(head);
const grid=E('div','','craft-hub');HUB.forEach(([k,icon,name,desc])=>{const b=B('',()=>{if(k==='drawing'||k==='music'){gardenGo(k);return}craft=k;act=null;render();section.querySelector('h2')?.focus?.()},'craft-card');b.dataset.craft=k;b.append(E('span',icon,'craft-card-icon'),E('strong',L(name)),E('span',L(desc),'small'));grid.append(b)});section.append(grid);return}
section.dataset.craft=craft;const c=C[craft];const top=E('div','','draw-tools');top.append(B(u('back'),()=>{craft=null;render()},'studio-back'));section.append(top);
const head=E('div','','versus-head');head.append(E('span',HUB.find(h=>h[0]===craft)[1],'craft-head-icon'),E('div'));head.lastChild.append(E('h2',nameOf(craft)));if(c)head.lastChild.append(E('p',L(c.intro)));section.append(head);
if(c?.safe){const n=E('p','','craft-safety');n.append(E('strong',`⚠️ ${u('safety')}: `),document.createTextNode(L(c.safe)));section.append(n)}
if(c){const acts=actsOf(c);if(!acts.some(x=>x[0]===act))act=acts[0][0];const tabs=E('div','','learning-tabs');acts.forEach(([k,t])=>{const b=B(L(t),()=>{act=k;render()});b.setAttribute('aria-pressed',act===k);tabs.append(b)});section.append(tabs)}
stage=E('div','','learning-stage studio-stage');status=E('div','','learning-feedback');status.setAttribute('role','status');status.setAttribute('aria-live','polite');section.append(stage,status);
if(craft==='pottery')pottery();else if(craft==='crochet')crochet();else{const x=actsOf(c).find(y=>y[0]===act);({order:orderGame,tool:toolGame,math:mathGame,match:matchGame,pick:pickGame})[x[2]||x[0]](c,x[3])}}
const actsOf=c=>c.acts||[['order',U.tabSteps],['tool',U.tabTools],['math',U.tabMath]];
document.addEventListener('garden:open',e=>{const {view,mode:m}=e.detail||{};if(view!=='studio')return;craft=m||null;act=null;render()});
window.gardenCrafts={open:k=>{craft=k;act=null;render()}};
gardenOn(r=>{if(r==='start'||r==='switch'){craft=null;act=null;scarf=[];rowSt=null;potOrder=null}render()});if(profile)render();
})();
