// Grădina Curioasă — Descoperă: litere, ceasul, bani, puzzle pe siluetă, povești cu mai multe finaluri.
(()=>{
const D={
ro:{title:'Descoperă',intro:'Litere, ceasul, banii, puzzle-uri și povești cu mai multe finaluri.',letters:'Litere',clock:'Ceasul',money:'Bani',puzzle:'Puzzle',tale:'Povești',listen:'🔊 Ascultă',next:'Mai departe',level:'Nivelul',findLetter:'Găsește litera',findLetterHelp:'Atinge litera {l}.',firstSound:'Primul sunet',firstSoundHelp:'Cu ce literă începe cuvântul?',missing:'Litera lipsă',missingHelp:'Ce literă lipsește din cuvânt?',clockQ:'Cât arată ceasul?',clockLater:'Ceasul arată ora de acum. Cât va fi peste {m} minute?',clockLabel:'Ceas analogic',countPieces:'Câte monede și bancnote vezi?',total:'Câți bani sunt în total?',afford:'Ai {s}. Ce îți poți cumpăra?',change:'Ai {s} și cumperi ceva care costă {p}. Cât rest primești?',wallet:'Portofelul tău',puzzleHelp:'Trage fiecare piesă pe umbra ei. Poți și să atingi piesa, apoi locul ei.',puzzleDone:'Ai construit {name}!',pieceWrong:'Piesa nu se potrivește aici. Încearcă alt loc.',slot:'Loc pentru {shape}',piece:'Piesă: {shape}',selected:'Ai ales {shape}. Acum atinge locul ei.',square:'pătrat',rect:'dreptunghi',triangle:'triunghi',triangleL:'triunghi culcat',circle:'cerc',oval:'oval',hull:'trapez',house:'o casă',tree:'un copac',boat:'o barcă',rocket:'o rachetă',snowman:'un om de zăpadă',fish:'un pește',extra:'Atenție: o piesă nu își are locul în desen.',well:'Ai descoperit!',retry:'Mai privește și încearcă din nou.',endings:'Finaluri găsite: {n}/{t}',again:'Citește din nou',other:'Altă poveste',theEnd:'Final',chooseStory:'Alege o poveste și decide ce se întâmplă.'},
en:{title:'Discover',intro:'Letters, the clock, money, puzzles and stories with more than one ending.',letters:'Letters',clock:'Clock',money:'Money',puzzle:'Puzzle',tale:'Stories',listen:'🔊 Listen',next:'Keep going',level:'Level',findLetter:'Find the letter',findLetterHelp:'Tap the letter {l}.',firstSound:'First sound',firstSoundHelp:'Which letter does the word start with?',missing:'Missing letter',missingHelp:'Which letter is missing from the word?',clockQ:'What time does the clock show?',clockLater:'The clock shows the time now. What time will it be in {m} minutes?',clockLabel:'Analog clock',countPieces:'How many coins and notes can you see?',total:'How much money is there in total?',afford:'You have {s}. What can you buy?',change:'You have {s} and buy something that costs {p}. How much change do you get?',wallet:'Your wallet',puzzleHelp:'Drag each piece onto its shadow. You can also tap a piece, then its place.',puzzleDone:'You built {name}!',pieceWrong:'That piece does not fit here. Try another place.',slot:'Place for {shape}',piece:'Piece: {shape}',selected:'You chose {shape}. Now tap its place.',square:'square',rect:'rectangle',triangle:'triangle',triangleL:'sideways triangle',circle:'circle',oval:'oval',hull:'trapezoid',house:'a house',tree:'a tree',boat:'a boat',rocket:'a rocket',snowman:'a snowman',fish:'a fish',extra:'Careful: one piece does not belong in the picture.',well:'You discovered it!',retry:'Look again and try once more.',endings:'Endings found: {n}/{t}',again:'Read again',other:'Another story',theEnd:'Ending',chooseStory:'Choose a story and decide what happens.'},
hu:{title:'Felfedezés',intro:'Betűk, óra, pénz, kirakósok és több befejezésű mesék.',letters:'Betűk',clock:'Óra',money:'Pénz',puzzle:'Kirakó',tale:'Mesék',listen:'🔊 Meghallgatom',next:'Tovább',level:'Szint',findLetter:'Keresd a betűt',findLetterHelp:'Érintsd meg ezt a betűt: {l}.',firstSound:'Az első hang',firstSoundHelp:'Milyen betűvel kezdődik a szó?',missing:'Hiányzó betű',missingHelp:'Melyik betű hiányzik a szóból?',clockQ:'Mennyit mutat az óra?',clockLater:'Az óra a mostani időt mutatja. Mennyi lesz {m} perc múlva?',clockLabel:'Mutatós óra',countPieces:'Hány érmét és bankjegyet látsz?',total:'Mennyi pénz van összesen?',afford:'Van {s}. Mit tudsz megvenni?',change:'Van {s}, és veszel valamit, ami {p}. Mennyi visszajárót kapsz?',wallet:'A pénztárcád',puzzleHelp:'Húzd minden darabot az árnyékára. Megérintheted a darabot is, aztán a helyét.',puzzleDone:'Megépítetted: {name}!',pieceWrong:'Ez a darab nem ide illik. Próbálj másik helyet.',slot:'Hely: {shape}',piece:'Darab: {shape}',selected:'Ezt választottad: {shape}. Most érintsd meg a helyét.',square:'négyzet',rect:'téglalap',triangle:'háromszög',triangleL:'fekvő háromszög',circle:'kör',oval:'ovális',hull:'trapéz',house:'egy ház',tree:'egy fa',boat:'egy hajó',rocket:'egy rakéta',snowman:'egy hóember',fish:'egy hal',extra:'Figyelem: egy darab nem tartozik a képhez.',well:'Rájöttél!',retry:'Nézd meg újra, és próbáld még egyszer.',endings:'Megtalált befejezések: {n}/{t}',again:'Újra elolvasom',other:'Másik mese',theEnd:'Befejezés',chooseStory:'Válassz egy mesét, és döntsd el, mi történjen.'},
uk:{title:'Відкриття',intro:'Літери, годинник, гроші, пазли та казки з кількома кінцівками.',letters:'Літери',clock:'Годинник',money:'Гроші',puzzle:'Пазл',tale:'Казки',listen:'🔊 Послухати',next:'Далі',level:'Рівень',findLetter:'Знайди літеру',findLetterHelp:'Торкнися літери {l}.',firstSound:'Перший звук',firstSoundHelp:'З якої літери починається слово?',missing:'Пропущена літера',missingHelp:'Якої літери бракує в слові?',clockQ:'Котру годину показує годинник?',clockLater:'Годинник показує, котра зараз година. Котра буде через {m} хвилин?',clockLabel:'Годинник зі стрілками',countPieces:'Скільки монет і банкнот ти бачиш?',total:'Скільки грошей разом?',afford:'У тебе {s}. Що ти можеш купити?',change:'У тебе {s}, і ти купуєш щось за {p}. Скільки тобі дадуть решти?',wallet:'Твій гаманець',puzzleHelp:'Перетягни кожну деталь на її тінь. Можна також торкнутися деталі, а потім її місця.',puzzleDone:'Ти склав(-ла) {name}!',pieceWrong:'Ця деталь сюди не підходить. Спробуй інше місце.',slot:'Місце для: {shape}',piece:'Деталь: {shape}',selected:'Ти обрав(-ла): {shape}. Тепер торкнися її місця.',square:'квадрат',rect:'прямокутник',triangle:'трикутник',triangleL:'трикутник набік',circle:'коло',oval:'овал',hull:'трапеція',house:'будиночок',tree:'дерево',boat:'човен',rocket:'ракету',snowman:'сніговика',fish:'рибку',extra:'Увага: одна деталь зайва.',well:'Ти відкрив(-ла) це!',retry:'Подивися ще раз і спробуй знову.',endings:'Знайдено кінцівок: {n}/{t}',again:'Прочитати ще раз',other:'Інша казка',theEnd:'Кінцівка',chooseStory:'Обери казку й виріши, що станеться.'}};
const WORDS={
ro:[['MĂR','🍎'],['CASĂ','🏠'],['SOARE','☀️'],['LUNĂ','🌙'],['PEȘTE','🐟'],['URS','🐻'],['AVION','✈️'],['BARCĂ','⛵'],['FLOARE','🌸'],['NOR','☁️'],['OU','🥚'],['IEPURE','🐰'],['DOVLEAC','🎃'],['TORT','🎂'],['ROCHIE','👗'],['VACĂ','🐄'],['ZEBRĂ','🦓'],['ELEFANT','🐘'],['INIMĂ','❤️'],['TREN','🚂'],['CAL','🐴'],['PISICĂ','🐱'],['LAPTE','🥛'],['GHIOZDAN','🎒']],
en:[['APPLE','🍎'],['HOUSE','🏠'],['SUN','☀️'],['MOON','🌙'],['FISH','🐟'],['BEAR','🐻'],['PLANE','✈️'],['BOAT','⛵'],['FLOWER','🌸'],['CLOUD','☁️'],['EGG','🥚'],['RABBIT','🐰'],['PUMPKIN','🎃'],['CAKE','🎂'],['DRESS','👗'],['COW','🐄'],['ZEBRA','🦓'],['ELEPHANT','🐘'],['HEART','❤️'],['TRAIN','🚂'],['HORSE','🐴'],['CAT','🐱'],['DOG','🐶'],['MILK','🥛']],
hu:[['ALMA','🍎'],['HÁZ','🏠'],['NAP','☀️'],['HOLD','🌙'],['HAL','🐟'],['MEDVE','🐻'],['REPÜLŐ','✈️'],['HAJÓ','⛵'],['VIRÁG','🌸'],['FELHŐ','☁️'],['TOJÁS','🥚'],['BÉKA','🐸'],['TÖK','🎃'],['TORTA','🎂'],['RUHA','👗'],['TEHÉN','🐄'],['ZEBRA','🦓'],['ELEFÁNT','🐘'],['EPER','🍓'],['VONAT','🚂'],['LÓ','🐴'],['MACSKA','🐱'],['KUTYA','🐶'],['TEJ','🥛']],
uk:[['ЯБЛУКО','🍎'],['ДІМ','🏠'],['СОНЦЕ','☀️'],['МІСЯЦЬ','🌙'],['РИБА','🐟'],['ВЕДМІДЬ','🐻'],['ЛІТАК','✈️'],['ЧОВЕН','⛵'],['КВІТКА','🌸'],['ХМАРА','☁️'],['ЯЙЦЕ','🥚'],['ЗАЄЦЬ','🐰'],['ГАРБУЗ','🎃'],['ТОРТ','🎂'],['СУКНЯ','👗'],['КОРОВА','🐄'],['ЗЕБРА','🦓'],['СЛОН','🐘'],['СЕРЦЕ','❤️'],['ПОТЯГ','🚂'],['КІНЬ','🐴'],['КІТ','🐱'],['ПЕС','🐶'],['МОЛОКО','🥛']]};
const ABC={ro:'AĂÂBCDEFGHIÎJLMNOPRSȘTȚUVZ',en:'ABCDEFGHIJKLMNOPRSTUVWZ',hu:'AÁBCDEÉFGHIÍJKLMNOÓÖŐPRSTUÚÜŰVZ',uk:'АБВГДЕЄЖЗИІЇКЛМНОПРСТУФХЦЧШЯ'};
// Monedă și bancnote pe limbă: valori întregi, ușor de adunat.
const CUR={ro:{pieces:[1,5,10],note:v=>v>=1,fmt:n=>n===1?'1 leu':`${n} lei`},en:{pieces:[1,2,5,10],note:v=>v>=5,fmt:n=>`€${n}`},hu:{pieces:[10,20,50,100],note:v=>v>=500,fmt:n=>`${n} Ft`},uk:{pieces:[1,2,5,10],note:v=>v>=20,fmt:n=>`${n} ₴`}};
const ITEMS=['🧃','🍦','📓','🎈','🍪','🧸','⚽','🖍️'];
// Povești ramificate: [text, emoji, [[alegere, nod]...]] ; nodurile „end” au titlu de final.
const TALES={
ro:{bia:{title:'Buburuza și cheia pierdută',nodes:{s:['Buburuza Bia găsește o cheie mică în iarbă. A cui să fie?','🔑',[['Întreab-o pe furnică','ant'],['Urmează urmele din noroi','tracks']]],ant:['Furnica spune că a văzut un melc care căuta ceva lângă fântână.','🐜',[['Mergi la fântână','snail'],['Ajut-o întâi pe furnică să care firimiturile','help']]],tracks:['Urmele duc la o căsuță-ciupercă încuiată.','🍄',[['Încearcă cheia','e1'],['Bate la ușă','snail']]],snail:['Melcul Mihai e trist: și-a pierdut cheia de la căsuță!','🐌',[['Dă-i cheia','e2'],['Ajută-l să caute și umbrela pierdută','e3']]],help:['Furnica îți mulțumește și vine cu tine. Împreună îl găsiți pe melc.','🐜',[['Dă-i melcului cheia','e2']]],e1:['Ușa se deschide. Înăuntru, melcul te așteaptă cu ceai!','🍵','Musafirul neașteptat'],e2:['Melcul zâmbește și te invită la el acasă.','🐌','Prietenul de la fântână'],e3:['Găsiți împreună umbrela, chiar înainte de ploaie.','☂️','Echipa de căutători']}},
rocket:{title:'Racheta de carton',nodes:{s:['Ai construit o rachetă din cutii. Unde zbori mai întâi?','🚀',[['Spre Lună','moon'],['Spre o planetă albastră','planet']]],moon:['Pe Lună e foarte liniște. Vezi o piatră care strălucește.','🌙',[['O iei ca amintire','e1'],['O lași la locul ei și faci o fotografie','e2']]],planet:['Te întâmpină un extraterestru prietenos care nu vorbește limba ta.','👽',[['Îi faci cu mâna','friend'],['Îi desenezi un soare','friend']]],friend:['Extraterestrul râde și îți arată grădina lui de stele.','✨',[['Plantați împreună o stea','e3'],['Îl inviți pe Pământ','e4']]],e1:['Piatra îți luminează camera în fiecare noapte.','🌙','Lumina de pe Lună'],e2:['Fotografia ajunge în albumul clasei.','📷','Exploratorul grijuliu'],e3:['Steaua voastră strălucește pe cer în fiecare seară.','⭐','Grădinarul de stele'],e4:['A doua zi, extraterestrul aterizează în curtea ta!','🛸','Vizita surpriză']}}},
en:{bia:{title:'The ladybug and the lost key',nodes:{s:['Bia the ladybug finds a tiny key in the grass. Whose could it be?','🔑',[['Ask the ant','ant'],['Follow the tracks in the mud','tracks']]],ant:['The ant says she saw a snail looking for something near the well.','🐜',[['Go to the well','snail'],['First help the ant carry crumbs','help']]],tracks:['The tracks lead to a locked mushroom house.','🍄',[['Try the key','e1'],['Knock on the door','snail']]],snail:['Mike the snail is sad: he lost the key to his house!','🐌',[['Give him the key','e2'],['Help him find his lost umbrella too','e3']]],help:['The ant thanks you and comes along. Together you find the snail.','🐜',[['Give the snail the key','e2']]],e1:['The door opens. Inside, the snail is waiting with tea!','🍵','The surprise guest'],e2:['The snail smiles and invites you to his home.','🐌','The friend by the well'],e3:['Together you find the umbrella, just before the rain.','☂️','The search team']}},
rocket:{title:'The cardboard rocket',nodes:{s:['You built a rocket from boxes. Where do you fly first?','🚀',[['To the Moon','moon'],['To a blue planet','planet']]],moon:['The Moon is very quiet. You see a shiny stone.','🌙',[['Keep it as a souvenir','e1'],['Leave it and take a photo','e2']]],planet:['A friendly alien greets you but does not speak your language.','👽',[['Wave hello','friend'],['Draw a sun for it','friend']]],friend:['The alien laughs and shows you its star garden.','✨',[['Plant a star together','e3'],['Invite it to Earth','e4']]],e1:['The stone lights up your room every night.','🌙','Moonlight'],e2:['The photo goes into the class album.','📷','The careful explorer'],e3:['Your star shines in the sky every evening.','⭐','The star gardener'],e4:['The next day, the alien lands in your yard!','🛸','The surprise visit']}}},
hu:{bia:{title:'A katica és az elveszett kulcs',nodes:{s:['Bia katica egy apró kulcsot talál a fűben. Vajon kié lehet?','🔑',[['Megkérdezem a hangyát','ant'],['Követem a nyomokat a sárban','tracks']]],ant:['A hangya látott egy csigát, aki valamit keresett a kútnál.','🐜',[['Elmegyek a kúthoz','snail'],['Előbb segítek a hangyának morzsát vinni','help']]],tracks:['A nyomok egy bezárt gombaházhoz vezetnek.','🍄',[['Kipróbálom a kulcsot','e1'],['Bekopogok','snail']]],snail:['Miki csiga szomorú: elvesztette a háza kulcsát!','🐌',[['Odaadom neki a kulcsot','e2'],['Segítek megkeresni az esernyőjét is','e3']]],help:['A hangya megköszöni, és veled tart. Együtt megtaláljátok a csigát.','🐜',[['Odaadom a csigának a kulcsot','e2']]],e1:['Az ajtó kinyílik. Bent a csiga teával vár!','🍵','A váratlan vendég'],e2:['A csiga mosolyog, és meghív magához.','🐌','A kút melletti barát'],e3:['Együtt megtaláljátok az esernyőt, épp az eső előtt.','☂️','A kereső csapat']}},
rocket:{title:'A kartonrakéta',nodes:{s:['Dobozokból rakétát építettél. Hová repülsz először?','🚀',[['A Holdra','moon'],['Egy kék bolygóra','planet']]],moon:['A Holdon nagy a csend. Látsz egy csillogó követ.','🌙',[['Elteszem emléknek','e1'],['A helyén hagyom, és fényképet készítek','e2']]],planet:['Egy barátságos űrlény fogad, de nem beszéli a nyelvedet.','👽',[['Integetek neki','friend'],['Rajzolok neki egy napot','friend']]],friend:['Az űrlény nevet, és megmutatja a csillagkertjét.','✨',[['Együtt ültetünk egy csillagot','e3'],['Meghívom a Földre','e4']]],e1:['A kő minden éjjel bevilágítja a szobádat.','🌙','Holdfény'],e2:['A fénykép bekerül az osztály albumába.','📷','A gondos felfedező'],e3:['A csillagotok minden este ragyog az égen.','⭐','A csillagkertész'],e4:['Másnap az űrlény leszáll az udvarotokon!','🛸','A meglepetés-látogatás']}}},
uk:{bia:{title:'Сонечко і загублений ключик',nodes:{s:['Сонечко Бія знаходить у траві маленький ключик. Чий він?','🔑',[['Запитати мурашку','ant'],['Піти слідами в багнюці','tracks']]],ant:['Мурашка каже, що бачила равлика, який щось шукав біля криниці.','🐜',[['Піти до криниці','snail'],['Спершу допомогти мурашці нести крихти','help']]],tracks:['Сліди ведуть до замкненого будиночка-грибочка.','🍄',[['Спробувати ключик','e1'],['Постукати у двері','snail']]],snail:['Равлик Михайлик сумує: він загубив ключ від свого будиночка!','🐌',[['Віддати йому ключик','e2'],['Допомогти знайти ще й парасольку','e3']]],help:['Мурашка дякує і йде з тобою. Разом ви знаходите равлика.','🐜',[['Віддати равликові ключик','e2']]],e1:['Двері відчиняються. Усередині на тебе чекає равлик із чаєм!','🍵','Несподіваний гість'],e2:['Равлик усміхається і запрошує тебе в гості.','🐌','Друг біля криниці'],e3:['Разом ви знаходите парасольку якраз перед дощем.','☂️','Команда шукачів']}},
rocket:{title:'Картонна ракета',nodes:{s:['Ти збудував(-ла) ракету з коробок. Куди полетиш спочатку?','🚀',[['На Місяць','moon'],['На блакитну планету','planet']]],moon:['На Місяці дуже тихо. Ти бачиш блискучий камінчик.','🌙',[['Взяти на згадку','e1'],['Залишити й сфотографувати','e2']]],planet:['Тебе зустрічає привітний інопланетянин, який не розмовляє твоєю мовою.','👽',[['Помахати йому','friend'],['Намалювати йому сонце','friend']]],friend:['Інопланетянин сміється й показує свій зоряний сад.','✨',[['Разом посадити зірку','e3'],['Запросити його на Землю','e4']]],e1:['Камінчик щоночі світить у твоїй кімнаті.','🌙','Місячне світло'],e2:['Фото потрапляє до класного альбому.','📷','Дбайливий дослідник'],e3:['Ваша зірка сяє на небі щовечора.','⭐','Садівник зірок'],e4:['Наступного дня інопланетянин приземляється у твоєму дворі!','🛸','Несподіваний візит']}}}};
// Siluete: [tip, x, y, w, h, culoare] în procente din tablă.
const PICS={house:[['square',28,45,44,44,'#ffb703'],['triangle',22,14,56,32,'#e63946'],['rect',44,63,12,26,'#8a5a3b'],['square',32,52,10,10,'#bde0fe']],tree:[['circle',22,6,56,56,'#52b788'],['rect',43,58,14,34,'#8a5a3b'],['circle',50,14,16,16,'#95d5b2']],boat:[['hull',12,62,76,22,'#8a5a3b'],['triangle',40,10,34,48,'#f8f9fa'],['triangleL',18,24,20,26,'#e63946']],rocket:[['rect',40,28,20,44,'#f1f5f9'],['triangle',40,8,20,22,'#e63946'],['triangle',26,56,14,20,'#e63946'],['triangle',60,56,14,20,'#e63946'],['circle',44,36,12,12,'#4cc9f0'],['triangle',43,72,14,18,'#ffb703']],snowman:[['circle',24,46,52,48,'#f8f9fa'],['circle',32,14,36,34,'#f8f9fa'],['triangleL',49,28,14,8,'#fb8500'],['rect',34,4,32,12,'#343a40']],fish:[['oval',14,28,54,40,'#ffb703'],['triangleL',64,30,26,36,'#fb8500'],['circle',22,40,8,8,'#1f2a44']]};
const PATH={square:'<rect x="0" y="0" width="100" height="100"/>',rect:'<rect x="0" y="0" width="100" height="100"/>',triangle:'<polygon points="50,0 100,100 0,100"/>',triangleL:'<polygon points="0,50 100,0 100,100"/>',circle:'<ellipse cx="50" cy="50" rx="50" ry="50"/>',oval:'<ellipse cx="50" cy="50" rx="50" ry="50"/>',hull:'<polygon points="0,0 100,0 82,100 18,100"/>'};
Object.assign(D,window.gardenLangs?.discover||{});
const tx=(k,v={})=>String(D[lang]?.[k]??D.en[k]??k).replace(/\{(\w+)\}/g,(_,x)=>v[x]??'');
const E=(tag,text='',cls='')=>{const e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;return e},B=(text,fn,cls)=>{const b=E('button',text,cls);b.type='button';b.onclick=fn;return b};
const rnd=n=>Math.floor(Math.random()*n),pickOne=a=>a[rnd(a.length)];
const uid=()=>localStorage.getItem('garden_active')||'default',key=()=>`garden_discover_${uid()}`,read=()=>{try{return JSON.parse(localStorage.getItem(key()))||{}}catch{return {}}},save=d=>localStorage.setItem(key(),JSON.stringify(d));
const group=()=>{const a=ageOf(profile.dob);return a<=5?0:a<=8?1:2};const lv=g=>Math.min(3,Math.floor((read().wins?.[g]||0)/3));
const section=E('section','','card discover');section.id='discover';section.dataset.view='discover';$('app').insertBefore(section,$('birthday'));
let mode='letters',stage,status,taleId=null,node='s';
function win(g,msg){const d=read();d.wins=d.wins||{};d.wins[g]=(d.wins[g]||0)+1;save(d);status.textContent=msg||tx('well');gardenCelebrate(g)}
function wrong(g,msg){status.textContent=msg||tx('retry');gardenMiss(g)}
function listen(text){return B(tx('listen'),()=>gardenSpeak(text,true),'speak-btn')}
function optionsRow(opts,correct,g,onWin){const row=E('div','','discover-options');opts.forEach(o=>{const b=B(String(o),()=>{if(o===correct){row.querySelectorAll('button').forEach(x=>x.disabled=true);win(g);onWin?.();nextBtn()}else wrong(g)});row.append(b)});return row}
function nextBtn(){stage.append(B(tx('next'),()=>render(),'primary'))}
// ——— Litere
function letters(){const g=group(),L=lv('letters'),words=WORDS[lang]||WORDS.en,abc=[...(ABC[lang]||ABC.en)];const distract=(c,n)=>shuffle(abc.filter(x=>x!==c)).slice(0,n);
if(g===0){const [w]=pickOne(words),c=[...w][0];stage.append(E('h3',tx('findLetter')),E('p',tx('findLetterHelp',{l:c})),listen(tx('findLetterHelp',{l:c})),E('div',c,'discover-big'),optionsRow(shuffle([c,...distract(c,2+Math.min(2,L))]),c,'letters'))}
else if(g===1){const [w,icon]=pickOne(words),chars=[...w],c=chars[0];stage.append(E('h3',tx('firstSound')),E('p',tx('firstSoundHelp')),listen(tx('firstSoundHelp')+' '+w.toLowerCase()),E('div',icon,'discover-big'),E('div','? '+chars.slice(1).join(' '),'discover-word'),optionsRow(shuffle([c,...distract(c,2+Math.min(1,L))]),c,'letters'))}
else{const long=words.filter(([w])=>[...w].length>=4),[w,icon]=pickOne(long.length?long:words),chars=[...w],i=1+rnd(chars.length-2),c=chars[i];const shown=chars.map((x,j)=>j===i?'_':x).join(' ');stage.append(E('h3',tx('missing')),E('p',tx('missingHelp')),listen(tx('missingHelp')),E('div',icon,'discover-big'),E('div',shown,'discover-word'),optionsRow(shuffle([c,...distract(c,3)]),c,'letters'))}}
// ——— Ceasul
function clockSvg(h,m){const hr=((h%12)+m/60)*30,mn=m*6;let ticks='';for(let i=0;i<12;i++){const a=i*30*Math.PI/180,x1=50+42*Math.sin(a),y1=50-42*Math.cos(a),x2=50+46*Math.sin(a),y2=50-46*Math.cos(a),nx=50+35*Math.sin(a),ny=50-35*Math.cos(a)+3.5;ticks+=`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="#1f2a44" stroke-width="2"/><text x="${nx}" y="${ny}" font-size="10" text-anchor="middle" fill="#1f2a44" font-weight="700">${i||12}</text>`}const w=E('div','','clock-wrap');w.setAttribute('role','img');w.setAttribute('aria-label',tx('clockLabel'));w.innerHTML=`<svg viewBox="0 0 100 100" width="200" height="200"><circle cx="50" cy="50" r="48" fill="#fffdf5" stroke="#ffc978" stroke-width="4"/>${ticks}<line x1="50" y1="50" x2="${50+22*Math.sin(hr*Math.PI/180)}" y2="${50-22*Math.cos(hr*Math.PI/180)}" stroke="#e63946" stroke-width="5" stroke-linecap="round"/><line x1="50" y1="50" x2="${50+33*Math.sin(mn*Math.PI/180)}" y2="${50-33*Math.cos(mn*Math.PI/180)}" stroke="#1f2a44" stroke-width="3" stroke-linecap="round"/><circle cx="50" cy="50" r="3" fill="#1f2a44"/></svg>`;return w}
const fmtTime=(h,m)=>`${((h-1+12)%12)+1}:${String(m).padStart(2,'0')}`;
function clock(){const g=group(),L=lv('clock');let h=1+rnd(12),m=g===0?0:g===1?pickOne(L<1?[0,30]:[0,15,30,45]):5*rnd(12);const later=g===2&&L>=1&&Math.random()<.5,add=later?pickOne([15,30,45,60]):0;const tm=h*60+m+add,ah=Math.floor(tm/60),am=tm%60,correct=fmtTime(ah,am);const set=new Set([correct]);const cands=[fmtTime(ah+1,am),fmtTime(ah-1,am),fmtTime(ah,(am+30)%60),fmtTime(Math.max(1,Math.round(am/5))||12,((ah%12)*5)%60),fmtTime(ah,(am+15)%60)];for(const c of shuffle(cands)){if(set.size>=(g===0?3:4))break;set.add(c)}stage.append(E('h3',later?tx('clockLater',{m:add}):tx('clockQ')),listen(later?tx('clockLater',{m:add}):tx('clockQ')),clockSvg(h,m),optionsRow(shuffle([...set]),correct,'clock'))}
// ——— Bani
function moneyPiece(v){const c=CUR[lang]||CUR.en,note=c.note(v),e=E('span',c.fmt(v),note?'money note':'money coin');e.dataset.v=v;return e}
function money(){const g=group(),L=lv('money'),c=CUR[lang]||CUR.en,P=c.pieces;const wallet=E('div','','wallet');wallet.setAttribute('aria-label',tx('wallet'));
if(g===0){const n=2+rnd(3+L);for(let i=0;i<n;i++)wallet.append(moneyPiece(P[0]));stage.append(E('h3',tx('countPieces')),listen(tx('countPieces')),wallet,optionsRow(shuffle([...new Set([n,n+1,Math.max(1,n-1),n+2])].slice(0,3)),n,'money'))}
else if(g===1){const k=2+rnd(2+Math.min(1,L)),vals=Array.from({length:k},()=>pickOne(P.slice(0,L>=2?4:3)));vals.forEach(v=>wallet.append(moneyPiece(v)));const s=vals.reduce((a,b)=>a+b,0),u=P[0];stage.append(E('h3',tx('total')),listen(tx('total')),wallet,optionsRow(shuffle([...new Set([s,s+u,Math.max(u,s-u),s+P[1]])].slice(0,4).map(c.fmt)),c.fmt(s),'money'))}
else{const vals=Array.from({length:3},()=>pickOne(P)),s=vals.reduce((a,b)=>a+b,0),u=P[0];vals.forEach(v=>wallet.append(moneyPiece(v)));if(Math.random()<.5){const cheap=u*(1+rnd(Math.max(1,s/u-1))),items=shuffle([...ITEMS]).slice(0,3),prices=[cheap,s+u*(1+rnd(3)),s+u*(3+rnd(4))];const row=E('div','','shop');items.forEach((it,i)=>row.append(E('span',`${it} ${c.fmt(prices[i])}`,'price')));const labels=items.map((it,i)=>`${it} ${c.fmt(prices[i])}`);stage.append(E('h3',tx('afford',{s:c.fmt(s)})),listen(tx('afford',{s:c.fmt(s)})),wallet,optionsRow(shuffle([...labels]),labels[0],'money'))}else{const p=u*(1+rnd(Math.max(1,s/u-1))),ch=s-p;stage.append(E('h3',tx('change',{s:c.fmt(s),p:c.fmt(p)})),listen(tx('change',{s:c.fmt(s),p:c.fmt(p)})),wallet,optionsRow(shuffle([...new Set([ch,ch+u,Math.max(0,ch-u),p])]).map(c.fmt),c.fmt(ch),'money'))}}}
// ——— Puzzle pe siluetă (drag & drop + atingere)
function shapeSvg(type,fill,outline){return `<svg viewBox="0 0 100 100" preserveAspectRatio="none" width="100%" height="100%"><g fill="${outline?'rgba(255,255,255,.08)':fill}" ${outline?'stroke="currentColor" stroke-width="3" stroke-dasharray="7 5" vector-effect="non-scaling-stroke"':''}>${PATH[type].replace('/>',' vector-effect="non-scaling-stroke"/>')}</g></svg>`}
function puzzle(){const g=group(),names=Object.keys(PICS),name=pickOne(g===0?['house','tree','fish']:names),parts=PICS[name].slice(0,g===0?3:g===1?4:6);const extraPiece=g===2?pickOne([['circle',0,0,18,18,'#c77dff'],['square',0,0,16,16,'#06d6a0']]):null;let selected=null,left=parts.length;
stage.append(E('h3',tx('puzzle')),E('p',tx('puzzleHelp')+(extraPiece?' '+tx('extra'):'')),listen(tx('puzzleHelp')));const wrap=E('div','','puzzle-wrap'),boardEl=E('div','','puzzle-board'),tray=E('div','','puzzle-tray');wrap.append(boardEl,tray);stage.append(wrap);
const keyOf=p=>`${p[0]}:${p[3]}x${p[4]}`;parts.forEach((p,i)=>{const [type,x,y,w,h]=p,slot=B('',()=>place(slot),'puzzle-slot');slot.dataset.key=keyOf(p);slot.style.cssText=`left:${x}%;top:${y}%;width:${w}%;height:${h}%;z-index:${i+1}`;slot.innerHTML=shapeSvg(type,'',true);slot.setAttribute('aria-label',tx('slot',{shape:tx(type)}));boardEl.append(slot)});
const pieces=shuffle([...parts,...(extraPiece?[extraPiece]:[])]);pieces.forEach(p=>{const [type,,,w,h,color]=p,pc=B('',()=>{select(pc)},'puzzle-piece');pc.dataset.key=keyOf(p);pc.dataset.color=color;pc.style.width=w+'%';pc.style.aspectRatio=`${w}/${h}`;pc.innerHTML=shapeSvg(type,color);pc.setAttribute('aria-label',tx('piece',{shape:tx(type)}));drag(pc);tray.append(pc)});
function select(pc){if(pc.disabled)return;tray.querySelectorAll('.puzzle-piece').forEach(x=>x.setAttribute('aria-pressed',x===pc));selected=pc;status.textContent=tx('selected',{shape:pc.getAttribute('aria-label').split(': ').pop()})}
function place(slot,pc=selected){if(!pc||slot.classList.contains('filled'))return;if(pc.dataset.key!==slot.dataset.key){wrong('puzzle',tx('pieceWrong'));pc.classList.remove('shake');void pc.offsetWidth;pc.classList.add('shake');return}slot.classList.add('filled');slot.innerHTML=shapeSvg(slot.dataset.key.split(':')[0],pc.dataset.color);slot.disabled=true;pc.remove();selected=null;status.textContent='';window.gardenSound?.('pop');if(--left===0){tray.replaceChildren();win('puzzle',tx('puzzleDone',{name:tx(name)}));nextBtn()}}
function drag(pc){pc.addEventListener('pointerdown',e=>{if(e.button!==0)return;const r=pc.getBoundingClientRect(),ox=e.clientX-r.left,oy=e.clientY-r.top;let moved=false,ghost=null;const onMove=ev=>{if(!moved&&Math.hypot(ev.clientX-e.clientX,ev.clientY-e.clientY)<6)return;if(!moved){moved=true;ghost=pc.cloneNode(true);ghost.classList.add('puzzle-ghost');ghost.style.width=r.width+'px';ghost.style.height=r.height+'px';document.body.append(ghost);pc.style.opacity=.3}ghost.style.transform=`translate(${ev.clientX-ox}px,${ev.clientY-oy}px)`};const onUp=ev=>{removeEventListener('pointermove',onMove);removeEventListener('pointerup',onUp);removeEventListener('pointercancel',onUp);pc.style.opacity='';if(!moved)return;ghost.remove();const cx=ev.clientX-ox+r.width/2,cy=ev.clientY-oy+r.height/2;const slots=[...boardEl.querySelectorAll('.puzzle-slot:not(.filled)')].filter(s=>{const b=s.getBoundingClientRect();return cx>=b.left&&cx<=b.right&&cy>=b.top&&cy<=b.bottom});if(slots.length){const same=slots.find(s=>s.dataset.key===pc.dataset.key);place(same||slots[slots.length-1],pc)}pc.dataset.dragged='1';setTimeout(()=>delete pc.dataset.dragged,0)};addEventListener('pointermove',onMove);addEventListener('pointerup',onUp);addEventListener('pointercancel',onUp)});pc.addEventListener('click',e=>{if(pc.dataset.dragged){e.stopImmediatePropagation()}},true)}}
// ——— Povești
function tale(){const set=TALES[lang]||TALES.en,d=read(),found=d.endings||[],total=Object.values(set).reduce((a,s)=>a+Object.keys(s.nodes).filter(k=>k.startsWith('e')).length,0);if(!taleId){stage.append(E('h3',tx('tale')),E('p',tx('chooseStory')),E('p',tx('endings',{n:found.length,t:total}),'progress'));const row=E('div','','discover-options');Object.entries(set).forEach(([id,s])=>row.append(B(`${s.nodes.s[1]} ${s.title}`,()=>{taleId=id;node='s';render()})));stage.append(row);return}
const s=set[taleId],n=s.nodes[node],isEnd=node.startsWith('e');stage.append(E('div',s.title,'eyebrow'),E('div',n[1],'discover-big'),E('p',n[0],'tale-text'),listen(n[0]));if(!isEnd){const row=E('div','','tale-choices');n[2].forEach(([label,to])=>row.append(B(label,()=>{node=to;render()})));stage.append(row)}else{const id=`${taleId}:${node}`,dd=read();dd.endings=[...new Set([...(dd.endings||[]),id])];save(dd);stage.append(E('p',`${tx('theEnd')}: ${n[2]}`,'tale-end'));if(!found.includes(id))win('tale',`${tx('theEnd')}: ${n[2]}`);else status.textContent=tx('endings',{n:dd.endings.length,t:total});stage.append(B(tx('again'),()=>{node='s';render()}),B(tx('other'),()=>{taleId=null;render()}))}}
function render(){if(!profile||$('app').hidden)return;section.replaceChildren(E('h2',tx('title')),E('p',tx('intro')));const tabs=E('div','','learning-tabs');[['letters','🔤'],['clock','🕒'],['money','💰'],['puzzle','🧩'],['tale','📖']].forEach(([k,icon])=>{const b=B(`${icon} ${tx(k)}`,()=>{mode=k;if(k!=='tale')taleId=null;render()});b.setAttribute('aria-pressed',mode===k);tabs.append(b)});section.append(tabs);if(mode!=='tale')section.append(E('p',`${tx('level')} ${lv(mode)+1}`,'learning-level'));stage=E('div','','learning-stage discover-stage');section.append(stage);status=E('div','','learning-feedback');status.setAttribute('role','status');status.setAttribute('aria-live','polite');({letters,clock,money,puzzle,tale})[mode]();stage.append(status)}
gardenOn(()=>{taleId=null;render()});if(profile)render();
})();
