// Grădina Curioasă — „Scrie-ți părerea”, în zona pentru părinți (după poarta pentru adulți).
// Trimite la Worker-ul din feedback-worker/, care creează un Issue de moderat. Nu se cer date de contact.
(()=>{
// Adresa Worker-ului Cloudflare, după activare (vezi feedback-worker/README.md).
const ENDPOINT=window.GARDEN_FEEDBACK_ENDPOINT||'';
const F={
ro:{title:'Scrie-ți părerea',intro:'Cum ți se pare Grădina Curioasă? Părerea ta poate apărea în portofoliul meu, după ce o citesc.',text:'Părerea ta',name:'Cum semnezi (opțional)',namePh:'ex.: Ana, mama lui R.',nameHint:'Te rog să nu scrii numele complet al copilului.',role:'Ești',roles:{parent:'Părinte',teacher:'Profesor',developer:'Dezvoltator',other:'Altceva'},rating:'Câte stele îi dai?',stars:'{n} din 5 stele',consent:'Sunt de acord ca părerea mea să fie publicată în portofoliu.',privacy:'Nu salvăm e-mail, telefon sau alte date de contact.',send:'Trimite părerea',sending:'Se trimite…',thanks:'Mulțumesc! Părerea ta va apărea în portofoliu după ce o citesc.',short:'Scrie măcar câteva cuvinte (minimum 10 caractere).',consentErr:'Bifează acordul pentru publicare.',contact:'Te rog să nu incluzi linkuri, e-mailuri sau numere de telefon.',fast:'Mai citește o dată și trimite din nou.',rate:'Ai trimis deja câteva păreri. Încearcă din nou mai târziu.',net:'Nu s-a putut trimite acum. Verifică internetul și încearcă din nou.',soon:'Formularul de păreri se activează în curând.',count:'{n}/600'},
en:{title:'Share your opinion',intro:'What do you think of Curious Garden? Your opinion may appear in my portfolio after I read it.',text:'Your opinion',name:'How you sign (optional)',namePh:'e.g. Ana, R.’s mum',nameHint:'Please don’t write your child’s full name.',role:'You are',roles:{parent:'Parent',teacher:'Teacher',developer:'Developer',other:'Other'},rating:'How many stars?',stars:'{n} of 5 stars',consent:'I agree that my opinion may be published in the portfolio.',privacy:'No e-mail, phone or other contact details are stored.',send:'Send opinion',sending:'Sending…',thanks:'Thank you! Your opinion will appear in the portfolio after I read it.',short:'Please write a few words (at least 10 characters).',consentErr:'Please tick the publication consent.',contact:'Please don’t include links, e-mails or phone numbers.',fast:'Read it once more and send again.',rate:'You have already sent a few opinions. Please try again later.',net:'Could not send right now. Check your connection and try again.',soon:'The feedback form will be switched on soon.',count:'{n}/600'},
hu:{title:'Írd meg a véleményed',intro:'Hogy tetszik a Kíváncsi Kert? A véleményed megjelenhet a portfóliómban, miután elolvastam.',text:'A véleményed',name:'Aláírás (nem kötelező)',namePh:'pl.: Anna, R. anyukája',nameHint:'Kérlek, ne írd ki a gyermek teljes nevét.',role:'Te vagy',roles:{parent:'Szülő',teacher:'Tanár',developer:'Fejlesztő',other:'Más'},rating:'Hány csillagot adsz?',stars:'{n} / 5 csillag',consent:'Hozzájárulok, hogy a véleményem megjelenjen a portfólióban.',privacy:'Nem tárolunk e-mailt, telefonszámot vagy más elérhetőséget.',send:'Vélemény küldése',sending:'Küldés…',thanks:'Köszönöm! A véleményed megjelenik a portfólióban, miután elolvastam.',short:'Írj legalább pár szót (minimum 10 karakter).',consentErr:'Jelöld be a közzétételi hozzájárulást.',contact:'Kérlek, ne írj linket, e-mail-címet vagy telefonszámot.',fast:'Olvasd át még egyszer, és küldd el újra.',rate:'Már küldtél néhány véleményt. Próbáld újra később.',net:'Most nem sikerült elküldeni. Ellenőrizd az internetet, és próbáld újra.',soon:'A véleményűrlap hamarosan elérhető lesz.',count:'{n}/600'},
uk:{title:'Напиши свою думку',intro:'Як тобі Цікавий сад? Твоя думка може з’явитися в моєму портфоліо після того, як я її прочитаю.',text:'Твоя думка',name:'Підпис (необов’язково)',namePh:'напр.: Анна, мама Р.',nameHint:'Будь ласка, не пиши повне ім’я дитини.',role:'Ти',roles:{parent:'Батьки',teacher:'Вчитель',developer:'Розробник',other:'Інше'},rating:'Скільки зірок?',stars:'{n} з 5 зірок',consent:'Я погоджуюся, що мою думку можна опублікувати в портфоліо.',privacy:'Ми не зберігаємо e-mail, телефон чи інші контакти.',send:'Надіслати',sending:'Надсилаємо…',thanks:'Дякую! Твоя думка з’явиться в портфоліо, щойно я її прочитаю.',short:'Напиши хоча б кілька слів (щонайменше 10 символів).',consentErr:'Познач згоду на публікацію.',contact:'Будь ласка, не додавай посилань, e-mail чи номерів телефону.',fast:'Перечитай ще раз і надішли знову.',rate:'Ти вже надіслав(-ла) кілька думок. Спробуй пізніше.',net:'Зараз не вдалося надіслати. Перевір інтернет і спробуй ще раз.',soon:'Форма відгуків скоро запрацює.',count:'{n}/600'}};
const tx=(k,v={})=>String(F[lang]?.[k]??F.en[k]??k).replace(/\{(\w+)\}/g,(_,x)=>v[x]??'');const roles=()=>F[lang]?.roles||F.en.roles;
const E=(tag,text='',cls='')=>{const e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;return e};
const hasContact=t=>/https?:\/\/|www\.|\b[\w.+-]+@[\w-]+\.[\w.]+\b|(?:\+?\d[\s.-]?){8,}/i.test(t);
function form(){const box=E('div','','feedback-form'),opened=Date.now();let rating=0;
box.append(E('p',tx('intro')));
const ta=E('textarea');ta.id='fbText';ta.maxLength=600;ta.rows=4;const tl=E('label',tx('text'));tl.htmlFor='fbText';const cnt=E('span',tx('count',{n:0}),'small fb-count');ta.oninput=()=>cnt.textContent=tx('count',{n:ta.value.length});
const nm=E('input');nm.id='fbName';nm.maxLength=60;nm.placeholder=tx('namePh');nm.autocomplete='off';const nl=E('label',tx('name'));nl.htmlFor='fbName';const nh=E('span',tx('nameHint'),'small');
const rs=E('select');rs.id='fbRole';Object.entries(roles()).forEach(([k,v])=>{const o=E('option',v);o.value=k;rs.append(o)});const rl=E('label',tx('role'));rl.htmlFor='fbRole';
const stars=E('div','','fb-stars');stars.setAttribute('role','radiogroup');stars.setAttribute('aria-label',tx('rating'));const paint=()=>stars.querySelectorAll('button').forEach((b,i)=>{b.textContent=i<rating?'★':'☆';b.setAttribute('aria-checked',i+1===rating)});for(let i=1;i<=5;i++){const b=E('button','☆');b.type='button';b.setAttribute('role','radio');b.setAttribute('aria-label',tx('stars',{n:i}));b.onclick=()=>{rating=i;paint()};stars.append(b)}
const trap=E('input');trap.type='text';trap.name='website';trap.tabIndex=-1;trap.autocomplete='off';trap.className='fb-trap';trap.setAttribute('aria-hidden','true');
const cb=E('input');cb.type='checkbox';cb.id='fbConsent';const cl=E('label','','fb-consent');cl.htmlFor='fbConsent';cl.append(cb,E('span',tx('consent')));
const msg=E('p','','fb-status');msg.setAttribute('role','status');msg.setAttribute('aria-live','polite');
const send=E('button',tx('send'),'primary');send.type='button';
box.append(tl,ta,cnt,nl,nm,nh,rl,rs,E('span',tx('rating'),'fb-label'),stars,trap,cl,E('p',tx('privacy'),'small'),send,msg);
if(!ENDPOINT){send.disabled=true;msg.textContent=tx('soon')}
send.onclick=async()=>{const text=ta.value.trim(),name=nm.value.trim();if(text.length<10){msg.textContent=tx('short');ta.focus();return}if(hasContact(text)||hasContact(name)){msg.textContent=tx('contact');return}if(!cb.checked){msg.textContent=tx('consentErr');cb.focus();return}
send.disabled=true;msg.textContent=tx('sending');try{const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,name,role:rs.value,rating,lang,project:'curious-garden',consent:true,elapsed:Date.now()-opened,website:trap.value})});const j=await r.json().catch(()=>({}));if(r.ok&&j.ok){msg.textContent=tx('thanks');ta.value='';nm.value='';cb.checked=false;rating=0;paint();ta.oninput();window.gardenSound?.('badge');return}msg.textContent=tx({short:'short',consent:'consentErr',contact:'contact',fast:'fast',rate:'rate'}[j.error]||'net')}catch{msg.textContent=tx('net')}finally{send.disabled=!ENDPOINT}};
return box}
const prev=window.gardenSettingsExtra;window.gardenSettingsExtra=(card,layer)=>{prev?.(card,layer);const d=E('details','','settings-section feedback-section');d.append(E('summary','💬 '+tx('title')),form());card.append(d)};
})();
