// Grădina Curioasă — festivaluri de sărbători: câte o provocare nouă în fiecare zi a sărbătorii
// (Mărțișor, Paște, Ziua Pământului, 1 Iunie, prima zi de școală, Halloween) și calendarul de Advent de Crăciun (1–24 decembrie).
(()=>{
const LANGS=['ro','en','hu','uk'],L=a=>a[Math.max(0,LANGS.indexOf(lang))]??a[1],fmt=(s,v={})=>String(s).replace(/\{(\w+)\}/g,(_,x)=>v[x]??'');
const E=(t,x='',c='')=>{const e=document.createElement(t);e.textContent=x;if(c)e.className=c;return e},B=(x,fn,c)=>{const b=E('button',x,c);b.type='button';b.onclick=fn;return b};
const NS='http://www.w3.org/2000/svg',S=(t,a={})=>{const e=document.createElementNS(NS,t);for(const k in a)e.setAttribute(k,a[k]);return e};
const uid=()=>localStorage.getItem('garden_active')||'default',age=()=>ageOf(profile.dob),rand=n=>Math.floor(Math.random()*n),pick=a=>a[rand(a.length)],mix=a=>shuffle([...a]);
const U={
day:['Ziua {n}','Day {n}','{n}. nap','День {n}'],dayOf:['Ziua {d} din {n}','Day {d} of {n}','{d}. nap / {n}','День {d} з {n}'],opens:['Se deschide {when}','Opens {when}','Nyílik: {when}','Відкриється {when}'],tomorrow:['mâine','tomorrow','holnap','завтра'],inDays:['peste {n} zile','in {n} days','{n} nap múlva','через {n} дн.'],
endsIn:['Se încheie peste {n} zile.','Ends in {n} days.','{n} nap múlva véget ér.','Завершиться через {n} дн.'],preview:['👀 Previzualizare pentru adulți: festivalul se deschide doar în perioada sărbătorii.','👀 Adult preview: the festival only opens during the holiday.','👀 Felnőtt előnézet: a fesztivál csak az ünnep idején nyílik meg.','👀 Попередній перегляд для дорослих: фестиваль відкривається лише під час свята.'],
back:['← Înapoi la festival','← Back to the festival','← Vissza a fesztiválra','← Назад до фестивалю'],reward:['🎁 Ai primit: {r}','🎁 You got: {r}','🎁 Ezt kaptad: {r}','🎁 Ти отримав(-ла): {r}'],collection:['Colecția festivalului','Festival collection','A fesztivál gyűjteménye','Колекція фестивалю'],
allDone:['Ai terminat toate zilele festivalului! 🎉','You finished every day of the festival! 🎉','A fesztivál minden napját teljesítetted! 🎉','Ти пройшов(-ла) всі дні фестивалю! 🎉'],
homeText:['{icon} {title}: ziua {d} din {n}. Te așteaptă o provocare nouă!','{icon} {title}: day {d} of {n}. A new challenge is waiting!','{icon} {title}: {d}. nap / {n}. Új feladat vár!','{icon} {title}: день {d} з {n}. На тебе чекає нове завдання!'],
homeAdvent:['🎄 Calendarul de Advent: fereastra {d} te așteaptă!','🎄 Advent calendar: window {d} is waiting for you!','🎄 Adventi naptár: a(z) {d}. ablak vár rád!','🎄 Адвент-календар: віконце {d} чекає на тебе!'],homeXmas:['🎄 Crăciun fericit! Bradul tău are {n} globuri.','🎄 Merry Christmas! Your tree has {n} ornaments.','🎄 Boldog karácsonyt! A fádon {n} dísz van.','🎄 Веселого Різдва! На твоїй ялинці прикрас: {n}.'],
enter:['🎪 Intră la festival','🎪 Go to the festival','🎪 Irány a fesztivál','🎪 До фестивалю'],openAdvent:['🎄 Deschide calendarul','🎄 Open the calendar','🎄 Nyisd ki a naptárat','🎄 Відкрити календар'],cardBtn:['🎪 Festivalul','🎪 Festival','🎪 Fesztivál','🎪 Фестиваль'],cardAdvent:['🎄 Calendarul de Advent','🎄 Advent calendar','🎄 Adventi naptár','🎄 Адвент-календар'],
doorLocked:['Fereastra {n} se deschide pe {n} decembrie.','Window {n} opens on {n} December.','A(z) {n}. ablak december {n}-én nyílik.','Віконце {n} відкриється {n} грудня.'],door:['Fereastra {n}','Window {n}','{n}. ablak','Віконце {n}'],tree:['Bradul meu','My tree','Az én fám','Моя ялинка'],
adventHelp:['Deschide în fiecare zi o fereastră, rezolvă provocarea și primești un glob pentru brad.','Open one window each day, solve the challenge and get an ornament for your tree.','Nyiss ki minden nap egy ablakot, oldd meg a feladatot, és kapsz egy díszt a fádra.','Щодня відкривай віконце, виконуй завдання й отримуй прикрасу для ялинки.'],
merry:['Crăciun fericit! Ai deschis toate cele 24 de ferestre! 🎄','Merry Christmas! You opened all 24 windows! 🎄','Boldog karácsonyt! Mind a 24 ablakot kinyitottad! 🎄','Веселого Різдва! Ти відкрив(-ла) всі 24 віконця! 🎄'],
festHelp:['În fiecare zi a sărbătorii se deschide o provocare nouă. Zilele pierdute rămân deschise până la final.','Each day of the holiday opens a new challenge. Missed days stay open until the end.','Az ünnep minden napján új feladat nyílik. A kihagyott napok a végéig nyitva maradnak.','Щодня під час свята відкривається нове завдання. Пропущені дні лишаються відкритими до кінця.'],
findHelp:['Găsește toate {icon}. Mai sunt {n}.','Find every {icon}. {n} left.','Keresd meg az összes {icon}. Még {n}.','Знайди всі {icon}. Залишилось {n}.'],findWrong:['Acesta nu e {icon}. Mai caută!','That’s not {icon}. Keep looking!','Ez nem {icon}. Keress tovább!','Це не {icon}. Шукай далі!'],
patternHelp:['Continuă șirul: ce urmează?','Continue the pattern: what comes next?','Folytasd a sort: mi jön?','Продовж ряд: що далі?'],patternWrong:['Uită-te din nou la șir.','Look at the pattern again.','Nézd meg újra a sort.','Поглянь на ряд ще раз.'],
memoryHelp:['Întoarce câte două cărți și găsește perechile.','Turn over two cards at a time and find the pairs.','Fordíts meg két kártyát, és találd meg a párokat.','Перевертай по дві картки й шукай пари.'],moves:['Mutări: {n}','Moves: {n}','Lépések: {n}','Ходи: {n}'],card:['Carte {n}','Card {n}','{n}. kártya','Картка {n}'],
cYoung:['Câte {icon} vezi?','How many {icon} can you see?','Hány {icon} látsz?','Скільки {icon} бачиш?'],cMid:['{a} × {i1} și {b} × {i2}. Câte sunt în total?','{a} × {i1} and {b} × {i2}. How many altogether?','{a} × {i1} és {b} × {i2}. Hány összesen?','{a} × {i1} і {b} × {i2}. Скільки разом?'],
cOld1:['În fiecare coșuleț sunt {n} × {icon}. Câte sunt în {k} coșulețe?','Each basket holds {n} × {icon}. How many in {k} baskets?','Minden kosárkában {n} × {icon} van. Hány van {k} kosárkában?','У кожному кошику {n} × {icon}. Скільки в {k} кошиках?'],cOld2:['Împarte {t} × {icon} în mod egal în {k} coșulețe. Câte pui în fiecare?','Share {t} × {icon} equally between {k} baskets. How many in each?','Ossz szét {t} × {icon} egyenlően {k} kosárkába. Mennyi jut egybe?','Розклади {t} × {icon} порівну в {k} кошики. Скільки в кожному?'],
good:['Corect! 🎉','Correct! 🎉','Helyes! 🎉','Правильно! 🎉'],nearly:['Aproape! Mai încearcă.','Nearly! Try again.','Majdnem! Próbáld újra.','Майже! Спробуй ще.'],
decHelp:['Alege culoarea și modelul, apoi atinge desenul ca să pui abțibilduri. Pune cel puțin 3.','Pick a colour and a pattern, then tap the picture to add stickers. Add at least 3.','Válassz színt és mintát, aztán érintsd meg a képet, hogy matricákat tegyél rá. Legalább 3-at.','Обери колір і візерунок, потім торкайся малюнка, щоб додати наліпки. Щонайменше 3.'],
face:['Fața dovleacului','Pumpkin face','A tök arca','Обличчя гарбуза'],faces:[['Vesel','Happy','Vidám','Весела'],['Năzdrăvan','Silly','Huncut','Пустотлива'],['Mirat','Surprised','Meglepett','Здивована']],
color:['Culoare','Colour','Szín','Колір'],pattern:['Model','Pattern','Minta','Візерунок'],patterns:[['simplu','plain','sima','без візерунка'],['dungi','stripes','csíkos','смужки'],['buline','dots','pöttyös','горошок']],stickers:['Abțibilduri','Stickers','Matricák','Наліпки'],
decMore:['Mai pune {n} abțibilduri.','Add {n} more stickers.','Tégy rá még {n} matricát.','Додай ще {n} наліпки.'],decDone:['✅ Gata','✅ Done','✅ Kész','✅ Готово'],decUndo:['↩️ Scoate ultimul','↩️ Remove the last one','↩️ Az utolsót le','↩️ Прибрати останню'],album:['Albumul sărbătorii','Holiday album','Ünnepi album','Святковий альбом'],
bases:{pumpkin:['Dovleacul tău','Your pumpkin','A tököd','Твій гарбуз'],egg:['Oul tău','Your egg','A tojásod','Твоє яйце'],tree:['Bradul tău','Your tree','A fád','Твоя ялинка'],card:['Mărțișorul tău','Your mărțișor','A márciskád','Твій мерцішор'],globe:['Planeta ta','Your planet','A bolygód','Твоя планета'],kite:['Zmeul tău','Your kite','A sárkányod','Твій повітряний змій'],backpack:['Ghiozdanul tău','Your school bag','Az iskolatáskád','Твій рюкзак']}};
const u=(k,v)=>fmt(L(U[k]),v);
const H={
martisor:{icon:'🎀',title:['Săptămâna Mărțișorului','Mărțișor week','Márciska-hét','Тиждень Мерцішора'],sym:['🎀','🌷','🌸','🐞','🍀','🌼'],base:'card',tint:'#e63946',stickers:['🍀','🐞','🌷','🌸','⭐','❤️','🌼','🦋']},
easter:{icon:'🥚',title:['Festivalul de Paște','Easter festival','Húsvéti fesztivál','Великодній фестиваль'],sym:['🥚','🐣','🐰','🌷','🧺','🌼'],base:'egg',tint:'#f783ac',stickers:['🐣','🌷','🌼','⭐','💛','🐰','🦋','🌸']},
earth:{icon:'🌍',title:['Zilele Pământului','Earth Days','A Föld napjai','Дні Землі'],sym:['🌍','🌳','♻️','💧','🌱','🐝'],base:'globe',tint:'#4dabf7',stickers:['🌳','🌱','🐝','🦋','🐟','🌻','💧','♻️']},
children:{icon:'🎈',title:['Zilele copiilor','Children’s Days','Gyereknapok','Дні дітей'],sym:['🎈','🪁','🍭','🧸','⚽','🎠'],base:'kite',tint:'#ffd43b',stickers:['⭐','🎈','🌈','☀️','🦋','🍭','🧸','⚽']},
school:{icon:'🎒',title:['Primele zile de școală','Back-to-school days','Az első iskolai napok','Перші шкільні дні'],sym:['🎒','📚','✏️','📏','🖍️','🍎'],base:'backpack',tint:'#4dabf7',stickers:['⭐','✏️','📚','🍎','🌈','⚽','🦖','🚀']},
halloween:{icon:'🎃',title:['Festivalul de Halloween','Halloween festival','Halloween-fesztivál','Фестиваль Геловіну'],sym:['🎃','👻','🦇','🕸️','🍬','🌙'],base:'pumpkin',tint:'#f4892b',stickers:['🦇','🕸️','🍬','⭐','🌙','👻','🍭','🕯️']},
christmas:{icon:'🎄',title:['Calendarul de Advent','Advent calendar','Adventi naptár','Адвент-календар'],sym:['🎄','⭐','🎁','❄️','🔔','🦌'],base:'tree',tint:'#2f9e44',stickers:['⭐','🔔','🎀','❄️','🍬','🎁','🕯️','🍭']}};
const ORN=['⭐','🔔','🎁','❄️','🦌','🍪','🧦','🕯️','🎀','🍬','☃️','🍭','🧸','🎅','🛷','🌟','🎶','🧤','🥛','🍊','🍩','🎺','🪅','👼'];
const TYPES=['find','pattern','memory','count','decorate'];
const COLORS=['#f4892b','#e63946','#f783ac','#9775fa','#4dabf7','#69db7c','#ffd43b','#f8f9fa'];
const key=(id,y)=>`garden_festival_${uid()}_${id}_${y}`,read=(id,y)=>{try{return JSON.parse(localStorage.getItem(key(id,y)))||{}}catch{return {}}},save=(id,y,d)=>{try{localStorage.setItem(key(id,y),JSON.stringify(d))}catch{}};
const DAY=864e5,today=()=>{const n=new Date();return new Date(n.getFullYear(),n.getMonth(),n.getDate())};
// Fereastra sărbătorii în care suntem acum sau următoarea (pentru previzualizare)
function current(id){const n=new Date(),y=n.getFullYear();const ws=[y-1,y,y+1].map(v=>[v,...eventWindow(id,v)]);return ws.find(([,a,b])=>n>=a&&n<b)||ws.find(([,a])=>a>n)}
function plan(id){const [year,a,b]=current(id),open=new Date()>=a&&new Date()<b;if(id==='christmas'){const start=new Date(a.getFullYear(),11,1);return {id,year:start.getFullYear(),open,start,end:b,days:24,unlock:i=>new Date(start.getFullYear(),11,i+1)}}const start=new Date(a.getFullYear(),a.getMonth(),a.getDate()),days=Math.max(1,Math.round((b-start)/DAY));return {id,year:start.getFullYear(),open,start,end:b,days,unlock:i=>new Date(start.getTime()+i*DAY)}}
function active(){for(const id of Object.keys(H)){const p=plan(id);if(p.open){const t=today();let d=0;for(let i=0;i<p.days;i++)if(p.unlock(i)<=t)d=i+1;return {...p,day:Math.max(1,d)}}}return null}
const section=E('section','','card studio festival');section.id='festival';section.dataset.view='festival';$('app').insertBefore(section,$('birthday'));
let fid=null,playing=null,previewing=false,stage,status;
const say=(m,good=true)=>{status.textContent=m;status.classList.toggle('bad',!good)};
const help=t=>{stage.append(E('p',t,'studio-help'));if(age()<=6)stage.append(B(L(['🔊 Ascultă','🔊 Listen','🔊 Meghallgatom','🔊 Послухати']),()=>gardenSpeak(t,true),'speak-btn'))};
function whenText(d){const n=Math.round((d-today())/DAY);return n<=1?u('tomorrow'):u('inDays',{n})}
function rewardOf(id,i){return id==='christmas'?ORN[i%ORN.length]:H[id].stickers[i%H[id].stickers.length]}
function render(){if(!profile||$('app').hidden||!fid)return;const h=H[fid],p=plan(fid),d=read(fid,p.year),done=d.done||{};section.replaceChildren();section.dataset.holiday=fid;
const head=E('div','','versus-head');head.append(E('span',h.icon,'craft-head-icon'),E('div'));head.lastChild.append(E('h2',L(h.title)),E('p',fid==='christmas'?u('adventHelp'):u('festHelp')));section.append(head);
if(!p.open)section.append(E('p',u('preview'),'party-locked'));else section.append(E('p',u('endsIn',{n:Math.max(1,Math.ceil((p.end-new Date())/DAY))}),'small'));
stage=E('div','','learning-stage studio-stage fest-stage');status=E('p','','party-status');status.setAttribute('role','status');status.setAttribute('aria-live','polite');
if(playing!==null){const back=B(u('back'),()=>{playing=null;render()},'studio-back');section.append(back,stage,status);play(playing);return}
const ok=i=>previewing||(p.open&&p.unlock(i)<=today());
if(fid==='christmas'){const grid=E('div','','advent-grid');const order=seeded(p.year);order.forEach(i=>{const b=B('',()=>{if(!ok(i)){say(u('doorLocked',{n:i+1}),false);return}playing=i;render()},'advent-door');b.dataset.door=i+1;const isDone=!!done[i];b.classList.toggle('done',isDone);b.classList.toggle('locked',!ok(i));b.append(E('span',String(i+1),'advent-num'));if(isDone)b.append(E('span',rewardOf(fid,i),'advent-orn'));else if(!ok(i))b.append(E('span','🔒','advent-lock'));b.setAttribute('aria-label',`${u('door',{n:i+1})}${isDone?' ✓ '+rewardOf(fid,i):!ok(i)?' 🔒':''}`);grid.append(b)});stage.append(grid);
stage.append(E('h3',u('tree')),treeSVG(Object.keys(done).map(Number)));if(Object.keys(done).length>=24)stage.append(E('p',u('merry'),'fest-merry'))}
else{const map=E('div','','fest-days');for(let i=0;i<p.days;i++){const isDone=!!done[i],b=B('',()=>{if(!ok(i)){say(u('opens',{when:whenText(p.unlock(i))}),false);return}playing=i;render()},'fest-day');b.dataset.day=i+1;b.classList.toggle('done',isDone);b.classList.toggle('locked',!ok(i));b.append(E('strong',u('day',{n:i+1})),E('span',isDone?rewardOf(fid,i):ok(i)?typeIcon(i):'🔒','fest-day-icon'));if(!ok(i)&&p.open)b.append(E('small',whenText(p.unlock(i))));map.append(b)}stage.append(map);
const col=E('div','','fest-collection');col.append(E('strong',u('collection')+': '),E('span',Object.keys(done).map(i=>rewardOf(fid,+i)).join(' ')||'—'));stage.append(col);if(Object.keys(done).length>=p.days)stage.append(E('p',u('allDone'),'fest-merry'));
const album=d.album||[];if(album.length){stage.append(E('h3',u('album')));const row=E('div','','fest-album');album.slice(-8).forEach(a=>row.append(baseSVG(a,true)));stage.append(row)}}
section.append(stage,status)}
const typeIcon=i=>({find:'🔍',pattern:'🔁',memory:'🃏',count:'🔢',decorate:'🎨'})[TYPES[i%TYPES.length]];
function seeded(y){const a=[...Array(24).keys()];let s=y*9301+49297;for(let i=a.length-1;i>0;i--){s=(s*9301+49297)%233280;const j=Math.floor(s/233280*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function complete(i,type,extra){const p=plan(fid),d=read(fid,p.year);d.done={...(d.done||{}),[i]:true};if(extra)d.album=[...(d.album||[]),extra].slice(-12);if(Object.keys(d.done).length>=p.days)d.complete=true;save(fid,p.year,d);gardenCelebrate('festival-'+type);const r=rewardOf(fid,i);say(u('reward',{r}));stage.dataset.done='1';
const all=!!d.complete;if(all)setTimeout(()=>say(fid==='christmas'?u('merry'):u('allDone')),quickMs(900));stage.append(B(u('back'),()=>{playing=null;render()},'primary fest-back'))}
const quickMs=ms=>document.body.classList.contains('quiet')?30:ms;
function play(i){const type=TYPES[i%TYPES.length],h=H[fid],lvl=Math.floor(i/5);stage.dataset.type=type;stage.append(E('h3',fid==='christmas'?u('door',{n:i+1}):u('day',{n:i+1})));({find,pattern,memory,count,decorate})[type](h,i,lvl)}
// Găsește
function find(h,i,lvl){const a=age(),target=h.sym[i%h.sym.length],k=(a<=5?3:a<=8?5:7)+lvl,others=h.sym.filter(s=>s!==target),n=(a<=5?6:a<=8?12:18)+lvl*2;let left=k,done=false;const items=mix([...Array(k).fill(target),...Array.from({length:n},()=>pick(others))]);
const info=E('p','','studio-help');const upd=()=>{info.textContent=u('findHelp',{icon:target,n:left})};stage.dataset.target=target;stage.append(info);const scene=E('div','','fest-find');
items.forEach(s=>{const b=B(s,()=>{if(done||b.classList.contains('found'))return;if(s===target){b.classList.add('found');b.disabled=true;left--;window.gardenSound?.('pop');upd();status.textContent='';if(!left){done=true;complete(i,'find')}}else{gardenMiss('festival-find');say(u('findWrong',{icon:target}),false)}},'fest-item');b.dataset.s=s;b.style.setProperty('--r',(rand(40)-20)+'deg');b.style.setProperty('--dx',(rand(14)-7)+'px');b.style.setProperty('--dy',(rand(14)-7)+'px');scene.append(b)});stage.append(scene);upd()}
// Continuă șirul
function pattern(h,i,lvl){const a=age(),units=a<=5?[[0,1],[0,0,1]]:a<=8?[[0,1,2],[0,0,1],[0,1,1]]:[[0,1,2,3],[0,1,1,2],[0,0,1,2]],unit=pick(units),syms=mix(h.sym).slice(0,4),len=(a<=5?6:a<=8?8:10)+Math.min(lvl,2),blanks=a<=5?2:3,seq=Array.from({length:len},(_,j)=>syms[unit[j%unit.length]]);let pos=len-blanks,done=false;
help(u('patternHelp'));const row=E('div','','fest-pattern');const cells=seq.map((s,j)=>{const c=E('span',j<pos?s:'?','fest-cell');if(j>=pos)c.classList.add('blank');row.append(c);return c});stage.append(row);stage.dataset.next=seq[pos];
const opts=mix([...new Set(unit.map(x=>syms[x]))].concat(a>5?[syms.find((_,j)=>!unit.includes(j))||h.sym[5]]:[])),box=E('div','','craft-answers');
opts.forEach(s=>{const b=B(s,()=>{if(done)return;if(s===seq[pos]){cells[pos].textContent=s;cells[pos].classList.remove('blank');pos++;window.gardenSound?.('pop');status.textContent='';stage.dataset.next=seq[pos]||'';if(pos>=len){done=true;complete(i,'pattern')}}else{gardenMiss('festival-pattern');say(u('patternWrong'),false)}},'craft-answer fest-opt');b.dataset.s=s;box.append(b)});stage.append(box)}
// Memory
function memory(h,i,lvl){const a=age(),pairs=Math.min(8,(a<=5?3:a<=8?6:8)),pool=[...new Set([...h.sym,...h.stickers])],cards=mix(mix(pool).slice(0,pairs).flatMap(s=>[s,s]));let open=[],matched=new Set(),moves=0,busy=false;
help(u('memoryHelp'));const mv=E('p',u('moves',{n:0}),'versus-pairs'),grid=E('div','','fest-memory');grid.style.setProperty('--cols',pairs<=3?3:4);stage.append(mv,grid);
const els=cards.map((s,j)=>{const b=B('?',()=>flip(j),'memory-card fest-card');b.dataset.s=s;b.setAttribute('aria-label',u('card',{n:j+1}));grid.append(b);return b});
function paint(){els.forEach((b,j)=>{const show=open.includes(j)||matched.has(j);b.textContent=show?cards[j]:'?';b.classList.toggle('matched',matched.has(j));b.disabled=matched.has(j);b.setAttribute('aria-label',show?cards[j]:u('card',{n:j+1}))});mv.textContent=u('moves',{n:moves})}
function flip(j){if(busy||open.includes(j)||matched.has(j))return;open.push(j);paint();if(open.length<2)return;moves++;const [x,y]=open;if(cards[x]===cards[y]){matched.add(x);matched.add(y);open=[];window.gardenSound?.('pop');paint();if(matched.size===cards.length)complete(i,'memory')}else{busy=true;paint();setTimeout(()=>{open=[];busy=false;paint()},quickMs(800))}}
paint()}
// Calcule
function numOpts(ans){const s=new Set([ans]);let k=1;while(s.size<4){[ans+k,ans-k].forEach(v=>{if(v>=0&&s.size<4)s.add(v)});k++}return mix([...s])}
function count(h,i,lvl){const a=age(),icon=h.sym[i%h.sym.length];let text,show='',ans;
if(a<=5){ans=3+rand(5)+Math.min(lvl,2);text=u('cYoung',{icon});show=icon.repeat(ans)}
else if(a<=8){const i2=h.sym[(i+1)%h.sym.length],x=2+rand(5),y=2+rand(5);ans=x+y;text=u('cMid',{a:x,i1:icon,b:y,i2});show=icon.repeat(x)+'\n'+i2.repeat(y)}
else if(Math.random()<.5){const n=3+rand(6),k=2+rand(4);ans=n*k;text=u('cOld1',{n,icon,k})}else{const k=2+rand(4),n=2+rand(6);ans=n;text=u('cOld2',{t:n*k,icon,k})}
help(text);if(show){const v=E('div',show,'craft-show');v.setAttribute('aria-hidden','true');stage.append(v)}stage.dataset.answer=ans;let done=false;const box=E('div','','craft-answers');
numOpts(ans).forEach(o=>{const b=B(String(o),()=>{if(done)return;if(o===ans){done=true;b.classList.add('right');say(u('good'));complete(i,'count')}else{gardenMiss('festival-count');b.classList.add('wrong-pick');say(u('nearly'),false)}},'craft-answer');box.append(b)});stage.append(box)}
// Decorează: dovleac, ou, brad, mărțișor, planetă, zmeu, ghiozdan
function baseSVG(o,small){const svg=S('svg',{viewBox:'0 0 200 200',class:small?'fest-mini':'fest-base'}),id='f'+Math.random().toString(36).slice(2,8),cp=S('clipPath',{id}),shape=[];const col=o.color;
const add=(t,a)=>{const e=S(t,{...a,fill:a.fill||col,stroke:'#2b2b2b','stroke-width':2.5});shape.push(e);return e};
if(o.base==='pumpkin'){add('ellipse',{cx:62,cy:115,rx:42,ry:58});add('ellipse',{cx:138,cy:115,rx:42,ry:58});add('ellipse',{cx:100,cy:115,rx:50,ry:64});svg.append(S('rect',{x:93,y:36,width:14,height:22,rx:4,fill:'#2f9e44',stroke:'#2b2b2b','stroke-width':2}))}
else if(o.base==='egg')add('ellipse',{cx:100,cy:108,rx:62,ry:82});
else if(o.base==='tree'){add('polygon',{points:'100,18 150,78 50,78'});add('polygon',{points:'100,50 165,128 35,128'});add('polygon',{points:'100,90 178,176 22,176'});svg.append(S('rect',{x:88,y:176,width:24,height:20,fill:'#8d6e63'}))}
else if(o.base==='card'){svg.append(S('path',{d:'M100 8 C 90 20, 110 30, 100 42',stroke:'#e63946','stroke-width':4,fill:'none'}),S('path',{d:'M104 8 C 94 20, 114 30, 104 42',stroke:'#fff','stroke-width':4,fill:'none'}));add('path',{d:'M100 180 C 20 120, 30 50, 72 50 C 90 50, 100 64, 100 72 C 100 64, 110 50, 128 50 C 170 50, 180 120, 100 180 Z'})}
else if(o.base==='globe'){add('circle',{cx:100,cy:104,r:84});svg.append(S('path',{d:'M60 70 q20 -20 40 0 q10 20 -10 30 q-20 10 -30 -5 z M120 120 q25 -10 35 10 q-5 25 -30 20 q-15 -10 -5 -30 z',fill:'#69db7c',stroke:'#2b2b2b','stroke-width':2}))}
else if(o.base==='kite'){add('polygon',{points:'100,14 168,92 100,176 32,92'});svg.append(S('path',{d:'M100 176 q-12 8 0 16 q12 8 -2 12',stroke:'#2b2b2b','stroke-width':2,fill:'none'}),S('line',{x1:100,y1:14,x2:100,y2:176,stroke:'#2b2b2b','stroke-width':1.5}),S('line',{x1:32,y1:92,x2:168,y2:92,stroke:'#2b2b2b','stroke-width':1.5}))}
else{add('rect',{x:40,y:40,width:120,height:150,rx:26});svg.append(S('path',{d:'M70 40 q30 -40 60 0',stroke:'#2b2b2b','stroke-width':6,fill:'none'}));shape.push(S('rect',{x:62,y:110,width:76,height:56,rx:12,fill:'#ffffff55',stroke:'#2b2b2b','stroke-width':2.5}))}
shape.forEach(e=>{cp.append(e.cloneNode());svg.append(e)});svg.prepend(cp);const g=S('g',{'clip-path':`url(#${id})`});
if(o.pattern===1)for(let y=20;y<200;y+=18)g.append(S('rect',{x:0,y,width:200,height:7,fill:'#ffffff88'}));if(o.pattern===2)for(let y=20;y<200;y+=16)for(let x=10+(y/16%2)*8;x<200;x+=16)g.append(S('circle',{cx:x,cy:y,r:3.5,fill:'#ffffffaa'}));svg.append(g);
if(o.base==='pumpkin'){const f=S('g',{fill:'#3b1f0b'});if(o.face===0){f.append(S('polygon',{points:'70,95 86,95 78,80'}),S('polygon',{points:'114,95 130,95 122,80'}),S('path',{d:'M70 128 q30 26 60 0 q-30 12 -60 0z'}))}else if(o.face===1){f.append(S('circle',{cx:78,cy:92,r:9}),S('rect',{x:112,y:88,width:20,height:6,rx:3}),S('path',{d:'M68 128 l12 8 l10 -8 l10 8 l10 -8 l10 8 l12 -8 q-32 30 -64 0z'}))}else{f.append(S('circle',{cx:78,cy:92,r:10}),S('circle',{cx:122,cy:92,r:10}),S('ellipse',{cx:100,cy:136,rx:12,ry:15}))}svg.append(f)}
(o.stickers||[]).forEach(s=>{const t=S('text',{x:s.x,y:s.y,'font-size':small?26:24,'text-anchor':'middle','dominant-baseline':'central'});t.textContent=s.s;svg.append(t)});
svg.setAttribute('role','img');svg.setAttribute('aria-label',L(U.bases[o.base]));return svg}
function decorate(h,i){const o={base:h.base,color:h.tint,pattern:0,face:0,stickers:[]};let sel=h.stickers[0],done=false;help(u('decHelp'));
const wrap=E('div','','fest-deco');const view=E('div','','fest-deco-view');const ctrl=E('div','','fest-deco-ctrl');wrap.append(view,ctrl);stage.append(wrap);
const draw=()=>{view.replaceChildren(baseSVG(o));stage.dataset.stickers=o.stickers.length};
view.addEventListener('click',e=>{if(done)return;const r=view.firstChild.getBoundingClientRect();const x=Math.round((e.clientX-r.left)/r.width*200),y=Math.round((e.clientY-r.top)/r.height*200);o.stickers.push({s:sel,x:Math.min(188,Math.max(12,x)),y:Math.min(188,Math.max(12,y))});window.gardenSound?.('pop');draw();status.textContent=''});
const group=(label,items,fn,cur,cls)=>{const g=E('div','','pot-group'),row=E('div','','draw-tools');row.setAttribute('role','group');row.setAttribute('aria-label',label);g.append(E('strong',label),row);items.forEach((it,j)=>{const b=B(it.t||'',()=>{fn(j);row.querySelectorAll('button').forEach((x,k)=>x.setAttribute('aria-pressed',k===j));draw()},cls||'');if(it.c){b.style.setProperty('--sw',it.c);b.setAttribute('aria-label',it.c)}b.setAttribute('aria-pressed',j===cur);row.append(b)});ctrl.append(g)};
if(h.base==='pumpkin')group(u('face'),U.faces.map(f=>({t:L(f)})),j=>o.face=j,0);
group(u('color'),COLORS.map(c=>({c})),j=>o.color=COLORS[j],-1,'swatch');group(u('pattern'),U.patterns.map(p=>({t:L(p)})),j=>o.pattern=j,0);
const sg=E('div','','pot-group'),sr=E('div','','draw-tools fest-stickers');sr.setAttribute('role','group');sr.setAttribute('aria-label',u('stickers'));sg.append(E('strong',u('stickers')),sr);h.stickers.forEach(s=>{const b=B(s,()=>{sel=s;sr.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',x.dataset.s===s))},'stamp-btn');b.dataset.s=s;b.setAttribute('aria-pressed',s===sel);sr.append(b)});ctrl.append(sg);
const row=E('div','','draw-tools');row.append(B(u('decUndo'),()=>{o.stickers.pop();draw()}),B(u('decDone'),()=>{if(done)return;if(o.stickers.length<3){say(u('decMore',{n:3-o.stickers.length}),false);return}done=true;complete(i,'decorate',{...o,stickers:[...o.stickers]})},'primary fest-finish'));ctrl.append(row);draw()}
function treeSVG(done){const svg=baseSVG({base:'tree',color:'#2f9e44',pattern:0,stickers:[]});svg.classList.add('advent-tree');const SPOTS=[[100,40],[86,64],[114,64],[100,76],[72,104],[128,104],[92,96],[110,112],[58,140],[142,140],[80,130],[120,130],[100,146],[44,168],[156,168],[70,160],[130,160],[92,168],[110,168],[60,122],[140,122],[100,120],[84,150],[116,150]];
done.forEach(i=>{const [x,y]=SPOTS[i%SPOTS.length],t=S('text',{x,y,'font-size':16,'text-anchor':'middle','dominant-baseline':'central'});t.textContent=ORN[i%ORN.length];svg.append(t)});if(done.length>=24){const t=S('text',{x:100,y:22,'font-size':26,'text-anchor':'middle','dominant-baseline':'central'});t.textContent='🌟';svg.append(t)}svg.setAttribute('aria-label',`${u('tree')}: ${done.length}/24`);return svg}
function open(id,preview){fid=id;playing=null;previewing=!!preview;gardenGo('festival');render();section.querySelector('h2')?.focus?.()}
window.gardenFestival={active,open,home(){const a=active();if(!a)return null;const h=H[a.id];if(a.id==='christmas'){const d=read('christmas',a.year).done||{};return {text:a.day<=24&&new Date()<new Date(a.year,11,25)?u('homeAdvent',{d:Math.min(24,a.day)}):u('homeXmas',{n:Object.keys(d).length}),button:u('openAdvent'),open:()=>open('christmas')}}return {text:u('homeText',{icon:h.icon,title:L(h.title),d:a.day,n:a.days}),button:u('enter'),open:()=>open(a.id)}}};
// Butoane pe cardurile de evenimente (Activități)
const prev=renderEvents;renderEvents=function(){prev();[...$('eventsList').children].forEach(card=>{const id=card.dataset.event;if(!H[id]||card.querySelector('.fest-open'))return;const p=plan(id);card.append(B(id==='christmas'?u('cardAdvent'):u('cardBtn'),()=>open(id,!p.open),'fest-open'))})};
document.addEventListener('garden:open',e=>{const {view,mode}=e.detail||{};if(view!=='festival')return;open(mode||active()?.id||'halloween',!active())});
gardenOn(()=>{if(fid)render();try{renderEvents()}catch{}});if(profile)try{renderEvents()}catch{}
})();
