(()=>{
const W={ro:{nav:'Meniu',home:'Acasă',adventures:'Aventuri',learning:'Numere',worlds:'12 lumi',activities:'Activități',birthday:'Aniversare',discover:'Descoperă',languages:'Limbi',languagesTitle:'Limbi străine',languagesDesc:'Engleză, franceză, germană și spaniolă prin joc',collection:'Colecția',versus:'Contra Robo',versusTitle:'Contra lui Robo',versusDesc:'X și 0, Memory și bețișoare cu un robot care se adaptează',discoverTitle:'Descoperă',discoverDesc:'Litere, ceas, bani, puzzle, povești',collectionTitle:'Colecția mea',collectionDesc:'Abțibilduri, grădina ta, insigne',choose:'Ce vrei să faci azi?',hint:'Atinge un joc și începe imediat.',adventuresTitle:'Aventuri interactive',adventuresDesc:'Unicorn, brioșe, mașini și rachetă',learningTitle:'Numere · Match · Culori',learningDesc:'Ordonează, potrivește, amestecă',worldsTitle:'Cele 12 lumi',worldsDesc:'Povești, provocarea zilei, constructor',activitiesTitle:'Activități pe vârsta ta',activitiesDesc:'Jocuri scurte, evenimente, album',birthdayTitle:'Atelierul aniversar',today:'Aniversarea este deschisă!',until:'Aniversare în {n} zile'},en:{nav:'Menu',home:'Home',adventures:'Adventures',learning:'Numbers',worlds:'12 worlds',activities:'Activities',birthday:'Birthday',discover:'Discover',languages:'Languages',languagesTitle:'Foreign languages',languagesDesc:'English, French, German and Spanish through play',collection:'Collection',versus:'Versus Robo',versusTitle:'Versus Robo',versusDesc:'Tic-tac-toe, Memory and sticks against a robot that adapts',discoverTitle:'Discover',discoverDesc:'Letters, clock, money, puzzles, stories',collectionTitle:'My collection',collectionDesc:'Stickers, your garden, badges',choose:'What would you like to do today?',hint:'Tap a game and start right away.',adventuresTitle:'Interactive adventures',adventuresDesc:'Unicorn, cupcakes, cars and rocket',learningTitle:'Numbers · Match · Colors',learningDesc:'Order, match, mix',worldsTitle:'The 12 worlds',worldsDesc:'Stories, daily challenge, builder',activitiesTitle:'Activities for your age',activitiesDesc:'Short games, events, album',birthdayTitle:'Birthday workshop',today:'Your birthday is open!',until:'Birthday in {n} days'}};
Object.assign(W,window.gardenLangs?.home||{});const tx=(k,v={})=>String(W[lang]?.[k]??W.en[k]??k).replace(/\{(\w+)\}/g,(_,x)=>v[x]??'');const el=(tag,txt='',cls='')=>{const x=document.createElement(tag);x.textContent=txt;x.className=cls;return x};
const VIEWS=[['home','🏠'],['adventures','🎮'],['learning','🔢'],['discover','🔤'],['languages','🗣️'],['worlds','🌍'],['activities','🧩'],['collection','🌼'],['versus','🤖'],['birthday','🎂']];
const app=$('app'),birthday=$('birthday');
// Fiecare secțiune aparține unui singur ecran; CSS ascunde restul.
$('interactiveAdventures').dataset.view='adventures';$('grandAdventure').dataset.view='worlds';app.querySelector('.theme-scene').dataset.view='activities';$('extras').dataset.view='activities';
const nav=el('nav','','garden-nav'),quick=el('section','','card quick-home');quick.dataset.view='home';app.prepend(nav);app.querySelector('.row.section').after(quick);
let view='home';try{view=sessionStorage.getItem('garden_view')||'home'}catch{}
function dayCount(){if(!profile)return 0;const now=new Date(),[,m,d]=profile.dob.split('-').map(Number);let next=new Date(now.getFullYear(),m-1,d);if(m===2&&d===29&&next.getMonth()!==1)next=new Date(now.getFullYear(),1,28);if(next<new Date(now.getFullYear(),now.getMonth(),now.getDate())){next=new Date(now.getFullYear()+1,m-1,d);if(m===2&&d===29&&next.getMonth()!==1)next=new Date(now.getFullYear()+1,1,28)}return Math.max(0,Math.round((next-new Date(now.getFullYear(),now.getMonth(),now.getDate()))/864e5))}
function birthdayText(){const now=new Date(),open=[now.getFullYear()-1,now.getFullYear()].some(y=>{const [a,b]=eventWindow('birthdayEvent',y);return now>=a&&now<b});return open?tx('today'):tx('until',{n:dayCount()})}
function go(v,focus=true){if(!VIEWS.some(([k])=>k===v))v='home';view=v;try{sessionStorage.setItem('garden_view',v)}catch{}app.dataset.view=v;birthday.hidden=false;nav.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',b.dataset.go===v));if(app.hidden)return;if(nav.getBoundingClientRect().top<0)nav.scrollIntoView({block:'start'});if(focus){const h=[...app.querySelectorAll('h1,h2')].find(x=>x.offsetParent&&x.closest(`[data-view=${v}]`));if(h){h.tabIndex=-1;h.focus({preventScroll:true})}}}
window.gardenGo=go;
function draw(){if(!profile)return;nav.setAttribute('aria-label',tx('nav'));nav.replaceChildren(...VIEWS.map(([k,icon])=>{const b=el('button','');b.type='button';b.dataset.go=k;b.append(el('span',icon,'ni'),el('span',tx(k)));b.setAttribute('aria-pressed',k===view);b.onclick=()=>go(k);return b}));
const grid=el('div','','quick-grid');VIEWS.slice(1).forEach(([k,icon])=>{const b=el('button','');b.type='button';b.onclick=()=>go(k);b.append(el('span',icon,'quick-icon'),el('strong',tx(k+'Title')),el('span',k==='birthday'?birthdayText():tx(k+'Desc'),'small'));grid.append(b)});quick.replaceChildren(el('h2',tx('choose')),el('p',tx('hint')),grid)}
gardenOn(r=>{draw();if(r==='start'){view='home';go('home')}else if(r==='switch')go('home',false)});
app.dataset.view=view;if(profile){draw();go(view,false)}
})();
