// Grădina Curioasă — Limbi străine: engleză, franceză, germană, spaniolă prin joc.
// Instrucțiunile rămân în limba jocului; cuvintele sunt în limba aleasă pentru învățat.
(()=>{
const UI={
ro:{title:"Limbi străine",intro:"Învață cuvinte noi jucându-te. Apasă 🔊 ca să auzi pronunția.",learn:"Limba pe care o înveți",theme:"Tema",listen:"Ascultă și atinge",memory:"Memory cu cuvinte",spell:"Scrie cuvântul",sentence:"Propoziții",dialog:"Dialoguri",daily:"Cuvintele zilei",listenHelp:"Ascultă cuvântul și atinge imaginea potrivită.",memoryHelp:"Găsește perechile: imaginea și cuvântul care îi corespunde. Atinge un cuvânt ca să-l auzi.",spellHelp:"Pune literele în ordine ca să scrii cuvântul.",sentenceHelp:"Alege cuvântul care completează propoziția.",dialogHelp:"Alege răspunsul potrivit în conversație.",dailyHelp:"Câteva cuvinte în fiecare zi. Cele învățate revin după câteva zile, ca să rămână în minte.",hear:"🔊 Ascultă",showWord:"Cuvântul:",noVoice:"Telefonul nu are voce pentru {lang}. Citiți cuvântul împreună cu un adult.",next:"Mai departe",well:"Bravo! Ai descoperit!",retry:"Mai încearcă o dată.",learned:"Cuvinte învățate în {lang}: {n}",dailyPlan:"Azi: {n} cuvinte, dintre care {r} de repetat.",know:"L-am văzut, mai departe",quiz:"Acum alege imaginea pentru fiecare cuvânt.",dailyDone:"Ai terminat cuvintele de azi! Revino mâine pentru altele.",dailyAgain:"Exersează din nou",meaning:"💡 {g}",scenario:"Alege o situație",done:"Ai terminat conversația! 🎉",again:"Încă o dată",card:"Carte {n}",pair:"pereche găsită",sentenceDone:"Corect: {s}",themes:{animals:"Animale",fruits:"Fructe",colors:"Culori",numbers:"Numere",house:"Casa",school:"Școala",body:"Corpul",clothes:"Haine"},langs:{en:"Engleză",fr:"Franceză",de:"Germană",es:"Spaniolă"},colorNames:{red:"roșu",blue:"albastru",yellow:"galben",green:"verde",orange:"portocaliu",purple:"mov",pink:"roz",black:"negru",white:"alb",brown:"maro"},scenarios:{meet:"Cunoștințe noi",shop:"La magazin",school:"La școală"}},
en:{title:"Foreign languages",intro:"Learn new words by playing. Tap 🔊 to hear the pronunciation.",learn:"Language you are learning",theme:"Theme",listen:"Listen and tap",memory:"Word memory",spell:"Spell the word",sentence:"Sentences",dialog:"Dialogues",daily:"Words of the day",listenHelp:"Listen to the word and tap the matching picture.",memoryHelp:"Find the pairs: a picture and its word. Tap a word to hear it.",spellHelp:"Put the letters in order to spell the word.",sentenceHelp:"Choose the word that completes the sentence.",dialogHelp:"Choose the right reply in the conversation.",dailyHelp:"A few words every day. Learned words come back after a few days so they stick.",hear:"🔊 Listen",showWord:"The word:",noVoice:"This device has no {lang} voice. Read the word together with an adult.",next:"Keep going",well:"Well done! You found it!",retry:"Try once more.",learned:"Words learned in {lang}: {n}",dailyPlan:"Today: {n} words, {r} of them to review.",know:"Seen it, next",quiz:"Now choose the picture for each word.",dailyDone:"You finished today’s words! Come back tomorrow for more.",dailyAgain:"Practise again",meaning:"💡 {g}",scenario:"Choose a situation",done:"You finished the conversation! 🎉",again:"Once more",card:"Card {n}",pair:"pair found",sentenceDone:"Correct: {s}",themes:{animals:"Animals",fruits:"Fruit",colors:"Colours",numbers:"Numbers",house:"Home",school:"School",body:"Body",clothes:"Clothes"},langs:{en:"English",fr:"French",de:"German",es:"Spanish"},colorNames:{red:"red",blue:"blue",yellow:"yellow",green:"green",orange:"orange",purple:"purple",pink:"pink",black:"black",white:"white",brown:"brown"},scenarios:{meet:"Meeting someone",shop:"At the shop",school:"At school"}},
hu:{title:"Idegen nyelvek",intro:"Tanulj új szavakat játszva. Érintsd meg a 🔊 gombot a kiejtésért.",learn:"A nyelv, amit tanulsz",theme:"Téma",listen:"Hallgasd és érintsd",memory:"Szómemória",spell:"Rakd ki a szót",sentence:"Mondatok",dialog:"Párbeszédek",daily:"A nap szavai",listenHelp:"Hallgasd meg a szót, és érintsd meg a hozzá illő képet.",memoryHelp:"Keresd a párokat: a képet és a hozzá tartozó szót. Érints meg egy szót, hogy meghalld.",spellHelp:"Rakd sorba a betűket, hogy kirakd a szót.",sentenceHelp:"Válaszd ki a szót, amely kiegészíti a mondatot.",dialogHelp:"Válaszd ki a helyes választ a beszélgetésben.",dailyHelp:"Minden nap néhány szó. A megtanultak pár nap múlva visszatérnek, hogy megmaradjanak.",hear:"🔊 Meghallgatom",showWord:"A szó:",noVoice:"Ezen az eszközön nincs {lang} hang. Olvassátok fel a szót egy felnőttel.",next:"Tovább",well:"Ügyes! Rájöttél!",retry:"Próbáld még egyszer.",learned:"Megtanult szavak ({lang}): {n}",dailyPlan:"Ma: {n} szó, ebből {r} ismétlés.",know:"Láttam, tovább",quiz:"Most válaszd ki minden szóhoz a képet.",dailyDone:"Kész vagy a mai szavakkal! Holnap jöhetnek újak.",dailyAgain:"Gyakorlás újra",meaning:"💡 {g}",scenario:"Válassz helyzetet",done:"Befejezted a beszélgetést! 🎉",again:"Még egyszer",card:"{n}. kártya",pair:"megtalált pár",sentenceDone:"Helyes: {s}",themes:{animals:"Állatok",fruits:"Gyümölcsök",colors:"Színek",numbers:"Számok",house:"Otthon",school:"Iskola",body:"Test",clothes:"Ruhák"},langs:{en:"Angol",fr:"Francia",de:"Német",es:"Spanyol"},colorNames:{red:"piros",blue:"kék",yellow:"sárga",green:"zöld",orange:"narancssárga",purple:"lila",pink:"rózsaszín",black:"fekete",white:"fehér",brown:"barna"},scenarios:{meet:"Ismerkedés",shop:"A boltban",school:"Az iskolában"}},
uk:{title:"Іноземні мови",intro:"Вчи нові слова граючись. Натисни 🔊, щоб почути вимову.",learn:"Мова, яку ти вчиш",theme:"Тема",listen:"Послухай і торкнися",memory:"Мемо зі словами",spell:"Склади слово",sentence:"Речення",dialog:"Діалоги",daily:"Слова дня",listenHelp:"Послухай слово й торкнися потрібної картинки.",memoryHelp:"Знайди пари: картинку і відповідне слово. Торкнися слова, щоб його почути.",spellHelp:"Розстав літери по порядку, щоб скласти слово.",sentenceHelp:"Обери слово, яке доповнює речення.",dialogHelp:"Обери правильну відповідь у розмові.",dailyHelp:"Кілька слів щодня. Вивчені слова повертаються через кілька днів, щоб запам’яталися.",hear:"🔊 Послухати",showWord:"Слово:",noVoice:"На цьому пристрої немає голосу для мови: {lang}. Прочитайте слово разом із дорослим.",next:"Далі",well:"Молодець! Ти знайшов(-ла)!",retry:"Спробуй ще раз.",learned:"Вивчені слова ({lang}): {n}",dailyPlan:"Сьогодні: {n} слів, з них {r} на повторення.",know:"Бачив(-ла), далі",quiz:"Тепер обери картинку для кожного слова.",dailyDone:"Ти вивчив(-ла) слова на сьогодні! Повертайся завтра.",dailyAgain:"Потренуватися ще",meaning:"💡 {g}",scenario:"Обери ситуацію",done:"Розмову завершено! 🎉",again:"Ще раз",card:"Картка {n}",pair:"пару знайдено",sentenceDone:"Правильно: {s}",themes:{animals:"Тварини",fruits:"Фрукти",colors:"Кольори",numbers:"Числа",house:"Дім",school:"Школа",body:"Тіло",clothes:"Одяг"},langs:{en:"Англійська",fr:"Французька",de:"Німецька",es:"Іспанська"},colorNames:{red:"червоний",blue:"синій",yellow:"жовтий",green:"зелений",orange:"помаранчевий",purple:"фіолетовий",pink:"рожевий",black:"чорний",white:"білий",brown:"коричневий"},scenarios:{meet:"Знайомство",shop:"У магазині",school:"У школі"}}};
const TARGETS={en:{voice:"en-GB",flag:"🇬🇧"},fr:{voice:"fr-FR",flag:"🇫🇷"},de:{voice:"de-DE",flag:"🇩🇪"},es:{voice:"es-ES",flag:"🇪🇸"}};
// [id, afișare, {en, fr, de, es}] — pentru culori afișarea e culoarea, pentru numere numărul de buline.
const V={
animals:[["cat","🐱",{en:"cat",fr:"le chat",de:"die Katze",es:"el gato"}],["dog","🐶",{en:"dog",fr:"le chien",de:"der Hund",es:"el perro"}],["fish","🐟",{en:"fish",fr:"le poisson",de:"der Fisch",es:"el pez"}],["bird","🐦",{en:"bird",fr:"l'oiseau",de:"der Vogel",es:"el pájaro"}],["horse","🐴",{en:"horse",fr:"le cheval",de:"das Pferd",es:"el caballo"}],["cow","🐄",{en:"cow",fr:"la vache",de:"die Kuh",es:"la vaca"}],["rabbit","🐰",{en:"rabbit",fr:"le lapin",de:"das Kaninchen",es:"el conejo"}],["frog","🐸",{en:"frog",fr:"la grenouille",de:"der Frosch",es:"la rana"}]],
fruits:[["apple","🍎",{en:"apple",fr:"la pomme",de:"der Apfel",es:"la manzana"}],["banana","🍌",{en:"banana",fr:"la banane",de:"die Banane",es:"el plátano"}],["orange","🍊",{en:"orange",fr:"l'orange",de:"die Orange",es:"la naranja"}],["grapes","🍇",{en:"grapes",fr:"le raisin",de:"die Trauben",es:"las uvas"}],["strawberry","🍓",{en:"strawberry",fr:"la fraise",de:"die Erdbeere",es:"la fresa"}],["pear","🍐",{en:"pear",fr:"la poire",de:"die Birne",es:"la pera"}],["cherry","🍒",{en:"cherry",fr:"la cerise",de:"die Kirsche",es:"la cereza"}],["watermelon","🍉",{en:"watermelon",fr:"la pastèque",de:"die Wassermelone",es:"la sandía"}]],
colors:[["red","#e84b56",{en:"red",fr:"rouge",de:"rot",es:"rojo"}],["blue","#3d8afa",{en:"blue",fr:"bleu",de:"blau",es:"azul"}],["yellow","#ffd34c",{en:"yellow",fr:"jaune",de:"gelb",es:"amarillo"}],["green","#34b779",{en:"green",fr:"vert",de:"grün",es:"verde"}],["orange","#fa9444",{en:"orange",fr:"orange",de:"orange",es:"naranja"}],["purple","#9a66dc",{en:"purple",fr:"violet",de:"lila",es:"morado"}],["pink","#ef79b4",{en:"pink",fr:"rose",de:"rosa",es:"rosa"}],["black","#1b1b1f",{en:"black",fr:"noir",de:"schwarz",es:"negro"}],["white","#f8f9fa",{en:"white",fr:"blanc",de:"weiß",es:"blanco"}],["brown","#8a593b",{en:"brown",fr:"marron",de:"braun",es:"marrón"}]],
numbers:[["1",1,{en:"one",fr:"un",de:"eins",es:"uno"}],["2",2,{en:"two",fr:"deux",de:"zwei",es:"dos"}],["3",3,{en:"three",fr:"trois",de:"drei",es:"tres"}],["4",4,{en:"four",fr:"quatre",de:"vier",es:"cuatro"}],["5",5,{en:"five",fr:"cinq",de:"fünf",es:"cinco"}],["6",6,{en:"six",fr:"six",de:"sechs",es:"seis"}],["7",7,{en:"seven",fr:"sept",de:"sieben",es:"siete"}],["8",8,{en:"eight",fr:"huit",de:"acht",es:"ocho"}],["9",9,{en:"nine",fr:"neuf",de:"neun",es:"nueve"}],["10",10,{en:"ten",fr:"dix",de:"zehn",es:"diez"}]],
house:[["house","🏠",{en:"house",fr:"la maison",de:"das Haus",es:"la casa"}],["door","🚪",{en:"door",fr:"la porte",de:"die Tür",es:"la puerta"}],["bed","🛏️",{en:"bed",fr:"le lit",de:"das Bett",es:"la cama"}],["key","🔑",{en:"key",fr:"la clé",de:"der Schlüssel",es:"la llave"}],["clock","⏰",{en:"clock",fr:"l'horloge",de:"die Uhr",es:"el reloj"}],["bath","🛁",{en:"bath",fr:"la baignoire",de:"die Badewanne",es:"la bañera"}],["phone","📱",{en:"phone",fr:"le téléphone",de:"das Telefon",es:"el teléfono"}],["tv","📺",{en:"television",fr:"la télévision",de:"der Fernseher",es:"la televisión"}]],
school:[["book","📖",{en:"book",fr:"le livre",de:"das Buch",es:"el libro"}],["pencil","✏️",{en:"pencil",fr:"le crayon",de:"der Bleistift",es:"el lápiz"}],["backpack","🎒",{en:"backpack",fr:"le cartable",de:"der Rucksack",es:"la mochila"}],["scissors","✂️",{en:"scissors",fr:"les ciseaux",de:"die Schere",es:"las tijeras"}],["ruler","📏",{en:"ruler",fr:"la règle",de:"das Lineal",es:"la regla"}],["palette","🎨",{en:"palette",fr:"la palette",de:"die Palette",es:"la paleta"}],["bus","🚌",{en:"bus",fr:"le bus",de:"der Bus",es:"el autobús"}],["computer","💻",{en:"computer",fr:"l'ordinateur",de:"der Computer",es:"el ordenador"}]],
body:[["hand","✋",{en:"hand",fr:"la main",de:"die Hand",es:"la mano"}],["foot","🦶",{en:"foot",fr:"le pied",de:"der Fuß",es:"el pie"}],["eye","👁️",{en:"eye",fr:"l'œil",de:"das Auge",es:"el ojo"}],["ear","👂",{en:"ear",fr:"l'oreille",de:"das Ohr",es:"la oreja"}],["nose","👃",{en:"nose",fr:"le nez",de:"die Nase",es:"la nariz"}],["mouth","👄",{en:"mouth",fr:"la bouche",de:"der Mund",es:"la boca"}],["tooth","🦷",{en:"tooth",fr:"la dent",de:"der Zahn",es:"el diente"}],["leg","🦵",{en:"leg",fr:"la jambe",de:"das Bein",es:"la pierna"}]],
clothes:[["tshirt","👕",{en:"T-shirt",fr:"le tee-shirt",de:"das T-Shirt",es:"la camiseta"}],["dress","👗",{en:"dress",fr:"la robe",de:"das Kleid",es:"el vestido"}],["cap","🧢",{en:"cap",fr:"la casquette",de:"die Mütze",es:"la gorra"}],["shoe","👟",{en:"shoe",fr:"la chaussure",de:"der Schuh",es:"el zapato"}],["sock","🧦",{en:"sock",fr:"la chaussette",de:"die Socke",es:"el calcetín"}],["coat","🧥",{en:"coat",fr:"le manteau",de:"der Mantel",es:"el abrigo"}],["glasses","👓",{en:"glasses",fr:"les lunettes",de:"die Brille",es:"las gafas"}],["trousers","👖",{en:"trousers",fr:"le pantalon",de:"die Hose",es:"el pantalón"}]]};
const YOUNG_THEMES=["animals","fruits","colors","numbers"];
// Propoziții: poziții (subiect + cutie) și culori, cu opțiuni scrise pentru fiecare limbă.
const PREP={en:{words:["on","in","under","next to"],cat:"The cat is ___ the box.",ball:"The ball is ___ the box."},fr:{words:["sur","dans","sous","à côté de"],cat:"Le chat est ___ la boîte.",ball:"Le ballon est ___ la boîte."},de:{words:["auf","in","unter","neben"],cat:"Die Katze ist ___ der Kiste.",ball:"Der Ball ist ___ der Kiste."},es:{words:["sobre","dentro de","debajo de","al lado de"],cat:"El gato está ___ la caja.",ball:"La pelota está ___ la caja."}};
const POS=["on","in","under","next"];
const COLOR_SENT=[["🍎",{en:["The apple is ___.","red",["red","green","blue"]],fr:["La pomme est ___.","rouge",["rouge","verte","bleue"]],de:["Der Apfel ist ___.","rot",["rot","grün","blau"]],es:["La manzana es ___.","roja",["roja","verde","azul"]]}],["🍌",{en:["The banana is ___.","yellow",["yellow","pink","black"]],fr:["La banane est ___.","jaune",["jaune","rose","noire"]],de:["Die Banane ist ___.","gelb",["gelb","rosa","schwarz"]],es:["El plátano es ___.","amarillo",["amarillo","rosa","negro"]]}],["🐸",{en:["The frog is ___.","green",["green","red","white"]],fr:["La grenouille est ___.","verte",["verte","rouge","blanche"]],de:["Der Frosch ist ___.","grün",["grün","rot","weiß"]],es:["La rana es ___.","verde",["verde","roja","blanca"]]}],["🐳",{en:["The whale is ___.","blue",["blue","yellow","brown"]],fr:["La baleine est ___.","bleue",["bleue","jaune","marron"]],de:["Der Wal ist ___.","blau",["blau","gelb","braun"]],es:["La ballena es ___.","azul",["azul","amarilla","marrón"]]}],["🍇",{en:["The grapes are ___.","purple",["purple","orange","white"]],fr:["Le raisin est ___.","violet",["violet","orange","blanc"]],de:["Die Trauben sind ___.","lila",["lila","orange","weiß"]],es:["Las uvas son ___.","moradas",["moradas","naranjas","blancas"]]}],["🐻",{en:["The bear is ___.","brown",["brown","pink","green"]],fr:["L'ours est ___.","brun",["brun","rose","vert"]],de:["Der Bär ist ___.","braun",["braun","rosa","grün"]],es:["El oso es ___.","marrón",["marrón","rosa","verde"]]}]];
// Dialoguri: [replica, [răspuns corect, variante], explicație în limba jocului]
const DIALOG={
meet:{icon:"👋",steps:[{en:["Hello! What's your name?",["My name is Ana.","I am six apples.","Good night!"]],fr:["Bonjour ! Comment tu t'appelles ?",["Je m'appelle Ana.","J'ai six pommes.","Bonne nuit !"]],de:["Hallo! Wie heißt du?",["Ich heiße Ana.","Ich habe sechs Äpfel.","Gute Nacht!"]],es:["¡Hola! ¿Cómo te llamas?",["Me llamo Ana.","Tengo seis manzanas.","¡Buenas noches!"]],g:{ro:"Te întreabă cum te cheamă.",en:"They ask your name.",hu:"Azt kérdezi, hogy hívnak.",uk:"Питають, як тебе звати."}},{en:["How old are you?",["I am seven.","It is blue.","Thank you!"]],fr:["Tu as quel âge ?",["J'ai sept ans.","C'est bleu.","Merci !"]],de:["Wie alt bist du?",["Ich bin sieben.","Es ist blau.","Danke!"]],es:["¿Cuántos años tienes?",["Tengo siete años.","Es azul.","¡Gracias!"]],g:{ro:"Te întreabă câți ani ai.",en:"They ask how old you are.",hu:"Azt kérdezi, hány éves vagy.",uk:"Питають, скільки тобі років."}},{en:["Nice to meet you!",["Nice to meet you too!","I am under the box.","Where is the bus?"]],fr:["Enchanté !",["Enchanté aussi !","Je suis sous la boîte.","Où est le bus ?"]],de:["Schön, dich kennenzulernen!",["Ebenfalls!","Ich bin unter der Kiste.","Wo ist der Bus?"]],es:["¡Mucho gusto!",["¡Igualmente!","Estoy debajo de la caja.","¿Dónde está el autobús?"]],g:{ro:"Se bucură să te cunoască.",en:"They are glad to meet you.",hu:"Örül, hogy megismert.",uk:"Радіють знайомству з тобою."}}]},
shop:{icon:"🛒",steps:[{en:["Good morning! Can I help you?",["An apple, please.","My name is dog.","I am under the table."]],fr:["Bonjour ! Je peux t'aider ?",["Une pomme, s'il vous plaît.","Je m'appelle chien.","Je suis sous la table."]],de:["Guten Morgen! Kann ich dir helfen?",["Einen Apfel, bitte.","Ich heiße Hund.","Ich bin unter dem Tisch."]],es:["¡Buenos días! ¿Te puedo ayudar?",["Una manzana, por favor.","Me llamo perro.","Estoy debajo de la mesa."]],g:{ro:"Vânzătorul întreabă cu ce te poate ajuta.",en:"The shopkeeper asks how they can help.",hu:"Az eladó megkérdezi, miben segíthet.",uk:"Продавець питає, чим допомогти."}},{en:["Here you are. Anything else?",["No, thank you.","Good night, apple.","I am seven."]],fr:["Voilà. Autre chose ?",["Non, merci.","Bonne nuit, pomme.","J'ai sept ans."]],de:["Bitte schön. Sonst noch etwas?",["Nein, danke.","Gute Nacht, Apfel.","Ich bin sieben."]],es:["Aquí tienes. ¿Algo más?",["No, gracias.","Buenas noches, manzana.","Tengo siete años."]],g:{ro:"Te întreabă dacă mai vrei ceva.",en:"They ask if you want anything else.",hu:"Megkérdezi, kérsz-e még valamit.",uk:"Питають, чи хочеш ще щось."}},{en:["That's two euros.",["Here you are.","I like green.","Hello, cat!"]],fr:["Ça fait deux euros.",["Voilà.","J'aime le vert.","Bonjour, chat !"]],de:["Das macht zwei Euro.",["Bitte schön.","Ich mag Grün.","Hallo, Katze!"]],es:["Son dos euros.",["Aquí tiene.","Me gusta el verde.","¡Hola, gato!"]],g:{ro:"Îți spune cât costă.",en:"They tell you the price.",hu:"Megmondja, mennyibe kerül.",uk:"Кажуть, скільки це коштує."}}]},
school:{icon:"🏫",steps:[{en:["Good morning, class! How are you?",["I'm fine, thank you!","I am a pencil.","Two euros."]],fr:["Bonjour, les enfants ! Comment ça va ?",["Ça va bien, merci !","Je suis un crayon.","Deux euros."]],de:["Guten Morgen, Kinder! Wie geht es euch?",["Gut, danke!","Ich bin ein Bleistift.","Zwei Euro."]],es:["¡Buenos días, niños! ¿Cómo estáis?",["¡Bien, gracias!","Soy un lápiz.","Dos euros."]],g:{ro:"Profesoara vă întreabă ce faceți.",en:"The teacher asks how you are.",hu:"A tanár megkérdezi, hogy vagytok.",uk:"Учителька питає, як справи."}},{en:["Can you open your book, please?",["Yes, of course!","It is a frog.","Good night!"]],fr:["Ouvrez votre livre, s'il vous plaît.",["Oui, bien sûr !","C'est une grenouille.","Bonne nuit !"]],de:["Öffnet bitte eure Bücher.",["Ja, gern!","Das ist ein Frosch.","Gute Nacht!"]],es:["Abrid el libro, por favor.",["¡Sí, claro!","Es una rana.","¡Buenas noches!"]],g:{ro:"Vă roagă să deschideți cartea.",en:"They ask you to open your book.",hu:"Arra kér, hogy nyissátok ki a könyvet.",uk:"Просять відкрити книжку."}},{en:["Goodbye! See you tomorrow!",["Goodbye!","Nice to meet you, book!","An apple, please."]],fr:["Au revoir ! À demain !",["Au revoir !","Enchanté, livre !","Une pomme, s'il vous plaît."]],de:["Tschüss! Bis morgen!",["Tschüss!","Schön, dich kennenzulernen, Buch!","Einen Apfel, bitte."]],es:["¡Adiós! ¡Hasta mañana!",["¡Adiós!","Mucho gusto, libro.","Una manzana, por favor."]],g:{ro:"Vă spune la revedere până mâine.",en:"They say goodbye until tomorrow.",hu:"Elköszön holnapig.",uk:"Прощаються до завтра."}}]}};
const INTERVALS=[0,1,3,7,14,30];
const tx=(k,v={})=>String(UI[lang]?.[k]??UI.en[k]??k).replace(/\{(\w+)\}/g,(_,x)=>v[x]??'');const sub=(k,id)=>(UI[lang]?.[k]||UI.en[k])[id];
const E=(tag,text='',cls='')=>{const e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;return e},B=(text,fn,cls)=>{const b=E('button',text,cls);b.type='button';b.onclick=fn;return b};
const rnd=n=>Math.floor(Math.random()*n),pickOne=a=>a[rnd(a.length)];
const uid=()=>localStorage.getItem('garden_active')||'default',key=()=>`garden_langs_${uid()}`,read=()=>{try{return JSON.parse(localStorage.getItem(key()))||{}}catch{return {}}},save=d=>localStorage.setItem(key(),JSON.stringify(d));
const today=()=>new Date().toLocaleDateString('en-CA');const addDays=n=>{const d=new Date();d.setDate(d.getDate()+n);return d.toLocaleDateString('en-CA')};
const group=()=>{const a=ageOf(profile.dob);return a<=5?0:a<=8?1:2};
const target=()=>{const t=read().target;return TARGETS[t]?t:(lang==='en'?'fr':'en')};
const wordOf=item=>item[2][target()];
const bare=w=>w.replace(/^(le |la |les |l'|der |die |das |el |la |las |los )/i,'');
const itemsOf=theme=>V[theme].map(it=>({theme,id:it[0],show:it[1],words:it[2]}));
const allItems=()=>Object.keys(V).flatMap(itemsOf);
// ——— Voce în limba învățată
const voices=()=>('speechSynthesis'in window)?speechSynthesis.getVoices():[];
const hasVoice=t=>voices().some(v=>v.lang.toLowerCase().replace('_','-').startsWith(t));
if('speechSynthesis'in window&&speechSynthesis.addEventListener)speechSynthesis.addEventListener('voiceschanged',()=>{if(!section.hidden&&mode&&!stage?.dataset.busy)section.querySelectorAll('.lang-novoice').forEach(n=>n.hidden=hasVoice(target()))});
function say(text,t=target()){if(!('speechSynthesis'in window)||!text)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=TARGETS[t].voice;const v=voices().find(x=>x.lang.toLowerCase().replace('_','-').startsWith(t));if(v)u.voice=v;u.rate=.85;speechSynthesis.speak(u)}
function hearBtn(text){const b=B(tx('hear'),()=>say(text),'lang-hear');return b}
function noVoiceNote(){const n=E('p',tx('noVoice',{lang:sub('langs',target())}),'small lang-novoice');n.hidden=hasVoice(target());return n}
// ——— Afișarea unui cuvânt: emoji, culoare sau buline
function visual(it,big){if(it.theme==='colors'){const s=E('span','','lang-swatch'+(big?' big':''));s.style.background=it.show;s.dataset.c=it.id;s.setAttribute('role','img');s.setAttribute('aria-label',sub('colorNames',it.id));return s}if(it.theme==='numbers'){const s=E('span','','lang-dots'+(big?' big':''));for(let i=0;i<it.show;i++)s.append(E('i'));s.setAttribute('role','img');s.setAttribute('aria-label',String(it.show));return s}const s=E('span',it.show,'lang-emoji'+(big?' big':''));return s}
// ——— Progres: văzute și repetare spațiată
function markSeen(it){const d=read();d.seen=d.seen||{};d.seen[`${target()}:${it.theme}:${it.id}`]=today();save(d)}
function learnedCount(){const d=read(),t=target();return Object.entries(d.srs||{}).filter(([k,v])=>k.startsWith(t+':')&&v.box>=2).length}
const section=E('section','','card languages');section.id='languages';section.dataset.view='languages';$('app').insertBefore(section,$('birthday'));
let mode=null,stage,status,theme='animals',scenario=null,step=0,dailyState=null;
function win(g,msg){status.textContent=msg||tx('well');gardenCelebrate('lang-'+g)}
function wrong(g){status.textContent=tx('retry');gardenMiss('lang-'+g)}
function nextBtn(fn){stage.append(B(tx('next'),fn||(()=>render()),'primary'))}
function themeChips(){const themes=group()===0?YOUNG_THEMES:Object.keys(V);if(!themes.includes(theme))theme=themes[0];const row=E('div','','lang-themes');row.setAttribute('role','group');row.setAttribute('aria-label',tx('theme'));themes.forEach(k=>{const b=B(sub('themes',k),()=>{theme=k;render()});b.setAttribute('aria-pressed',theme===k);row.append(b)});return row}
// ——— 1. Ascultă și atinge
function listen(){stage.append(themeChips(),E('p',tx('listenHelp')));const items=itemsOf(theme),n=group()===0?3:4,it=pickOne(items),opts=shuffle([it,...shuffle(items.filter(x=>x.id!==it.id)).slice(0,n-1)]),w=wordOf(V[theme].find(x=>x[0]===it.id));const top=E('div','','lang-prompt');top.append(hearBtn(w));const word=E('strong',w,'lang-word');if(group()===0&&hasVoice(target()))word.hidden=true;top.append(word);stage.append(top,noVoiceNote());const row=E('div','','lang-options');opts.forEach(o=>{const b=B('',()=>{if(o.id===it.id){row.querySelectorAll('button').forEach(x=>x.disabled=true);b.classList.add('right');word.hidden=false;markSeen(it);say(w);win('listen');nextBtn()}else{b.classList.add('shake');setTimeout(()=>b.classList.remove('shake'),350);wrong('listen')}},'lang-option');b.append(visual(o,true));row.append(b)});stage.append(row);if(hasVoice(target()))setTimeout(()=>say(w),350)}
// ——— 2. Memory cu cuvinte
function memory(){stage.append(themeChips(),E('p',tx('memoryHelp')));const pairs=group()===2?6:4,items=shuffle(itemsOf(theme)).slice(0,pairs),cards=shuffle(items.flatMap(it=>[{it,kind:'pic'},{it,kind:'word'}]));let open=[],found=new Set(),busy=false;const grid=E('div','','lang-memory');grid.style.setProperty('--cols',4);stage.append(grid);
const draw=()=>{grid.replaceChildren(...cards.map((c,i)=>{const shown=open.includes(i)||found.has(c.it.id),b=B('',()=>flip(i),'lang-card'+(shown?' shown':'')+(found.has(c.it.id)?' found':''));if(shown){if(c.kind==='pic')b.append(visual(c.it));else b.append(E('span',wordOf(V[theme].find(x=>x[0]===c.it.id)),'lang-card-word'))}else b.textContent='?';b.disabled=found.has(c.it.id);b.setAttribute('aria-label',found.has(c.it.id)?`${c.kind==='word'?wordOf(V[theme].find(x=>x[0]===c.it.id)):''} ${tx('pair')}`.trim():tx('card',{n:i+1}));return b}))};
function flip(i){if(busy||open.includes(i)||found.has(cards[i].it.id))return;open.push(i);const c=cards[i];if(c.kind==='word')say(wordOf(V[theme].find(x=>x[0]===c.it.id)));draw();if(open.length<2)return;const [a,b]=open.map(j=>cards[j]);if(a.it.id===b.it.id&&a.kind!==b.kind){found.add(a.it.id);markSeen(a.it);open=[];window.gardenSound?.('pop');draw();if(found.size===pairs){win('memory');nextBtn()}}else{busy=true;wrong('memory');setTimeout(()=>{open=[];busy=false;draw()},900)}}
draw()}
// ——— 3. Scrie cuvântul
function spell(){stage.append(themeChips(),E('p',tx('spellHelp')));const ok=itemsOf(theme).filter(it=>{const w=bare(wordOf(V[theme].find(x=>x[0]===it.id)));return /^[\p{L}]{3,9}$/u.test(w)});if(!ok.length){theme='animals';return render()}const it=pickOne(ok),full=wordOf(V[theme].find(x=>x[0]===it.id)),letters=[...bare(full).toUpperCase()];let pos=group()===1?1:0;const top=E('div','','lang-prompt');top.append(visual(it,true),hearBtn(full));stage.append(top,noVoiceNote());const slots=E('div','','lang-slots');const paint=()=>slots.replaceChildren(...letters.map((l,i)=>E('span',i<pos?l:'_',i<pos?'filled':'')));paint();const row=E('div','','lang-letters');shuffle(letters.map((l,i)=>({l,i}))).forEach(({l,i})=>{if(i<pos)return;const b=B(l,()=>{if(l===letters[pos]){b.disabled=true;b.classList.add('used');pos++;paint();window.gardenSound?.('pop');if(pos===letters.length){row.querySelectorAll('button').forEach(x=>x.disabled=true);markSeen(it);say(full);win('spell');nextBtn()}}else{b.classList.add('shake');setTimeout(()=>b.classList.remove('shake'),350);wrong('spell')}},'lang-letter');row.append(b)});stage.append(slots,row)}
// ——— 4. Propoziții
function sentence(){stage.append(E('p',tx('sentenceHelp')));const t=target();if(Math.random()<.5){const subj=pickOne(['cat','ball']),p=rnd(4),P=PREP[t],text=P[subj];const scene=E('div','','lang-scene pos-'+POS[p]);scene.append(E('span','📦','box'),E('span',subj==='cat'?'🐱':'⚽','subj'));scene.setAttribute('role','img');scene.setAttribute('aria-label',text.replace('___',P.words[p]));stage.append(scene,E('p',text,'lang-sentence'),hearBtn(text.replace('___','…')),noVoiceNote());const row=E('div','','lang-choices');shuffle(P.words.map((w,i)=>({w,i}))).forEach(({w,i})=>{const b=B(w,()=>{if(i===p){row.querySelectorAll('button').forEach(x=>x.disabled=true);const full=text.replace('___',w);say(full);win('sentence',tx('sentenceDone',{s:full}));nextBtn()}else wrong('sentence')});row.append(b)});stage.append(row)}else{const [icon,byLang]=pickOne(COLOR_SENT),[text,ans,opts]=byLang[t];stage.append(E('div',icon,'lang-emoji big'),E('p',text,'lang-sentence'),hearBtn(text.replace('___','…')),noVoiceNote());const row=E('div','','lang-choices');shuffle([...opts]).forEach(w=>{const b=B(w,()=>{if(w===ans){row.querySelectorAll('button').forEach(x=>x.disabled=true);const full=text.replace('___',w);say(full);win('sentence',tx('sentenceDone',{s:full}));nextBtn()}else wrong('sentence')});row.append(b)});stage.append(row)}}
// ——— 5. Dialoguri
function dialog(){const t=target();if(!scenario){stage.append(E('p',tx('dialogHelp')),E('h3',tx('scenario')));const row=E('div','','lang-choices');Object.entries(DIALOG).forEach(([k,s])=>row.append(B(`${s.icon} ${sub('scenarios',k)}`,()=>{scenario=k;step=0;render()})));stage.append(row);return}
const S=DIALOG[scenario],st=S.steps[step],[line,opts]=st[t];stage.append(E('div',`${S.icon} ${sub('scenarios',scenario)} · ${step+1}/${S.steps.length}`,'eyebrow'));const bubble=E('div','','lang-bubble');bubble.append(E('span','🧑','who'),E('span',line));stage.append(bubble,hearBtn(line),noVoiceNote());const row=E('div','','lang-choices dialog');shuffle(opts.map((o,i)=>({o,i}))).forEach(({o,i})=>{const b=B(o,()=>{if(i===0){row.querySelectorAll('button').forEach(x=>x.disabled=true);b.classList.add('right');say(o);stage.append(E('p',tx('meaning',{g:st.g[lang]||st.g.en}),'lang-gloss'));if(step<S.steps.length-1){status.textContent=tx('well');nextBtn(()=>{step++;render()})}else{win('dialog',tx('done'));stage.append(B(tx('again'),()=>{step=0;render()}),B(tx('scenario'),()=>{scenario=null;render()}))}}else wrong('dialog')});row.append(b)});stage.append(row)}
// ——— 6. Cuvintele zilei (repetare spațiată)
function planToday(){const d=read(),t=target(),srs=d.srs||{},all=allItems().filter(it=>group()>0||YOUNG_THEMES.includes(it.theme));const due=all.filter(it=>{const s=srs[`${t}:${it.theme}:${it.id}`];return s&&s.due<=today()}).slice(0,5);const fresh=shuffle(all.filter(it=>!srs[`${t}:${it.theme}:${it.id}`])).slice(0,5-due.length);return{words:[...due,...fresh],review:due.length}}
function daily(){stage.append(E('p',tx('dailyHelp')));const d=read();if(d.dailyDone===`${target()}:${today()}`&&!dailyState){stage.append(E('p',tx('dailyDone'),'lang-done'),B(tx('dailyAgain'),()=>{dailyState={...planToday(),i:0,phase:'cards'};render()}));return}
if(!dailyState)dailyState={...planToday(),i:0,phase:'cards'};const S=dailyState;if(!S.words.length){stage.append(E('p',tx('dailyDone'),'lang-done'));return}
if(S.i===0&&S.phase==='cards')stage.append(E('p',tx('dailyPlan',{n:S.words.length,r:S.review}),'progress'));
const it=S.words[S.i],w=it.words[target()];
if(S.phase==='cards'){stage.append(E('div',`${S.i+1}/${S.words.length}`,'eyebrow'));const card=E('div','','lang-flash');card.append(visual(it,true),E('strong',w,'lang-word'));stage.append(card,hearBtn(w),noVoiceNote(),B(tx('know'),()=>{S.i++;if(S.i>=S.words.length){S.i=0;S.phase='quiz'}render()},'primary'));say(w);return}
if(S.i===0)stage.append(E('p',tx('quiz'),'progress'));stage.append(E('div',`${S.i+1}/${S.words.length}`,'eyebrow'));const top=E('div','','lang-prompt');top.append(hearBtn(w),E('strong',w,'lang-word'));stage.append(top);const pool=itemsOf(it.theme).filter(x=>x.id!==it.id),opts=shuffle([it,...shuffle(pool).slice(0,2)]);const row=E('div','','lang-options');let missed=false;opts.forEach(o=>{const b=B('',()=>{const dd=read();dd.srs=dd.srs||{};const k=`${target()}:${it.theme}:${it.id}`,cur=dd.srs[k]||{box:0};if(o.id===it.id){row.querySelectorAll('button').forEach(x=>x.disabled=true);b.classList.add('right');const box=missed?1:Math.min(5,cur.box+1);dd.srs[k]={box,due:addDays(INTERVALS[box])};save(dd);say(w);S.i++;if(S.i>=S.words.length){dd.dailyDone=`${target()}:${today()}`;save(dd);dailyState=null;win('daily',tx('dailyDone'));stage.append(E('p',tx('learned',{lang:sub('langs',target()),n:learnedCount()}),'progress'),B(tx('dailyAgain'),()=>{dailyState={...planToday(),i:0,phase:'cards'};render()}))}else{status.textContent=tx('well');nextBtn(()=>render())}}else{missed=true;b.classList.add('shake');setTimeout(()=>b.classList.remove('shake'),350);dd.srs[k]={box:1,due:addDays(1)};save(dd);wrong('daily')}},'lang-option');b.append(visual(o,true));row.append(b)});stage.append(row)}
const MODES=()=>group()===0?['listen','daily']:group()===1?['listen','memory','spell','daily']:['listen','memory','spell','sentence','dialog','daily'];
function render(){if(!profile||$('app').hidden)return;const modes=MODES();if(!modes.includes(mode))mode=modes[0];section.replaceChildren(E('h2',tx('title')),E('p',tx('intro')));
const langRow=E('div','','lang-targets');langRow.setAttribute('role','group');langRow.setAttribute('aria-label',tx('learn'));langRow.append(E('strong',tx('learn')));Object.keys(TARGETS).forEach(t=>{const b=B(`${TARGETS[t].flag} ${sub('langs',t)}`,()=>{const d=read();d.target=t;save(d);dailyState=null;scenario=null;render()});b.setAttribute('aria-pressed',target()===t);langRow.append(b)});section.append(langRow,E('p',tx('learned',{lang:sub('langs',target()),n:learnedCount()}),'lang-learned'));
const tabs=E('div','','learning-tabs lang-tabs');const icons={listen:'👂',memory:'🃏',spell:'🔤',sentence:'📝',dialog:'💬',daily:'📅'};modes.forEach(k=>{const b=B(`${icons[k]} ${tx(k)}`,()=>{mode=k;if(k!=='dialog')scenario=null;if(k!=='daily')dailyState=null;render()});b.setAttribute('aria-pressed',mode===k);tabs.append(b)});section.append(tabs);
stage=E('div','','learning-stage lang-stage');stage.lang=target();status=E('div','','learning-feedback');status.setAttribute('role','status');status.setAttribute('aria-live','polite');section.append(stage);({listen,memory,spell,sentence,dialog,daily})[mode]();section.append(status)}
window.gardenForeign={read,learnedCount,targets:Object.keys(TARGETS)};
gardenOn(r=>{if(r!=='lang'){dailyState=null;scenario=null}render()});if(profile)render();
})();
