// Grădina Curioasă — recompense: abțibilduri, grădina care crește, insigne, ghidul Bia, sunete, statistici.
(()=>{
const R={
ro:{collection:'Colecția mea',intro:'Fiecare reușită aduce ceva nou: abțibilduri, flori și insigne.',stickers:'Abțibilduri',garden:'Grădina mea',badges:'Insigne',count:'{n} din {t} abțibilduri',board:'Pajiștea ta',boardHelp:'Trage abțibildurile pe pajiște. Poți și să atingi un abțibild, apoi locul unde îl vrei. Săgețile îl mută, Delete îl scoate.',placed:'Ai pus {s} pe pajiște.',removed:'Ai scos abțibildul.',tray:'Abțibildurile tale',none:'Rezolvă provocări și primești primul abțibild!',locked:'Abțibild încă ascuns',gardenHelp:'Fiecare reușită udă grădina. La fiecare 6 reușite înflorește o floare.',nextFlower:'Încă {n} reușite până înflorește următoarea floare.',flowers:'Flori înflorite: {n}',earned:'Câștigată',notYet:'Încă nu',newSticker:'Abțibild nou: {s}!',newBadge:'Insignă nouă: {b}!',bloom:'A înflorit o floare în grădina ta! 🌸',hello:'Bună, {name}! Eu sunt Bia. Hai să descoperim ceva azi!',helloAnon:'Bună! Eu sunt Bia, buburuza. Hai să descoperim ceva azi!',praise:['Bravo! Ai descoperit!','Ce bine ai gândit!','Super, încă o reușită!','Ai răbdare și atenție. Minunat!','Uau! Grădina ta crește!'],encourage:['Nicio grabă. Privește încă o dată.','Greșelile ne ajută să învățăm. Mai încearcă!','Respiră adânc și alege din nou.','Poți apăsa 🔊 ca să asculți din nou.'],tips:['Atinge-mă oricând pentru un sfat!','În Colecția mea găsești abțibildurile tale.','În Descoperă sunt povești cu mai multe finaluri.','Fiecare reușită udă florile din grădină.'],guide:'Bia, ghidul tău',hide:'Ascunde',b:{first:['Prima descoperire','Prima provocare rezolvată'],w10:['Explorator','10 reușite'],w50:['Explorator curajos','50 de reușite'],w100:['Mare explorator','100 de reușite'],numbers:['Prieten cu numerele','10 reușite la numere'],logic:['Mic logician','10 reușite la logică'],attention:['Ochi de vultur','10 reușite la atenție și memorie'],world:['Curios de lume','10 reușite despre lumea din jur'],language:['Iubitor de litere','10 reușite la litere și povești'],orientation:['Busola vie','10 reușite la trasee'],creativity:['Artist','10 creații'],streak3:['Trei zile la rând','Ai jucat 3 zile diferite'],streak7:['O săptămână de joacă','Ai jucat 7 zile diferite'],stick10:['Colecționar','10 abțibilduri'],stickAll:['Albumul complet','Toate abțibildurile'],brave:['Nu renunț','Ai reușit după 3 încercări'],tales:['Povestitor','Ai găsit toate finalurile']}},
en:{collection:'My collection',intro:'Every success brings something new: stickers, flowers and badges.',stickers:'Stickers',garden:'My garden',badges:'Badges',count:'{n} of {t} stickers',board:'Your meadow',boardHelp:'Drag stickers onto the meadow. You can also tap a sticker, then the place you want. Arrow keys move it, Delete removes it.',placed:'You put {s} on the meadow.',removed:'Sticker removed.',tray:'Your stickers',none:'Solve challenges to get your first sticker!',locked:'Sticker still hidden',gardenHelp:'Every success waters the garden. Every 6 successes, a flower blooms.',nextFlower:'{n} more successes until the next flower blooms.',flowers:'Flowers in bloom: {n}',earned:'Earned',notYet:'Not yet',newSticker:'New sticker: {s}!',newBadge:'New badge: {b}!',bloom:'A flower bloomed in your garden! 🌸',hello:'Hi, {name}! I’m Bia. Let’s discover something today!',helloAnon:'Hi! I’m Bia the ladybug. Let’s discover something today!',praise:['Well done! You found it!','Great thinking!','Super, another success!','Patient and careful. Wonderful!','Wow! Your garden is growing!'],encourage:['No rush. Look once more.','Mistakes help us learn. Try again!','Take a deep breath and choose again.','You can tap 🔊 to listen again.'],tips:['Tap me any time for a tip!','Your stickers are in My collection.','Discover has stories with more than one ending.','Every success waters the flowers in your garden.'],guide:'Bia, your guide',hide:'Hide',b:{first:['First discovery','First challenge solved'],w10:['Explorer','10 successes'],w50:['Brave explorer','50 successes'],w100:['Great explorer','100 successes'],numbers:['Number friend','10 number successes'],logic:['Little logician','10 logic successes'],attention:['Eagle eye','10 attention and memory successes'],world:['Curious about the world','10 world successes'],language:['Letter lover','10 letters and stories successes'],orientation:['Living compass','10 route successes'],creativity:['Artist','10 creations'],streak3:['Three days','Played on 3 different days'],streak7:['A week of play','Played on 7 different days'],stick10:['Collector','10 stickers'],stickAll:['Complete album','All the stickers'],brave:['I don’t give up','Succeeded after 3 tries'],tales:['Storyteller','Found every story ending']}},
hu:{collection:'A gyűjteményem',intro:'Minden siker hoz valami újat: matricákat, virágokat és jelvényeket.',stickers:'Matricák',garden:'A kertem',badges:'Jelvények',count:'{n} / {t} matrica',board:'A te réted',boardHelp:'Húzd a matricákat a rétre. Megérintheted a matricát is, aztán a helyét. A nyilak mozgatják, a Delete leveszi.',placed:'Feltetted a rétre: {s}.',removed:'A matrica lekerült.',tray:'A matricáid',none:'Oldj meg feladatokat, és megkapod az első matricát!',locked:'Még rejtett matrica',gardenHelp:'Minden siker megöntözi a kertet. Minden 6 siker után kinyílik egy virág.',nextFlower:'Még {n} siker, és kinyílik a következő virág.',flowers:'Kinyílt virágok: {n}',earned:'Megszerezve',notYet:'Még nem',newSticker:'Új matrica: {s}!',newBadge:'Új jelvény: {b}!',bloom:'Kinyílt egy virág a kertedben! 🌸',hello:'Szia, {name}! Bia vagyok. Fedezzünk fel ma valamit!',helloAnon:'Szia! Bia vagyok, a katica. Fedezzünk fel ma valamit!',praise:['Ügyes! Rájöttél!','Milyen jól gondolkodtál!','Szuper, még egy siker!','Türelmes és figyelmes vagy. Csodás!','Hűha! Nő a kerted!'],encourage:['Nem kell sietni. Nézd meg még egyszer.','A hibákból tanulunk. Próbáld újra!','Vegyél egy mély levegőt, és válassz újra.','A 🔊 gombbal újra meghallgathatod.'],tips:['Érints meg bármikor egy tippért!','A matricáidat A gyűjteményemben találod.','A Felfedezésben több befejezésű mesék vannak.','Minden siker megöntözi a kerted virágait.'],guide:'Bia, a vezetőd',hide:'Elrejtés',b:{first:['Első felfedezés','Az első megoldott feladat'],w10:['Felfedező','10 siker'],w50:['Bátor felfedező','50 siker'],w100:['Nagy felfedező','100 siker'],numbers:['A számok barátja','10 siker a számokkal'],logic:['Kis logikus','10 siker a logikában'],attention:['Sasszem','10 siker a figyelemben és memóriában'],world:['Kíváncsi a világra','10 siker a világról'],language:['Betűbarát','10 siker a betűkkel és mesékkel'],orientation:['Élő iránytű','10 siker az útvonalakkal'],creativity:['Művész','10 alkotás'],streak3:['Három nap','3 különböző napon játszottál'],streak7:['Egy hét játék','7 különböző napon játszottál'],stick10:['Gyűjtő','10 matrica'],stickAll:['Teljes album','Az összes matrica'],brave:['Nem adom fel','3 próbálkozás után sikerült'],tales:['Mesemondó','Megtaláltad az összes befejezést']}},
uk:{collection:'Моя колекція',intro:'Кожен успіх приносить щось нове: наліпки, квіти й значки.',stickers:'Наліпки',garden:'Мій сад',badges:'Значки',count:'{n} з {t} наліпок',board:'Твоя галявина',boardHelp:'Перетягни наліпки на галявину. Можна також торкнутися наліпки, а потім місця. Стрілки її рухають, Delete прибирає.',placed:'Ти поклав(-ла) {s} на галявину.',removed:'Наліпку прибрано.',tray:'Твої наліпки',none:'Розв’язуй завдання й отримаєш першу наліпку!',locked:'Наліпка ще прихована',gardenHelp:'Кожен успіх поливає сад. Кожні 6 успіхів розквітає квітка.',nextFlower:'Ще {n} успіхів — і розквітне наступна квітка.',flowers:'Розквітлих квітів: {n}',earned:'Отримано',notYet:'Ще ні',newSticker:'Нова наліпка: {s}!',newBadge:'Новий значок: {b}!',bloom:'У твоєму саду розквітла квітка! 🌸',hello:'Привіт, {name}! Я Бія. Давай сьогодні щось відкриємо!',helloAnon:'Привіт! Я Бія, сонечко. Давай сьогодні щось відкриємо!',praise:['Молодець! Ти знайшов(-ла)!','Як добре ти подумав(-ла)!','Супер, ще один успіх!','Терпляче й уважно. Чудово!','Ого! Твій сад росте!'],encourage:['Не поспішай. Подивися ще раз.','Помилки допомагають вчитися. Спробуй ще!','Глибоко вдихни й обери знову.','Натисни 🔊, щоб послухати ще раз.'],tips:['Торкнися мене будь-коли, щоб отримати пораду!','Твої наліпки — у Моїй колекції.','У Відкритті є казки з кількома кінцівками.','Кожен успіх поливає квіти у твоєму саду.'],guide:'Бія, твоя провідниця',hide:'Сховати',b:{first:['Перше відкриття','Перше розв’язане завдання'],w10:['Дослідник','10 успіхів'],w50:['Сміливий дослідник','50 успіхів'],w100:['Великий дослідник','100 успіхів'],numbers:['Друг чисел','10 успіхів із числами'],logic:['Маленький логік','10 успіхів у логіці'],attention:['Орлине око','10 успіхів в уважності й пам’яті'],world:['Цікавий до світу','10 успіхів про світ довкола'],language:['Любитель літер','10 успіхів із літерами й казками'],orientation:['Жива компас','10 успіхів із маршрутами'],creativity:['Митець','10 творінь'],streak3:['Три дні','Грав(-ла) у 3 різні дні'],streak7:['Тиждень гри','Грав(-ла) у 7 різних днів'],stick10:['Колекціонер','10 наліпок'],stickAll:['Повний альбом','Усі наліпки'],brave:['Я не здаюся','Вдалося після 3 спроб'],tales:['Оповідач','Знайдено всі кінцівки']}}};
Object.assign(R,window.gardenLangs?.rewards||{});
const tx=(k,v={})=>String(R[lang]?.[k]??R.en[k]??k).replace(/\{(\w+)\}/g,(_,x)=>v[x]??'');const list=k=>R[lang]?.[k]||R.en[k];const badgeText=id=>(R[lang]?.b||R.en.b)[id];
const STICKERS=['🦋','🐞','🐝','🐢','🐙','🦊','🐼','🐨','🦁','🐸','🐧','🦉','🐳','🐬','🦄','🌈','⭐','🌙','☀️','🌸','🌻','🌵','🍄','🍓','🍉','🍩','🧁','🍭','🎈','🎨','🎸','🚀','🚂','🚲','⛵','🏰','🎁','🔮','🎠','💎'];
const SKILL={count:'numbers',math:'numbers',fractions:'numbers',portion:'numbers',numbers:'numbers',money:'numbers',pattern:'logic',logic:'logic',craft:'logic',order:'logic',mission:'logic',plan:'logic',puzzle:'logic',sort:'attention',shadow:'attention',match:'attention',memory:'attention',season:'world',colors:'world',clock:'world',event:'world',letters:'language',tale:'language',story:'language',route:'orientation',unicorn:'orientation',cars:'orientation',cupcake:'creativity',rocket:'creativity',birthday:'creativity'};
const SKILLS=['numbers','logic','attention','world','language','orientation','creativity'];
const E=(tag,text='',cls='')=>{const e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;return e},B=(text,fn,cls)=>{const b=E('button',text,cls);b.type='button';b.onclick=fn;return b};
const uid=()=>localStorage.getItem('garden_active')||'default',key=()=>`garden_rewards_${uid()}`,read=()=>{try{return JSON.parse(localStorage.getItem(key()))||{}}catch{return {}}},save=d=>localStorage.setItem(key(),JSON.stringify(d));
const today=()=>new Date().toLocaleDateString('en-CA');const settings=()=>{try{return JSON.parse(localStorage.getItem('garden_settings'))||{}}catch{return {}}};
const totalWins=d=>Object.values(d.stats||{}).reduce((a,s)=>a+(s.w||0),0);
const skillWins=(d,s)=>Object.entries(d.stats||{}).filter(([g])=>(SKILL[g]||'world')===s).reduce((a,[,v])=>a+(v.w||0),0);
function talesDone(){try{const d=JSON.parse(localStorage.getItem(`garden_discover_${uid()}`))||{};return (d.endings||[]).length>=7}catch{return false}}
const BADGES=[['first','🌱',d=>totalWins(d)>=1],['w10','🏅',d=>totalWins(d)>=10],['w50','🥈',d=>totalWins(d)>=50],['w100','🏆',d=>totalWins(d)>=100],['numbers','🔢',d=>skillWins(d,'numbers')>=10],['logic','🧩',d=>skillWins(d,'logic')>=10],['attention','👀',d=>skillWins(d,'attention')>=10],['world','🌍',d=>skillWins(d,'world')>=10],['language','🔤',d=>skillWins(d,'language')>=10],['orientation','🧭',d=>skillWins(d,'orientation')>=10],['creativity','🎨',d=>skillWins(d,'creativity')>=10],['streak3','📅',d=>Object.keys(d.days||{}).length>=3],['streak7','🗓️',d=>Object.keys(d.days||{}).length>=7],['stick10','📒',d=>(d.stickers||[]).length>=10],['stickAll','📚',d=>(d.stickers||[]).length>=STICKERS.length],['brave','💪',d=>!!d.brave],['tales','📖',()=>talesDone()]];
// ——— Sunete sintetizate (fără fișiere audio), doar când „Efecte sonore” e pornit.
let actx=null;function tone(freq,start,dur,type='triangle',vol=.06){const t=actx.currentTime+start,o=actx.createOscillator(),g=actx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(vol,t+.02);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(actx.destination);o.start(t);o.stop(t+dur+.05)}
function sound(type){if(!settings().sound)return;try{actx=actx||new (window.AudioContext||window.webkitAudioContext)();if(actx.state==='suspended')actx.resume();({win:()=>{tone(523,0,.18);tone(659,.1,.18);tone(784,.2,.32)},miss:()=>{tone(330,0,.16,'sine',.04);tone(262,.12,.22,'sine',.04)},pop:()=>tone(880,0,.08,'sine',.05),sticker:()=>{[988,1319,1568,2093].forEach((f,i)=>tone(f,i*.07,.14,'sine',.035))},badge:()=>{[523,659,784,1047].forEach((f,i)=>tone(f,i*.12,.3))}})[type]?.()}catch{}}
window.gardenSound=sound;
// ——— Ghidul Bia
const guide=E('div','','guide');const guideBtn=B('',()=>say(pickOne(list('tips'))),'guide-btn');guideBtn.append(gardenArt('ladybug',52));guideBtn.setAttribute('aria-label',tx('guide'));const bubble=E('div','','guide-bubble');bubble.setAttribute('role','status');bubble.setAttribute('aria-live','polite');const hideBtn=B('×',()=>{bubble.classList.remove('show')},'guide-close');hideBtn.setAttribute('aria-label',tx('hide'));bubble.append(E('span'),hideBtn);guide.append(bubble,guideBtn);document.body.append(guide);let bubbleTimer=0;
const pickOne=a=>a[Math.floor(Math.random()*a.length)];
function say(text,ms=4500){if(settings().guide===false)return;bubble.firstChild.textContent=text;bubble.classList.add('show');clearTimeout(bubbleTimer);bubbleTimer=setTimeout(()=>bubble.classList.remove('show'),ms)}
function guideVisible(){guide.hidden=!profile||$('app').hidden||settings().guide===false;guideBtn.setAttribute('aria-label',tx('guide'));hideBtn.setAttribute('aria-label',tx('hide'))}
window.gardenGuideSay=say;window.gardenGuideRefresh=guideVisible;
// ——— Evenimente de joc
let missStreak=0,lastTouch=Date.now();
document.addEventListener('garden:win',e=>{if(!profile)return;const g=e.detail.game||'other',d=read();d.stats=d.stats||{};d.stats[g]=d.stats[g]||{w:0,m:0};d.stats[g].w++;d.stats[g].last=today();if(missStreak>=3)d.brave=true;missStreak=0;const before=new Set(d.earned||[]);d.since=(d.since||0)+1;let msg=pickOne(list('praise')),snd='win';d.stickers=d.stickers||[];if(d.since>=2&&d.stickers.length<STICKERS.length){d.since=0;const s=pickOne(STICKERS.filter(x=>!d.stickers.includes(x)));d.stickers.push(s);msg=tx('newSticker',{s});snd='sticker'}const t=totalWins(d);if(t>0&&t%6===0)msg=tx('bloom');d.earned=BADGES.filter(([,,test])=>test(d)).map(([id])=>id);const fresh=d.earned.filter(id=>!before.has(id));if(fresh.length){msg=tx('newBadge',{b:badgeText(fresh[0])[0]});snd='badge'}save(d);sound(snd);say(msg);if(!section.hidden)draw()});
document.addEventListener('garden:miss',e=>{if(!profile)return;const g=e.detail.game||'other',d=read();d.stats=d.stats||{};d.stats[g]=d.stats[g]||{w:0,m:0};d.stats[g].m++;save(d);missStreak++;sound('miss');if(missStreak===3||missStreak===6)say(pickOne(list('encourage')))});
['pointerdown','keydown'].forEach(ev=>addEventListener(ev,()=>lastTouch=Date.now(),{passive:true}));
// Timp de joc: numără doar când pagina e vizibilă și copilul a interacționat în ultimul minut.
setInterval(()=>{if(!profile||$('app').hidden||document.visibilityState!=='visible'||Date.now()-lastTouch>60000)return;const d=read();d.days=d.days||{};d.days[today()]=(d.days[today()]||0)+15;save(d);document.dispatchEvent(new CustomEvent('garden:tick',{detail:{seconds:d.days[today()]}}))},15000);
window.gardenRewards={read,SKILL,SKILLS,skillOf:g=>SKILL[g]||'world',totalWins};
// ——— Ecranul „Colecția mea”
const section=E('section','','card collection');section.id='collection';section.dataset.view='collection';$('app').insertBefore(section,$('birthday'));let tab='stickers',chosen=null;
function stickersTab(box){const d=read(),have=d.stickers||[],placed=d.placed||{};box.append(E('p',tx('count',{n:have.length,t:STICKERS.length}),'progress'));
const board=E('div','','sticker-board');board.tabIndex=0;board.setAttribute('role','application');board.setAttribute('aria-label',tx('board'));box.append(E('h3',tx('board')),E('p',tx('boardHelp'),'small'),board);
const put=(s,x,y)=>{const dd=read();dd.placed=dd.placed||{};dd.placed[s]=[Math.max(4,Math.min(96,x)),Math.max(6,Math.min(94,y))];save(dd)};
Object.entries(placed).forEach(([s,[x,y]])=>{const el=B(s,()=>{chosen=s;board.focus();mark()},'sticker placed');el.style.left=x+'%';el.style.top=y+'%';el.dataset.s=s;el.setAttribute('aria-label',s);drag(el,s);board.append(el)});
const tray=E('div','','sticker-tray');tray.setAttribute('aria-label',tx('tray'));const loose=have.filter(s=>!placed[s]);if(!have.length)tray.append(E('p',tx('none')));loose.forEach(s=>{const el=B(s,()=>{chosen=chosen===s?null:s;mark()},'sticker');el.dataset.s=s;el.setAttribute('aria-label',s);drag(el,s);tray.append(el)});box.append(E('h3',tx('tray')),tray);
const album=E('div','','sticker-album');STICKERS.forEach(s=>{const got=have.includes(s),c=E('span',got?s:'?','sticker-slot'+(got?' got':''));c.setAttribute('aria-label',got?s:tx('locked'));album.append(c)});box.append(album);
function mark(){box.querySelectorAll('.sticker').forEach(el=>el.setAttribute('aria-pressed',el.dataset.s===chosen))}mark();
board.onclick=e=>{if(!chosen||e.target.closest('.sticker.placed')&&e.target.closest('.sticker.placed').dataset.s!==chosen)return;if(e.target.closest('.sticker.placed'))return;const r=board.getBoundingClientRect();put(chosen,(e.clientX-r.left)/r.width*100,(e.clientY-r.top)/r.height*100);say(tx('placed',{s:chosen}),2500);sound('pop');chosen=null;draw()};
board.onkeydown=e=>{if(!chosen)return;const dd=read(),p=dd.placed?.[chosen];const moves={ArrowLeft:[-4,0],ArrowRight:[4,0],ArrowUp:[0,-4],ArrowDown:[0,4]};if(e.key==='Enter'&&!p){put(chosen,50,50);sound('pop');draw();return}if(!p)return;if(moves[e.key]){e.preventDefault();put(chosen,p[0]+moves[e.key][0],p[1]+moves[e.key][1]);const keep=chosen;draw();chosen=keep;section.querySelector('.sticker-board')?.focus();section.querySelectorAll('.sticker').forEach(el=>el.setAttribute('aria-pressed',el.dataset.s===chosen))}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();delete dd.placed[chosen];save(dd);say(tx('removed'),2000);chosen=null;draw()}};
function drag(el,s){el.style.touchAction='none';el.addEventListener('pointerdown',e=>{if(e.button!==0)return;const start=[e.clientX,e.clientY];let ghost=null;const mv=ev=>{if(!ghost&&Math.hypot(ev.clientX-start[0],ev.clientY-start[1])<6)return;if(!ghost){ghost=E('div',s,'sticker-ghost');document.body.append(ghost);el.style.opacity=.3}ghost.style.transform=`translate(${ev.clientX-22}px,${ev.clientY-22}px)`};const up=ev=>{removeEventListener('pointermove',mv);removeEventListener('pointerup',up);removeEventListener('pointercancel',up);el.style.opacity='';if(!ghost)return;ghost.remove();el.dataset.dragged='1';setTimeout(()=>delete el.dataset.dragged,0);const r=board.getBoundingClientRect();if(ev.clientX>=r.left&&ev.clientX<=r.right&&ev.clientY>=r.top&&ev.clientY<=r.bottom){put(s,(ev.clientX-r.left)/r.width*100,(ev.clientY-r.top)/r.height*100);sound('pop');chosen=null;draw()}};addEventListener('pointermove',mv);addEventListener('pointerup',up);addEventListener('pointercancel',up)});el.addEventListener('click',e=>{if(el.dataset.dragged)e.stopImmediatePropagation()},true)}}
const PETAL=['#ff8fab','#ffd166','#c77dff','#4cc9f0','#ff7b54','#f28482'];
function plantSvg(stage,i){const c=PETAL[i%PETAL.length];let g=`<ellipse cx="30" cy="92" rx="22" ry="6" fill="#8a603f"/>`;if(stage===0)return g+`<ellipse cx="30" cy="88" rx="4" ry="3" fill="#6b4a33"/>`;const h=[0,18,30,42,52,58][Math.min(5,stage)];g+=`<path d="M30 90V${90-h}" stroke="#40916c" stroke-width="3" stroke-linecap="round"/>`;if(stage>=1)g+=`<path d="M30 ${90-h*.45}c-8 0-12-5-13-11 7 0 12 4 13 11z" fill="#74c69d"/>`;if(stage>=2)g+=`<path d="M30 ${90-h*.65}c8 0 12-5 13-11-7 0-12 4-13 11z" fill="#52b788"/>`;if(stage>=3&&stage<6)g+=`<ellipse cx="30" cy="${88-h}" rx="${stage===5?7:5}" ry="${stage===5?9:7}" fill="${stage===5?c:'#95d5b2'}"/>`;if(stage>=6){const cy=90-h;for(let k=0;k<6;k++){const a=k*Math.PI/3;g+=`<ellipse cx="${30+9*Math.cos(a)}" cy="${cy+9*Math.sin(a)}" rx="7" ry="7" fill="${c}"/>`}g+=`<circle cx="30" cy="${cy}" r="6" fill="#ffd166"/>`}return g}
function gardenTab(box){const d=read(),t=totalWins(d),bloomed=Math.floor(t/6),n=Math.min(12,bloomed+1);box.append(E('p',tx('gardenHelp')),E('p',tx('flowers',{n:bloomed}),'progress'));const scene=E('div','','garden-scene');scene.setAttribute('role','img');scene.setAttribute('aria-label',tx('flowers',{n:bloomed}));let svg='';for(let i=0;i<n;i++){const stage=Math.max(0,Math.min(6,t-6*i));svg+=`<svg viewBox="0 0 60 100" class="plant">${plantSvg(stage,i)}</svg>`}scene.innerHTML=svg;box.append(scene);if(bloomed<12)box.append(E('p',tx('nextFlower',{n:6-(t%6)})))}
function badgesTab(box){const d=read(),earned=new Set(BADGES.filter(([,,test])=>test(d)).map(([id])=>id)),grid=E('div','','badge-grid');BADGES.forEach(([id,icon])=>{const [name,desc]=badgeText(id),got=earned.has(id),c=E('div','','badge-card'+(got?' got':''));c.append(E('span',got?icon:'🔒','badge-icon'),E('strong',name),E('span',desc,'small'),E('span',got?tx('earned'):tx('notYet'),'badge-state'));grid.append(c)});box.append(grid)}
function draw(){if(!profile||$('app').hidden)return;guideVisible();section.replaceChildren(E('h2',tx('collection')),E('p',tx('intro')));const tabs=E('div','','learning-tabs');[['stickers','📒'],['garden','🌷'],['badges','🏅']].forEach(([k,icon])=>{const b=B(`${icon} ${tx(k)}`,()=>{tab=k;chosen=null;draw()});b.setAttribute('aria-pressed',tab===k);tabs.append(b)});const box=E('div','','learning-stage');section.append(tabs,box);({stickers:stickersTab,garden:gardenTab,badges:badgesTab})[tab](box)}
gardenOn(r=>{draw();if(r==='lang')bubble.classList.remove('show');if(r==='start'||r==='switch'){const p=window.gardenProfileApi?.active();setTimeout(()=>say(p?.name?tx('hello',{name:p.name}):tx('helloAnon'),5000),600)}});
if(profile){draw();setTimeout(()=>{const p=window.gardenProfileApi?.active();say(p?.name?tx('hello',{name:p.name}):tx('helloAnon'),5000)},900)}else guideVisible();
new MutationObserver(guideVisible).observe($('app'),{attributes:true,attributeFilter:['hidden']});
})();
