// Grădina Curioasă — Jucării: Puzzle cu piese, Lego cu cărămizi (model, știfturi, liber) și Potrivește perechile.
(()=>{
const LANGS=['ro','en','hu','uk'],L=a=>a[Math.max(0,LANGS.indexOf(lang))]??a[1],fmt=(s,v={})=>String(s).replace(/\{(\w+)\}/g,(_,x)=>v[x]??'');
const E=(t,x='',c='')=>{const e=document.createElement(t);e.textContent=x;if(c)e.className=c;return e},B=(x,fn,c)=>{const b=E('button',x,c);b.type='button';b.onclick=fn;return b};
const uid=()=>localStorage.getItem('garden_active')||'default',key=()=>`garden_toys_${uid()}`,read=()=>{try{return JSON.parse(localStorage.getItem(key()))||{}}catch{return {}}},save=d=>{try{localStorage.setItem(key(),JSON.stringify(d))}catch{}};
const age=()=>ageOf(profile.dob),rand=n=>Math.floor(Math.random()*n),pick=a=>a[rand(a.length)],mix=a=>shuffle([...a]);
const U={
title:['Jucării','Toys','Játékok','Іграшки'],intro:['Puzzle cu piese, construcții din cărămizi și perechi de potrivit.','Jigsaw puzzles, brick building and pairs to match.','Kirakó, építőkocka és párosító.','Пазли, будування з цеглинок і пари для зіставлення.'],
puzzle:['🧩 Puzzle','🧩 Puzzle','🧩 Kirakó','🧩 Пазл'],lego:['🧱 Lego','🧱 Bricks','🧱 Építőkocka','🧱 Цеглинки'],match:['🃏 Potrivește','🃏 Match','🃏 Párosító','🃏 Пари'],listen:['🔊 Ascultă','🔊 Listen','🔊 Meghallgatom','🔊 Послухати'],
pHelp:['Atinge o piesă, apoi locul ei din tablou.','Tap a piece, then its place in the picture.','Érints meg egy darabot, aztán a helyét a képen.','Торкнися шматочка, а потім його місця на картинці.'],pHelpRot:['Atinge o piesă, rotește-o dacă e nevoie, apoi atinge locul ei. Nu mai ai imaginea ajutătoare!','Tap a piece, rotate it if needed, then tap its place. No helper picture this time!','Érints meg egy darabot, forgasd el, ha kell, aztán érintsd meg a helyét. Most nincs segítő kép!','Торкнися шматочка, поверни його, якщо треба, і торкнися його місця. Цього разу без підказки!'],
rotate:['🔄 Rotește piesa','🔄 Rotate the piece','🔄 Forgasd el a darabot','🔄 Поверни шматочок'],pickPiece:['Alege întâi o piesă.','Choose a piece first.','Előbb válassz egy darabot.','Спершу обери шматочок.'],notHere:['Piesa nu se potrivește aici. Mai încearcă!','This piece doesn’t fit here. Try again!','Ez a darab nem ide illik. Próbáld újra!','Цей шматочок сюди не підходить. Спробуй ще!'],turnIt:['Locul e bun, dar piesa e întoarsă. Rotește-o!','Right place, but the piece is turned. Rotate it!','Jó a hely, de a darab el van fordulva. Forgasd el!','Місце правильне, але шматочок повернутий. Поверни його!'],
pDone:['Puzzle complet! 🧩','Puzzle complete! 🧩','Kész a kirakó! 🧩','Пазл зібрано! 🧩'],pNext:['➡️ Alt puzzle','➡️ Another puzzle','➡️ Másik kirakó','➡️ Інший пазл'],piece:['Piesa {n}','Piece {n}','{n}. darab','Шматочок {n}'],slot:['Locul {r}, {c}','Place {r}, {c}','{r}. sor, {c}. hely','Місце {r}, {c}'],pieces:['Piese: {a} din {b}','Pieces: {a} of {b}','Darabok: {a} / {b}','Шматочки: {a} з {b}'],
lModes:{copy:['📋 Copiază modelul','📋 Copy the model','📋 Másold le','📋 Скопіюй модель'],studs:['🔢 Știfturi','🔢 Studs','🔢 Bütykök','🔢 Шипики'],free:['🎨 Construiește liber','🎨 Free build','🎨 Szabad építés','🎨 Вільне будування']},
lCopy:['Construiește la fel ca modelul: aceleași cărămizi, aceleași culori, în același loc. Alege cărămida și culoarea, apoi atinge coloana.','Build the same as the model: same bricks, same colours, same places. Pick a brick and colour, then tap a column.','Építsd meg ugyanúgy, mint a minta: ugyanazok a kockák, színek és helyek. Válassz kockát és színt, aztán érints meg egy oszlopot.','Збудуй так само, як модель: ті самі цеглинки, кольори й місця. Обери цеглинку й колір, потім торкнися стовпчика.'],
lStuds:['Folosește cărămizi care au împreună exact {s} știfturi.','Use bricks with exactly {s} studs altogether.','Használj olyan kockákat, amelyeken összesen pontosan {s} bütyök van.','Використай цеглинки, на яких разом рівно {s} шипиків.'],lStudsH:['Folosește exact {s} știfturi și construiește exact {h} rânduri înălțime.','Use exactly {s} studs and build exactly {h} rows high.','Használj pontosan {s} bütyköt, és építs pontosan {h} sor magasat.','Використай рівно {s} шипиків і збудуй рівно {h} рядів у висоту.'],
lFree:['Construiește ce vrei tu: o casă, un turn, un pod. Apoi salvează-l!','Build whatever you like: a house, a tower, a bridge. Then save it!','Építs, amit szeretnél: házat, tornyot, hidat. Aztán mentsd el!','Будуй що хочеш: будинок, вежу, міст. А потім збережи!'],
studsUsed:['Știfturi: {a} din {b}','Studs: {a} of {b}','Bütykök: {a} / {b}','Шипики: {a} з {b}'],height:['Înălțime: {h} rânduri','Height: {h} rows','Magasság: {h} sor','Висота: {h} рядів'],tooMany:['Prea multe știfturi! Scoate o cărămidă.','Too many studs! Take a brick off.','Túl sok bütyök! Vegyél le egy kockát.','Забагато шипиків! Прибери цеглинку.'],
tooHigh:['Nu mai e loc sus.','There’s no more room at the top.','Fent már nincs hely.','Згори більше немає місця.'],lDone:['Construcție reușită! 🧱','Great building! 🧱','Remek építmény! 🧱','Чудова споруда! 🧱'],wrongH:['Știfturile sunt bune, dar înălțimea trebuie să fie {h} rânduri.','Studs are right, but the height must be {h} rows.','A bütykök stimmelnek, de a magasság {h} sor legyen.','Шипики правильні, але висота має бути {h} рядів.'],
undo:['↩️ Scoate ultima','↩️ Remove the last one','↩️ Az utolsót le','↩️ Прибрати останню'],clear:['🧹 Începe din nou','🧹 Start again','🧹 Újrakezdés','🧹 Почати знову'],saveB:['💾 Salvează construcția','💾 Save the building','💾 Építmény mentése','💾 Зберегти споруду'],saved:['Salvată! O găsești mai jos.','Saved! You’ll find it below.','Elmentve! Lent találod.','Збережено! Вона нижче.'],mine:['Construcțiile mele','My buildings','Az építményeim','Мої споруди'],
model:['Modelul','The model','A minta','Модель'],yours:['Construcția ta','Your building','Az építményed','Твоя споруда'],brick:['Cărămida','Brick','Kocka','Цеглинка'],col:['Coloana {n}','Column {n}','{n}. oszlop','Стовпчик {n}'],nextL:['➡️ Altă provocare','➡️ Another challenge','➡️ Másik feladat','➡️ Інше завдання'],
mHelp:['Atinge un lucru din stânga, apoi perechea lui din dreapta.','Tap something on the left, then its partner on the right.','Érints meg valamit bal oldalt, aztán a párját jobb oldalt.','Торкнися чогось ліворуч, а потім його пари праворуч.'],mWrong:['Nu sunt pereche. Mai încearcă!','Not a pair. Try again!','Ezek nem párok. Próbáld újra!','Це не пара. Спробуй ще!'],mDone:['Toate perechile potrivite! 🃏','All pairs matched! 🃏','Minden pár megvan! 🃏','Усі пари знайдено! 🃏'],mNext:['➡️ Alte perechi','➡️ More pairs','➡️ Új párok','➡️ Нові пари'],mPick:['Alege întâi din stânga.','Choose from the left first.','Előbb válassz a bal oldalról.','Спершу обери зліва.'],
themes:{shadow:['🌑 Umbre','🌑 Shadows','🌑 Árnyékok','🌑 Тіні'],color:['🎨 Culori','🎨 Colours','🎨 Színek','🎨 Кольори'],dots:['🔵 Numără','🔵 Count','🔵 Számolás','🔵 Лічба'],babies:['🐣 Puii','🐣 Babies','🐣 Kicsinyek','🐣 Малята'],letters:['🔤 Litere','🔤 Letters','🔤 Betűk','🔤 Літери'],times:['✖️ Înmulțiri','✖️ Times tables','✖️ Szorzás','✖️ Множення'],opposites:['↔️ Contrarii','↔️ Opposites','↔️ Ellentétek','↔️ Протилежності'],fractions:['½ Fracții','½ Fractions','½ Törtek','½ Дроби'],clocks:['🕒 Ceasuri','🕒 Clocks','🕒 Órák','🕒 Годинники']},
colors:{red:['roșu','red','piros','червоний'],yellow:['galben','yellow','sárga','жовтий'],green:['verde','green','zöld','зелений'],blue:['albastru','blue','kék','синій'],purple:['mov','purple','lila','фіолетовий'],orange:['portocaliu','orange','narancs','помаранчевий'],brown:['maro','brown','barna','коричневий'],white:['alb','white','fehér','білий']}};
const u=(k,v)=>fmt(L(U[k]),v);
const section=E('section','','card studio toys');section.id='toys';section.dataset.view='toys';$('app').insertBefore(section,$('birthday'));
let mode=null,stage,status;const say=(m,good=true)=>{status.textContent=m;status.classList.toggle('bad',!good)};
const help=t=>{stage.append(E('p',t,'studio-help'));if(age()<=6)stage.append(B(u('listen'),()=>gardenSpeak(t,true),'speak-btn'))};
const art=(n,x,y,s)=>{const g=gardenArt(n,64).querySelector('svg');return `<g transform="translate(${x} ${y}) scale(${s})">${g?g.innerHTML:''}</g>`};

// ——— Puzzle: imagini compuse din ilustrațiile jocului
const SCENES=[
()=>`<rect width="300" height="300" fill="#bfe3ff"/><circle cx="255" cy="45" r="26" fill="#ffd43b"/><rect y="215" width="300" height="85" fill="#8fd694"/>${art('castle',95,40,2.6)}${art('unicorn',10,160,1.7)}${art('tree',215,150,1.2)}`,
()=>`<rect width="300" height="300" fill="#1b1f4b"/>${[[30,40],[80,110],[260,30],[220,120],[140,20],[40,230],[270,250],[180,270]].map(([x,y])=>`<circle cx="${x}" cy="${y}" r="3" fill="#fff"/>`).join('')}<circle cx="230" cy="220" r="46" fill="#4dabf7"/><path d="M200 205q30-15 55 5q-10 20-40 20z" fill="#69db7c"/>${art('rocket',70,40,2.6)}${art('robot',5,180,1.6)}`,
()=>`<rect width="300" height="300" fill="#e7f5ff"/><rect y="190" width="300" height="110" fill="#b2f2bb"/>${art('garden',10,110,2.2)}${art('tree',170,20,2.2)}${art('ladybug',200,200,1.4)}`,
()=>`<rect width="300" height="300" fill="#ffe8cc"/>${art('city',20,10,3.6)}<rect y="235" width="300" height="65" fill="#868e96"/><rect x="20" y="265" width="40" height="6" fill="#fff"/><rect x="130" y="265" width="40" height="6" fill="#fff"/><rect x="240" y="265" width="40" height="6" fill="#fff"/>${art('car',150,180,1.7)}`,
()=>`<rect width="300" height="300" fill="#d3f9d8"/><circle cx="60" cy="50" r="30" fill="#ffe066"/><rect y="230" width="300" height="70" fill="#8ce99a"/>${art('dino',60,60,3)}${art('tree',210,120,1.6)}${art('cone',10,190,1.2)}`,
()=>`<rect width="300" height="300" fill="#a5d8ff"/>${art('ocean',0,10,4.6)}`];
let pz=null;
function puzzle(){const a=age();if(!pz){const [cols,rows]=a<=4?[2,2]:a<=5?[3,2]:a<=8?[3,3]:[4,4];const n=cols*rows,scene=rand(SCENES.length),order=mix([...Array(n).keys()]);pz={cols,rows,n,scene,tray:order,rot:Object.fromEntries(order.map(i=>[i,a>=9?rand(4):0])),placed:{},sel:null,done:false}}
const p=pz,rotOn=a>=9,W=300/p.cols,H=300/p.rows,svg=SCENES[p.scene]();help(rotOn?u('pHelpRot'):u('pHelp'));
const info=E('p',u('pieces',{a:Object.keys(p.placed).length,b:p.n}),'versus-pairs');stage.append(info);
const board=E('div','','pz-board');board.style.setProperty('--cols',p.cols);board.style.setProperty('--rows',p.rows);if(!rotOn){const ghost=E('div','','pz-ghost');ghost.innerHTML=`<svg viewBox="0 0 300 300" preserveAspectRatio="none">${svg}</svg>`;board.append(ghost)}
const pieceSVG=i=>{const c=i%p.cols,r=Math.floor(i/p.cols);return `<svg viewBox="${c*W} ${r*H} ${W} ${H}" preserveAspectRatio="none">${svg}</svg>`};
for(let i=0;i<p.n;i++){const slot=B('',()=>drop(i),'pz-slot');slot.dataset.slot=i;slot.setAttribute('aria-label',u('slot',{r:Math.floor(i/p.cols)+1,c:i%p.cols+1}));if(p.placed[i]){slot.innerHTML=pieceSVG(i);slot.classList.add('filled');slot.disabled=true}board.append(slot)}
const tray=E('div','','pz-tray');tray.style.setProperty('--cols',Math.min(p.n,a<=5?3:4));
p.tray.filter(i=>!p.placed[i]).forEach(i=>{const b=B('',()=>{p.sel=i;paintSel()},'pz-piece');b.dataset.piece=i;b.innerHTML=pieceSVG(i);b.firstChild.style.transform=`rotate(${p.rot[i]*90}deg)`;b.setAttribute('aria-label',u('piece',{n:p.tray.indexOf(i)+1}));tray.append(b)});
const paintSel=()=>tray.querySelectorAll('.pz-piece').forEach(b=>b.setAttribute('aria-pressed',+b.dataset.piece===p.sel));
function drop(i){if(p.done)return;if(p.sel===null){say(u('pickPiece'),false);return}if(p.sel!==i){gardenMiss('toys-puzzle');say(u('notHere'),false);const s=board.querySelector(`[data-slot="${i}"]`);s.classList.remove('shake');s.getBoundingClientRect();s.classList.add('shake');return}if(p.rot[i]%4){say(u('turnIt'),false);return}
p.placed[i]=true;p.sel=null;window.gardenSound?.('pop');if(Object.keys(p.placed).length===p.n){p.done=true;render();gardenCelebrate('toys-puzzle');say(u('pDone'));return}render()}
stage.append(board);if(rotOn)stage.append(B(u('rotate'),()=>{if(p.sel===null){say(u('pickPiece'),false);return}p.rot[p.sel]=(p.rot[p.sel]+1)%4;const b=tray.querySelector(`[data-piece="${p.sel}"] svg`);if(b)b.style.transform=`rotate(${p.rot[p.sel]*90}deg)`;status.textContent=''},'pz-rotate'));stage.append(tray);paintSel();
stage.dataset.done=p.done?'1':'';if(p.done){board.classList.add('complete');stage.append(B(u('pNext'),()=>{pz=null;render()},'primary pz-next'))}}

// ——— Lego: cărămizi care cad pe coloane (vedere din față)
const BRICK_COLORS=[['red','#e03131'],['yellow','#fcc419'],['green','#2f9e44'],['blue','#1c7ed6'],['orange','#f76707'],['white','#f1f3f5']];
let lg=null;const legoState={w:2,c:'red',sub:null};
function tops(bricks,cols){const h=Array(cols).fill(0);bricks.forEach(b=>{for(let x=b.x;x<b.x+b.w;x++)h[x]=Math.max(h[x],b.y+1)});return h}
function dropBrick(bricks,cols,x,w){const h=tops(bricks,cols);x=Math.max(0,Math.min(cols-w,x));let y=0;for(let i=x;i<x+w;i++)y=Math.max(y,h[i]);return {x,y,w}}
function genModel(cols,n,widths){const bricks=[];for(let k=0;k<n;k++){const w=pick(widths),x=rand(cols-w+1),b=dropBrick(bricks,cols,x,w);if(b.y>=6){k--;continue}bricks.push({...b,c:pick(BRICK_COLORS)[0]})}return bricks}
const canon=bs=>JSON.stringify(bs.map(b=>[b.x,b.y,b.w,b.c]).sort());
function legoView(bricks,cols,rows,cls,onCol){const v=E('div','','lego-plate '+(cls||''));v.style.setProperty('--cols',cols);v.style.setProperty('--rows',rows);
bricks.forEach(b=>{const el=E('span','','lego-brick');el.style.left=`${b.x/cols*100}%`;el.style.bottom=`${b.y/rows*100}%`;el.style.width=`${b.w/cols*100}%`;el.style.height=`${100/rows}%`;el.style.setProperty('--b',BRICK_COLORS.find(c=>c[0]===b.c)[1]);el.style.setProperty('--w',b.w);v.append(el)});
if(onCol)for(let x=0;x<cols;x++){const c=B('',()=>onCol(x),'lego-col');c.style.left=`${x/cols*100}%`;c.style.width=`${100/cols}%`;c.dataset.col=x;c.setAttribute('aria-label',u('col',{n:x+1}));v.append(c)}
v.setAttribute('role',onCol?'group':'img');return v}
function lego(){const a=age(),subs=['copy','studs','free'];if(!subs.includes(legoState.sub))legoState.sub='copy';const sub=legoState.sub;
const cols=a<=5?6:a<=8?8:10,rows=a<=5?6:8;
if(!lg||lg.sub!==sub){lg={sub,bricks:[],done:false};if(sub==='copy'){const n=a<=5?3:a<=8?5+rand(2):8+rand(3);lg.model=a<=5?(()=>{const c=pick(BRICK_COLORS)[0];return Array.from({length:3},(_,y)=>({x:2,y,w:2,c:y===1?pick(BRICK_COLORS)[0]:c}))})():genModel(cols,n,a<=8?[1,2,2,3]:[1,2,3,4])}if(sub==='studs'){lg.target=a<=5?4+rand(3):a<=8?8+rand(7):12+rand(9);if(a>=9)lg.height=3+rand(2)}}
const tabs=E('div','','learning-tabs page-picker lego-subs');subs.forEach(k=>{const b=B(L(U.lModes[k]),()=>{legoState.sub=k;lg=null;render()});b.setAttribute('aria-pressed',k===sub);tabs.append(b)});stage.append(tabs);
help(sub==='copy'?u('lCopy'):sub==='studs'?(lg.height?u('lStudsH',{s:lg.target,h:lg.height}):u('lStuds',{s:lg.target})):u('lFree'));
if(sub==='copy'){stage.dataset.model=JSON.stringify(lg.model)}if(sub==='studs'){stage.dataset.target=lg.target;if(lg.height)stage.dataset.height=lg.height}
const pal=E('div','','lego-palette');const sizes=E('div','','draw-tools');sizes.setAttribute('role','group');sizes.setAttribute('aria-label',u('brick'));[1,2,3,4].forEach(w=>{const b=B('',()=>{legoState.w=w;paintPal()},'lego-size');b.dataset.w=w;const pv=E('span','','lego-brick mini');pv.style.setProperty('--b',BRICK_COLORS.find(c=>c[0]===legoState.c)[1]);pv.style.setProperty('--w',w);pv.style.width=`${w*22}px`;b.append(pv,E('span',`1×${w}`));sizes.append(b)});
const colors=E('div','','palette');BRICK_COLORS.forEach(([k,hex])=>{const b=B('',()=>{legoState.c=k;paintPal()},'swatch');b.dataset.c=k;b.style.setProperty('--sw',hex);b.setAttribute('aria-label',L(U.colors[k]));b.title=L(U.colors[k]);colors.append(b)});
pal.append(sizes,colors);const paintPal=()=>{sizes.querySelectorAll('button').forEach(b=>{b.setAttribute('aria-pressed',+b.dataset.w===legoState.w);b.querySelector('.lego-brick').style.setProperty('--b',BRICK_COLORS.find(c=>c[0]===legoState.c)[1])});colors.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',b.dataset.c===legoState.c))};
const info=E('p','','versus-pairs'),area=E('div','','lego-area');
const place=x=>{if(lg.done)return;const b=dropBrick(lg.bricks,cols,x,legoState.w);if(b.y>=rows){say(u('tooHigh'),false);return}lg.bricks.push({...b,c:legoState.c});window.gardenSound?.('pop');status.textContent='';check();draw()};
function check(){if(sub==='copy'&&canon(lg.bricks)===canon(lg.model)){lg.done=true;gardenCelebrate('toys-lego');say(u('lDone'))}
if(sub==='studs'){const s=lg.bricks.reduce((t,b)=>t+b.w,0),h=Math.max(0,...tops(lg.bricks,cols));if(s>lg.target){gardenMiss('toys-lego');say(u('tooMany'),false)}else if(s===lg.target){if(lg.height&&h!==lg.height)say(u('wrongH',{h:lg.height}),false);else{lg.done=true;gardenCelebrate('toys-lego');say(u('lDone'))}}}}
function draw(){area.replaceChildren();if(sub==='copy'){const f=E('figure','','lego-fig');f.append(E('figcaption',u('model')),legoView(lg.model,cols,rows,'model'));area.append(f)}const f2=E('figure','','lego-fig main');f2.append(E('figcaption',u('yours')),legoView(lg.bricks,cols,rows,'mine',place));area.append(f2);
const s=lg.bricks.reduce((t,b)=>t+b.w,0),h=Math.max(0,...tops(lg.bricks,cols));info.textContent=sub==='studs'?`${u('studsUsed',{a:s,b:lg.target})}${lg.height?' · '+u('height',{h}):''}`:'';stage.dataset.bricks=lg.bricks.length;stage.dataset.done=lg.done?'1':''}
const row=E('div','','draw-tools');row.append(B(u('undo'),()=>{lg.bricks.pop();lg.done=false;status.textContent='';draw()}),B(u('clear'),()=>{lg.bricks=[];lg.done=false;status.textContent='';draw()}));
if(sub==='free')row.append(B(u('saveB'),()=>{if(!lg.bricks.length)return;const d=read();d.lego=[{cols,rows,bricks:lg.bricks},...(d.lego||[])].slice(0,6);save(d);gardenCelebrate('toys-lego');say(u('saved'));drawSaved()},'primary lego-save'));else row.append(B(u('nextL'),()=>{lg=null;render()}));
stage.append(pal,info,area,row);const savedBox=E('div','','lego-saved');stage.append(savedBox);const drawSaved=()=>{const list=read().lego||[];savedBox.replaceChildren();if(sub!=='free'||!list.length)return;savedBox.append(E('h3',u('mine')));const r=E('div','','lego-saved-row');list.forEach(m=>r.append(legoView(m.bricks,m.cols,m.rows,'thumb')));savedBox.append(r)};
paintPal();draw();drawSaved()}

// ——— Potrivește perechile
const SHADOW=['🐶','🐱','🐘','🦒','🚗','🍎','🌳','🦋','⭐','🐟','🐢','🚲'];
const COLOR_OBJ=[['red','#e03131','🍓'],['yellow','#fcc419','🍌'],['green','#2f9e44','🥦'],['blue','#1c7ed6','🐳'],['purple','#9c36b5','🍇'],['orange','#f76707','🥕'],['brown','#8d6e63','🐻'],['white','#f1f3f5','⛄']];
const BABIES=[['🐄',['vițel','calf','borjú','теля']],['🐑',['miel','lamb','bárány','ягня']],['🐔',['puișor','chick','csibe','курча']],['🐴',['mânz','foal','csikó','лоша']],['🐕',['cățeluș','puppy','kiskutya','цуценя']],['🐈',['pisoi','kitten','kiscica','кошеня']],['🐖',['purcel','piglet','malac','порося']],['🐐',['ied','kid','gida','козеня']]];
const OPP=[[['mare','big','nagy','великий'],['mic','small','kicsi','малий']],[['cald','hot','meleg','гарячий'],['rece','cold','hideg','холодний']],[['sus','up','fel','вгору'],['jos','down','le','вниз']],[['zi','day','nappal','день'],['noapte','night','éjszaka','ніч']],[['repede','fast','gyors','швидко'],['încet','slow','lassú','повільно']],[['plin','full','tele','повний'],['gol','empty','üres','порожній']],[['deschis','open','nyitva','відчинений'],['închis','closed','zárva','зачинений']],[['vesel','happy','vidám','веселий'],['trist','sad','szomorú','сумний']]];
const FRAC=[['½','50%'],['¼','25%'],['¾','75%'],['1/10','10%'],['1/5','20%'],['2/5','40%'],['1/1','100%'],['3/10','30%']];
const CLOCKS=[['🕐','1:00'],['🕑','2:00'],['🕒','3:00'],['🕓','4:00'],['🕔','5:00'],['🕕','6:00'],['🕖','7:00'],['🕗','8:00'],['🕘','9:00'],['🕙','10:00'],['🕜','1:30'],['🕞','3:30'],['🕠','5:30']];
const THEMES=a=>a<=5?['shadow','color','dots']:a<=8?['dots','babies','letters','shadow']:['times','opposites','fractions','clocks'];
let mt=null,theme=null;
function genPairs(t,a){const n=a<=5?3+(a>=5?1:0):a<=8?5:6;const take=arr=>mix(arr).slice(0,n);
if(t==='shadow')return take(SHADOW).map(s=>({l:s,r:s,rCls:'silhouette',rLabel:s}));
if(t==='color')return take(COLOR_OBJ).map(([k,hex,o])=>({l:'',lCls:'dot',lStyle:hex,lLabel:L(U.colors[k]),r:o}));
if(t==='dots'){const max=a<=5?5:10;return mix([...Array(max).keys()].map(i=>i+1)).slice(0,n).map(k=>({l:'●'.repeat(k),lCls:'dots',lLabel:String(k),r:String(k)}))}
if(t==='babies')return take(BABIES).map(([e,nm])=>({l:e,r:L(nm)}));
if(t==='letters'){const abc=lang==='uk'?'АБВГДЕЖЗИКЛМНОПРСТУФХ':'ABCDEFGHIJKLMNOPRSTUVZ';return mix([...abc]).slice(0,n).map(c=>({l:c,r:c.toLowerCase()}))}
if(t==='times'){const out=[],seen=new Set();while(out.length<n){const x=2+rand(8),y=2+rand(8);if(seen.has(x*y))continue;seen.add(x*y);out.push({l:`${x} × ${y}`,r:String(x*y)})}return out}
if(t==='opposites')return take(OPP).map(([x,y])=>({l:L(x),r:L(y)}));
if(t==='fractions')return take(FRAC).map(([f,p])=>({l:f,r:p}));
return take(CLOCKS).map(([c,t])=>({l:c,r:t,lCls:'clock'}))}
function match(){const a=age(),list=THEMES(a);if(!list.includes(theme))theme=list[0];if(!mt||mt.theme!==theme){mt={theme,pairs:genPairs(theme,a),done:new Set(),sel:null}}
const tabs=E('div','','learning-tabs page-picker');list.forEach(k=>{const b=B(L(U.themes[k]),()=>{theme=k;mt=null;render()});b.setAttribute('aria-pressed',k===theme);tabs.append(b)});stage.append(tabs);help(u('mHelp'));
const P=mt.pairs,right=mt.rightOrder||(mt.rightOrder=mix(P.map((_,i)=>i)));const wrap=E('div','','match-cols'),L1=E('div','','match-col'),R1=E('div','','match-col');wrap.append(L1,R1);stage.append(wrap);
const lb=P.map((p,i)=>{const b=B(p.l,()=>{if(mt.done.has(i))return;mt.sel=i;paint()},'match-item m-left '+(p.lCls||''));b.dataset.pair=i;if(p.lStyle)b.style.setProperty('--dot',p.lStyle);if(p.lLabel)b.setAttribute('aria-label',p.lLabel);L1.append(b);return b});
const rb=right.map(i=>{const p=P[i],b=B(p.r,()=>pickRight(i,b),'match-item m-right '+(p.rCls||''));b.dataset.pair=i;if(p.rLabel)b.setAttribute('aria-label',p.rLabel);R1.append(b);return b});
function paint(){lb.forEach((b,i)=>{b.setAttribute('aria-pressed',mt.sel===i);b.disabled=mt.done.has(i);b.classList.toggle('done',mt.done.has(i));if(mt.done.has(i))b.style.setProperty('--pair',`var(--pair${[...mt.done].indexOf(i)%6})`)});rb.forEach(b=>{const i=+b.dataset.pair;b.disabled=mt.done.has(i);b.classList.toggle('done',mt.done.has(i));if(mt.done.has(i))b.style.setProperty('--pair',`var(--pair${[...mt.done].indexOf(i)%6})`)})}
function pickRight(i,b){if(mt.done.has(i))return;if(mt.sel===null){say(u('mPick'),false);return}if(mt.sel!==i){gardenMiss('toys-match');say(u('mWrong'),false);b.classList.remove('shake');b.getBoundingClientRect();b.classList.add('shake');return}mt.done.add(i);mt.sel=null;window.gardenSound?.('pop');status.textContent='';paint();if(mt.done.size===P.length){gardenCelebrate('toys-match');say(u('mDone'));stage.append(B(u('mNext'),()=>{mt=null;render()},'primary match-next'))}}
paint()}

function render(){if(!profile||$('app').hidden)return;section.replaceChildren();const head=E('div','','versus-head');head.append(E('span','🧸','craft-head-icon'),E('div'));head.lastChild.append(E('h2',u('title')),E('p',u('intro')));section.append(head);
if(!['puzzle','lego','match'].includes(mode))mode='puzzle';const tabs=E('div','','learning-tabs');['puzzle','lego','match'].forEach(k=>{const b=B(u(k),()=>{mode=k;render()});b.setAttribute('aria-pressed',mode===k);b.dataset.mode=k;tabs.append(b)});section.append(tabs);
stage=E('div','','learning-stage studio-stage toys-stage');status=E('p','','party-status');status.setAttribute('role','status');status.setAttribute('aria-live','polite');section.append(stage,status);
try{localStorage.setItem(`garden_last_${uid()}`,JSON.stringify({view:'toys',mode}))}catch{}({puzzle,lego,match})[mode]()}
document.addEventListener('garden:open',e=>{const {view,mode:m}=e.detail||{};if(view!=='toys')return;mode=m;render()});
gardenOn(r=>{if(r==='start'||r==='switch'){pz=null;lg=null;mt=null;mode=null;theme=null}else if(r==='lang')mt=null;render()});if(profile)render();
})();
