// Grădina Curioasă — Contra lui Robo: adversar calculat local (fără server, fără costuri).
// X și 0 (minimax), Memory cu memorie imperfectă, Bețișoare (Nim). Nivelul se adaptează la copil.
(()=>{
const V={
ro:{title:'Contra lui Robo',intro:'Joacă împotriva lui Robo, robotul din grădină. El se adaptează: când câștigi de două ori la rând, devine mai isteț; când pierde el, se relaxează.',ttt:'X și 0',memory:'Memory',nim:'Bețișoarele',level:'Robo e acum: {l}',levels:['ușor','mediu','isteț'],setLevel:'Alege nivelul lui Robo',score:'Tu {a} · Robo {b} · Egal {c}',again:'Încă o rundă',yourTurn:'E rândul tău.',thinking:'Robo se gândește…',youWin:'Ai câștigat! Robo te felicită. 🎉',roboWins:'Robo a câștigat de data asta. Mai încercăm?',draw:'Egal! Sunteți la fel de isteți.',levelUp:'Robo a devenit mai isteț!',levelDown:'Robo se relaxează puțin.',tttHelp:'Tu ești ✕, Robo e ◯. Cine face primul o linie de trei (orizontal, vertical sau pe diagonală) câștigă.',cell:'Rândul {r}, coloana {c}: {v}',empty:'liber',you:'tu',robo:'Robo',memHelp:'Întoarce două cărți. Dacă sunt la fel, le păstrezi și mai joci o dată. Altfel e rândul lui Robo. Robo ține minte cărțile, dar nu pe toate!',pairs:'Perechi: tu {a} · Robo {b}',card:'Carte {n}',found:'pereche găsită',nimHelp:'Luați pe rând câte 1–{m} bețișoare. Cine ia ultimul bețișor câștigă.',left:'Au rămas {n} bețișoare.',take:'Ia {n}',roboTook:'Robo a luat {n}.',youTook:'Ai luat {n}.',nimHint:'Sfat: încearcă să-i lași lui Robo un număr de bețișoare care se împarte la {k}.',listen:'🔊 Ascultă'},
en:{title:'Versus Robo',intro:'Play against Robo, the garden robot. He adapts: win twice in a row and he gets smarter; if he wins, he relaxes.',ttt:'Tic-tac-toe',memory:'Memory',nim:'Sticks',level:'Robo is now: {l}',levels:['easy','medium','clever'],setLevel:'Choose Robo’s level',score:'You {a} · Robo {b} · Draws {c}',again:'Another round',yourTurn:'Your turn.',thinking:'Robo is thinking…',youWin:'You won! Robo congratulates you. 🎉',roboWins:'Robo won this time. Shall we try again?',draw:'A draw! You are equally clever.',levelUp:'Robo got smarter!',levelDown:'Robo relaxes a little.',tttHelp:'You are ✕, Robo is ◯. The first to make a line of three (across, down or diagonal) wins.',cell:'Row {r}, column {c}: {v}',empty:'empty',you:'you',robo:'Robo',memHelp:'Turn over two cards. If they match, you keep them and play again. Otherwise it’s Robo’s turn. Robo remembers cards, but not all of them!',pairs:'Pairs: you {a} · Robo {b}',card:'Card {n}',found:'pair found',nimHelp:'Take turns picking 1–{m} sticks. Whoever takes the last stick wins.',left:'{n} sticks left.',take:'Take {n}',roboTook:'Robo took {n}.',youTook:'You took {n}.',nimHint:'Tip: try to leave Robo a number of sticks that divides by {k}.',listen:'🔊 Listen'},
hu:{title:'Robo ellen',intro:'Játssz Robo, a kerti robot ellen. Alkalmazkodik: ha kétszer egymás után nyersz, okosabb lesz; ha ő nyer, lazít.',ttt:'Amőba',memory:'Memória',nim:'Pálcikák',level:'Robo most: {l}',levels:['könnyű','közepes','okos'],setLevel:'Válaszd ki Robo szintjét',score:'Te {a} · Robo {b} · Döntetlen {c}',again:'Még egy kör',yourTurn:'Te jössz.',thinking:'Robo gondolkodik…',youWin:'Nyertél! Robo gratulál. 🎉',roboWins:'Most Robo nyert. Próbáljuk újra?',draw:'Döntetlen! Egyformán okosak vagytok.',levelUp:'Robo okosabb lett!',levelDown:'Robo kicsit lazít.',tttHelp:'Te vagy az ✕, Robo a ◯. Aki először kirak egy hármas sort (vízszintesen, függőlegesen vagy átlósan), nyer.',cell:'{r}. sor, {c}. oszlop: {v}',empty:'üres',you:'te',robo:'Robo',memHelp:'Fordíts fel két kártyát. Ha egyformák, megtarthatod őket, és újra jössz. Ha nem, Robo jön. Robo megjegyzi a kártyákat, de nem mindet!',pairs:'Párok: te {a} · Robo {b}',card:'{n}. kártya',found:'megtalált pár',nimHelp:'Felváltva vegyetek el 1–{m} pálcikát. Aki az utolsót elveszi, nyer.',left:'Maradt {n} pálcika.',take:'Elveszek {n}',roboTook:'Robo elvett {n}.',youTook:'Elvettél {n}.',nimHint:'Tipp: próbálj Robónak annyi pálcikát hagyni, ami osztható {k}-val.',listen:'🔊 Meghallgatom'},
uk:{title:'Проти Робо',intro:'Грай проти Робо — садового робота. Він підлаштовується: виграєш двічі поспіль — стає розумнішим; виграє він — відпочиває.',ttt:'Хрестики-нулики',memory:'Мемо',nim:'Палички',level:'Робо зараз: {l}',levels:['легкий','середній','кмітливий'],setLevel:'Обери рівень Робо',score:'Ти {a} · Робо {b} · Нічия {c}',again:'Ще раунд',yourTurn:'Твій хід.',thinking:'Робо думає…',youWin:'Ти переміг(-ла)! Робо тебе вітає. 🎉',roboWins:'Цього разу виграв Робо. Спробуємо ще?',draw:'Нічия! Ви однаково кмітливі.',levelUp:'Робо став розумнішим!',levelDown:'Робо трохи розслабився.',tttHelp:'Ти — ✕, Робо — ◯. Хто перший складе лінію з трьох (по горизонталі, вертикалі чи діагоналі), той виграє.',cell:'Рядок {r}, стовпчик {c}: {v}',empty:'порожньо',you:'ти',robo:'Робо',memHelp:'Переверни дві картки. Якщо вони однакові, забираєш їх і ходиш ще раз. Інакше хід Робо. Робо запам’ятовує картки, але не всі!',pairs:'Пари: ти {a} · Робо {b}',card:'Картка {n}',found:'пару знайдено',nimHelp:'По черзі беріть від 1 до {m} паличок. Хто візьме останню паличку, той виграє.',left:'Залишилося паличок: {n}.',take:'Взяти {n}',roboTook:'Робо взяв {n}.',youTook:'Ти взяв(-ла) {n}.',nimHint:'Порада: спробуй залишити Робо таку кількість паличок, що ділиться на {k}.',listen:'🔊 Послухати'}};
const tx=(k,v={})=>String(V[lang]?.[k]??V.en[k]??k).replace(/\{(\w+)\}/g,(_,x)=>v[x]??'');const lvName=i=>(V[lang]?.levels||V.en.levels)[i];
const E=(tag,text='',cls='')=>{const e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;return e},B=(text,fn,cls)=>{const b=E('button',text,cls);b.type='button';b.onclick=fn;return b};
const uid=()=>localStorage.getItem('garden_active')||'default',key=()=>`garden_versus_${uid()}`,read=()=>{try{return JSON.parse(localStorage.getItem(key()))||{}}catch{return {}}},save=d=>localStorage.setItem(key(),JSON.stringify(d));
const GAME={ttt:'tictactoe',memory:'memoryduel',nim:'nim'};
const ageStart=()=>ageOf(profile.dob)<=5?0:1;
function levelOf(m){const d=read();return d.level?.[m]??ageStart()}
const quick=()=>document.body.classList.contains('quiet')||window.gardenVersusFast;const wait=ms=>new Promise(r=>setTimeout(r,quick()?30:ms));
const section=E('section','','card versus');section.id='versus';section.dataset.view='versus';$('app').insertBefore(section,$('birthday'));
let mode='ttt',stage,status,token=0;
// Rezultatul unei runde: scor, nivel adaptiv, recompense.
function finish(m,result){const d=read();d.score=d.score||{};d.score[m]=d.score[m]||[0,0,0];d.level=d.level||{};d.streak=d.streak||{};const s=d.streak[m]||{w:0,l:0};let lv=d.level[m]??ageStart(),note='';
if(result==='win'){d.score[m][0]++;s.w++;s.l=0;if(s.w>=2&&lv<2){lv++;s.w=0;note=tx('levelUp')}gardenCelebrate(GAME[m])}else if(result==='loss'){d.score[m][1]++;s.l++;s.w=0;if(s.l>=2&&lv>0){lv--;s.l=0;note=tx('levelDown')}gardenMiss(GAME[m])}else{d.score[m][2]++}
d.level[m]=lv;d.streak[m]=s;save(d);const lvEl=section.querySelector('.versus-level strong');if(lvEl){lvEl.textContent=tx('level',{l:lvName(lv)});section.querySelectorAll('.versus-level button').forEach((b,i)=>b.setAttribute('aria-pressed',i===lv))}status.textContent=tx(result==='win'?'youWin':result==='loss'?'roboWins':'draw')+(note?' '+note:'');if(m==='nim'&&result==='loss')stage.append(E('p',tx('nimHint',{k:nimMax()+1}),'versus-hint'));stage.append(B(tx('again'),()=>render(),'primary'));scoreLine()}
function scoreLine(){const sc=(read().score||{})[mode]||[0,0,0];const el=section.querySelector('.versus-score');if(el)el.textContent=tx('score',{a:sc[0],b:sc[1],c:sc[2]})}
function roboSays(text){status.textContent=text}
// ——— X și 0
const LINES=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];
const winner=b=>{for(const [a,c,d] of LINES)if(b[a]&&b[a]===b[c]&&b[a]===b[d])return b[a];return b.every(Boolean)?'draw':null};
function minimax(b,turn){const w=winner(b);if(w==='O')return{score:1};if(w==='X')return{score:-1};if(w==='draw')return{score:0};let best=null;for(let i=0;i<9;i++)if(!b[i]){b[i]=turn;const r=minimax(b,turn==='O'?'X':'O');b[i]=null;const s=r.score*0.99;if(!best||(turn==='O'?s>best.score:s<best.score))best={score:s,move:i}}return best}
function roboMove(b,lv){const free=b.map((v,i)=>v?null:i).filter(i=>i!==null);const smart=[.25,.7,1][lv];if(Math.random()<smart)return minimax([...b],'O').move;for(const i of free){const t=[...b];t[i]='O';if(winner(t)==='O'&&lv>0)return i}return free[Math.floor(Math.random()*free.length)]}
function ttt(){const my=++token,lv=levelOf('ttt'),b=Array(9).fill(null);let busy=false;stage.append(E('p',tx('tttHelp')),listen(tx('tttHelp')));const grid=E('div','','ttt-grid');grid.setAttribute('role','group');grid.setAttribute('aria-label',tx('ttt'));stage.append(grid);
const cells=b.map((_,i)=>{const c=B('',()=>play(i),'ttt-cell');grid.append(c);return c});
const paint=()=>cells.forEach((c,i)=>{c.textContent=b[i]==='X'?'✕':b[i]==='O'?'◯':'';c.classList.toggle('x',b[i]==='X');c.classList.toggle('o',b[i]==='O');c.disabled=!!b[i]||busy||!!winner(b);c.setAttribute('aria-label',tx('cell',{r:Math.floor(i/3)+1,c:i%3+1,v:b[i]==='X'?tx('you'):b[i]==='O'?tx('robo'):tx('empty')}))});
const end=()=>{const w=winner(b);if(!w)return false;const line=LINES.find(([a,c,d])=>b[a]&&b[a]===b[c]&&b[a]===b[d]);if(line)line.forEach(i=>cells[i].classList.add('win'));finish('ttt',w==='X'?'win':w==='O'?'loss':'draw');return true};
async function play(i){if(busy||b[i]||winner(b))return;b[i]='X';window.gardenSound?.('pop');paint();if(end())return;busy=true;paint();roboSays(tx('thinking'));await wait(650);if(my!==token)return;b[roboMove(b,lv)]='O';busy=false;paint();if(!end())roboSays(tx('yourTurn'))}
paint();roboSays(tx('yourTurn'))}
// ——— Memory contra lui Robo
const SYMS=['🦄','🧁','🚀','🌈','🐞','🌻','🐳','🍓','⭐','🎈'];
function memory(){const my=++token,lv=levelOf('memory'),a=ageOf(profile.dob),pairs=a<=5?4:a<=8?6:8,remember=[.3,.55,.9][lv];const cards=shuffle(shuffle([...SYMS]).slice(0,pairs).flatMap(s=>[s,s]));const matched=new Set(),mem=new Map();let open=[],turn='you',busy=false,score={you:0,robo:0};
stage.append(E('p',tx('memHelp')),listen(tx('memHelp')));const info=E('p','','versus-pairs');const grid=E('div','','match-grid versus-cards');grid.style.setProperty('--match-cols',pairs<=4?4:pairs<=6?4:4);stage.append(info,grid);
const els=cards.map((s,i)=>{const c=B('?',()=>youFlip(i),'memory-card');grid.append(c);return c});
const see=i=>{if(Math.random()<remember)mem.set(i,cards[i])};
const paint=()=>{els.forEach((c,i)=>{const shown=open.includes(i)||matched.has(i);c.textContent=shown?cards[i]:'?';c.classList.toggle('matched',matched.has(i));c.classList.toggle('robo-pair',matched.has(i)&&c.dataset.owner==='robo');c.disabled=matched.has(i)||open.includes(i)||busy||turn!=='you';c.setAttribute('aria-label',matched.has(i)?`${cards[i]} · ${tx('found')}`:shown?cards[i]:tx('card',{n:i+1}))});info.textContent=tx('pairs',{a:score.you,b:score.robo})};
const done=()=>{if(matched.size<cards.length)return false;finish('memory',score.you>score.robo?'win':score.you<score.robo?'loss':'draw');return true};
async function resolve(who){busy=true;paint();const [x,y]=open;if(cards[x]===cards[y]){matched.add(x);matched.add(y);els[x].dataset.owner=els[y].dataset.owner=who;score[who]++;mem.delete(x);mem.delete(y);window.gardenSound?.('pop');await wait(500);if(my!==token)return;open=[];busy=false;paint();if(done())return;if(who==='robo')roboTurn();else roboSays(tx('yourTurn'))}else{await wait(950);if(my!==token)return;open=[];busy=false;turn=who==='you'?'robo':'you';paint();if(turn==='robo')roboTurn();else roboSays(tx('yourTurn'))}}
function youFlip(i){if(busy||turn!=='you'||open.includes(i)||matched.has(i))return;open.push(i);see(i);paint();if(open.length===2)resolve('you')}
async function roboTurn(){busy=true;paint();roboSays(tx('thinking'));await wait(700);if(my!==token)return;const left=[...cards.keys()].filter(i=>!matched.has(i));let first=null,second=null;const known=[...mem.entries()].filter(([i])=>!matched.has(i));for(let p=0;p<known.length&&first===null;p++)for(let q=p+1;q<known.length;q++)if(known[p][1]===known[q][1]){first=known[p][0];second=known[q][0];break}
if(first===null){const unknown=left.filter(i=>!mem.has(i));first=(unknown.length?unknown:left)[Math.floor(Math.random()*(unknown.length||left.length))]}open=[first];mem.set(first,cards[first]);paint();await wait(650);if(my!==token)return;if(second===null){const match=[...mem.entries()].find(([i,s])=>i!==first&&!matched.has(i)&&s===cards[first]);if(match)second=match[0];else{const rest=left.filter(i=>i!==first),unknown=rest.filter(i=>!mem.has(i));const pool=unknown.length?unknown:rest;second=pool[Math.floor(Math.random()*pool.length)]}}open=[first,second];see(second);paint();await wait(650);if(my!==token)return;resolve('robo')}
paint();roboSays(tx('yourTurn'))}
// ——— Bețișoarele (Nim): cine ia ultimul câștigă.
const nimMax=()=>ageOf(profile.dob)<=5?2:3;
function nim(){const my=++token,lv=levelOf('nim'),m=nimMax(),a=ageOf(profile.dob);let n=a<=5?7:a<=8?10+Math.floor(Math.random()*4):13+Math.floor(Math.random()*7),busy=false;stage.append(E('p',tx('nimHelp',{m})),listen(tx('nimHelp',{m})));const pile=E('div','','nim-pile');pile.setAttribute('role','img');const count=E('p','','versus-pairs'),row=E('div','','discover-options');stage.append(count,pile,row);
const paint=()=>{pile.replaceChildren(...Array.from({length:n},()=>E('span','','stick')));pile.setAttribute('aria-label',tx('left',{n}));count.textContent=tx('left',{n});row.replaceChildren(...Array.from({length:m},(_,i)=>{const b=B(tx('take',{n:i+1}),()=>take(i+1));b.disabled=busy||i+1>n;return b}))};
const optimal=()=>{const r=n%(m+1);return r||null};
async function take(k){if(busy||k>n)return;n-=k;window.gardenSound?.('pop');roboSays(tx('youTook',{n:k}));paint();if(n===0){finish('nim','win');return}busy=true;paint();await wait(750);if(my!==token)return;const smart=[0,.5,1][lv];let r=Math.random()<smart?optimal():null;if(!r)r=1+Math.floor(Math.random()*Math.min(m,n));n-=r;busy=false;paint();if(n===0){roboSays(tx('roboTook',{n:r}));finish('nim','loss');return}roboSays(tx('roboTook',{n:r})+' '+tx('yourTurn'))}
paint();roboSays(tx('yourTurn'))}
function listen(text){return B(tx('listen'),()=>gardenSpeak(text,true),'speak-btn')}
function render(){if(!profile||$('app').hidden)return;token++;section.replaceChildren();const head=E('div','','versus-head');head.append(gardenArt('robot',72),E('div'));head.lastChild.append(E('h2',tx('title')),E('p',tx('intro')));section.append(head);const tabs=E('div','','learning-tabs');[['ttt','✕◯'],['memory','🃏'],['nim','🥢']].forEach(([k,icon])=>{const b=B(`${icon} ${tx(k)}`,()=>{mode=k;render()});b.setAttribute('aria-pressed',mode===k);tabs.append(b)});section.append(tabs);
const lv=levelOf(mode),lvRow=E('div','','versus-level');lvRow.setAttribute('role','group');lvRow.setAttribute('aria-label',tx('setLevel'));lvRow.append(E('strong',tx('level',{l:lvName(lv)})));[0,1,2].forEach(i=>{const b=B(lvName(i),()=>{const d=read();d.level=d.level||{};d.level[mode]=i;d.streak=d.streak||{};d.streak[mode]={w:0,l:0};save(d);render()});b.setAttribute('aria-pressed',lv===i);lvRow.append(b)});section.append(lvRow,E('p','','versus-score'));
stage=E('div','','learning-stage versus-stage');status=E('div','','learning-feedback');status.setAttribute('role','status');status.setAttribute('aria-live','polite');section.append(stage);({ttt,memory,nim})[mode]();section.append(status);scoreLine()}
gardenOn(()=>render());if(profile)render();
})();
