const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');const html=fs.readFileSync(__dirname+'/index.html','utf8'),script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
class Element{constructor(){this.textContent='';this.value='';this.checked=false;this.hidden=false;this.children=[];this.dataset={};this.style={};this.classList={toggle(){}};this.files=[]}setAttribute(){}append(...v){this.children.push(...v)}replaceChildren(...v){this.children=v}querySelector(){return this.children[0]||new Element()}focus(){}click(){}setPointerCapture(){}getContext(){return {}}}
const elements=new Map();const get=id=>{if(!elements.has(id))elements.set(id,new Element());return elements.get(id)};get('mode').value='story';get('sport').value='basket';const doc={getElementById:get,documentElement:{style:{}},body:get('body'),querySelectorAll:()=>[],createElement:()=>new Element(),addEventListener(){}};const local=new Map();const context={document:doc,window:{parent:null},navigator:{},location:{protocol:"file:",origin:"null",search:""},innerWidth:390,URLSearchParams,matchMedia:()=>({matches:false}),localStorage:{getItem:k=>local.get(k)||null,setItem:(k,v)=>local.set(k,v)},requestAnimationFrame(){},addEventListener(){},setTimeout(){},Date,JSON,Math,Object,Array,Number,Set,Error,Infinity,Blob,URL,AbortController,confirm:()=>true};vm.createContext(context);vm.runInContext(script,context);const api=context.window.slideStorm;const evaluate=s=>vm.runInContext(s,context);const clone=x=>JSON.parse(JSON.stringify(x));assert.equal(api.getState().unlocked,1);
const base=clone(api.defaults());const malformed=[null,[],{}, {...base,best:null},{...base,best:[]},{...base,best:{1:-1}},{...base,best:{101:1}},{...base,daily:null},{...base,owned:['evil']},{...base,owned:['classic','classic']},{...base,equipped:'comet'},{...base,unlocked:101},{...base,coins:Infinity},{...base,settings:{...base.settings,speed:2}},{...base,settings:{...base.settings,single:'yes'}}];for(const b of malformed)assert.throws(()=>api.normalize(b));assert.deepEqual(clone(api.normalize(base)),base);const hostile={...base,best:JSON.parse('{"__proto__":2}')};assert.throws(()=>api.normalize(hostile));
evaluate('state.settings.single=true; state.settings.assist=true');api.start(1);api.update(45);assert.equal(api.getGame().distance,1100);for(let i=0;i<3;i++){api.action('single');api.update(.7)}assert.equal(api.getGame().phase,'result');assert.equal(api.getState().unlocked,2);assert(api.getState().coins>=25);const reward=api.getState().coins;api.update(100);assert.equal(api.getState().coins,reward);evaluate('next()');assert.equal(api.getGame().level,2);
evaluate('pauseGame()');const distance=api.getGame().distance;api.update(10);assert.equal(api.getGame().distance,distance);evaluate('pauseGame()');api.update(1);assert(api.getGame().distance>distance);
get('mode').value='zen';api.start(1);api.update(500);assert.equal(api.getGame().phase,'running');get('mode').value='race';api.start(1);api.update(71);assert.equal(api.getGame().phase,'result');
get('mode').value='daily';api.start();const first=api.getGame().events;api.start();assert.deepEqual(api.getGame().events,first);api.update(45);for(let i=0;i<3;i++){api.action('single');api.update(.7)}assert.equal(Object.keys(api.getState().daily).length,1);
get('mode').value='champ';get('sport').value='basket';api.start(1);for(let round=0;round<3;round++){api.update(45);for(let i=0;i<3;i++){api.action('single');api.update(.7)}assert.equal(api.getGame().phase,'result');if(round<2)evaluate('next()')}assert(api.getState().champBest>0);assert.equal(api.getGame().champRound,2);assert.equal(api.getState().unlocked,2);
const saved=JSON.parse(local.get('slidestorm-v1'));assert.deepEqual(clone(api.normalize(saved)),clone(api.getState()));
// Every interface translation has a matching key in both languages.
const keys=[...html.matchAll(/data-i="([^"]+)"/g)].map(m=>m[1]);for(const key of keys){assert(evaluate(`Object.hasOwn(copy.ro,${JSON.stringify(key)})`));assert(evaluate(`Object.hasOwn(copy.en,${JSON.stringify(key)})`))}
assert(html.includes('@media(max-width:460px)'));assert(html.includes('touch-action:none'));assert(html.includes('aria-live="polite"'));
// v1 migration keeps progress, currency and preferences.
const legacy={...base,version:1,unlocked:12,coins:321};delete legacy.extra;const migrated=clone(api.normalize(legacy));assert.equal(migrated.version,2);assert.equal(migrated.unlocked,12);assert.equal(migrated.coins,321);assert(migrated.extra.custom);
for(const extra of [null,[],{...base.extra,history:null},{...base.extra,opts:{...base.extra.opts,steps:'yes'}},{...base.extra,custom:{...base.extra.custom,events:[{d:1,lane:9,kind:'evil'}]}}])assert.throws(()=>api.normalize({...base,extra}));
assert.throws(()=>api.normalizeRoute({...base.extra.custom,length:10}));assert.throws(()=>api.normalizeRoute({...base.extra.custom,events:[{d:100,lane:3,kind:'energy'}]}));assert.equal(api.normalizeRoute(base.extra.custom).events.length,3);
// Exercise every generated level and sport, including solvable chapter mazes.
function solveMaze(){const m=api.getGame().maze;if(!m)return;const queue=[{x:m.x,y:m.y,path:[]}],seen=new Set();while(queue.length){const c=queue.shift(),key=c.x+','+c.y;if(seen.has(key))continue;seen.add(key);if(c.x===5&&c.y===5){for(const move of c.path)api.action(move);return}for(const [move,dx,dy]of [['left',-1,0],['right',1,0],['jump',0,-1],['throw',0,1]]){const x=c.x+dx,y=c.y+dy;if(x>=0&&x<7&&y>=0&&y<7&&!m.cells[y][x])queue.push({x,y,path:[...c.path,move]})}}throw Error('unsolvable maze')}
get('mode').value='story';evaluate('state.settings.single=true;state.settings.assist=true;state.extra.opts.timerOff=true');const sportNames=['basket','football','volley','handball','polo','golf','bowling','target'];for(let n=1;n<=100;n++){get('sport').value=sportNames[(n-1)%8];api.start(n);solveMaze();for(let tick=0;tick<1000&&api.getGame().distance<1100;tick++)api.update(.1);assert.equal(api.getGame().distance,1100,'level '+n+' route');for(let shots=0;shots<8&&api.getGame().phase==='running';shots++){api.action('single');api.update(.7)}assert.equal(api.getGame().phase,'result','level '+n+' result');assert.equal(api.getGame().goals,3)}assert.equal(api.getState().unlocked,100);assert.equal(api.getState().extra.history.length,100);assert.equal(Object.keys(api.getState().extra.stats).length,8);assert.deepEqual(clone(api.normalize(api.getState())),clone(api.getState()));
// Castle, sluice and combo cooldown.
get('mode').value='custom';api.start(1);evaluate("game.distance=100;game.lane=1;game.events=[{d:150,lane:1,kind:'castle',done:false}];game.jump=.7;game.shot=0");api.action('throw');assert.equal(api.getGame().broken,1);assert.equal(api.getGame().combos,1);api.action('throw');assert.equal(api.getGame().combos,1);evaluate("game.distance=650;game.events=[{d:650,lane:1,kind:'switch',done:false}];state.settings.single=false;state.settings.assist=false;game.shot=0");const gateDistance=api.getGame().distance;api.update(.1);assert.equal(api.getGame().distance,gateDistance);api.action('throw');assert.equal(api.getGame().events[0].done,true);api.update(.1);assert(api.getGame().distance>gateDistance);
// Step mode does not advance until the explicit next-step action.
evaluate('state.extra.opts.steps=true');api.start(1);const stopped=api.getGame().distance;api.update(10);assert.equal(api.getGame().distance,stopped);get('stepBtn').onclick();assert(api.getGame().distance>stopped);evaluate('state.extra.opts.steps=false;state.settings.single=true;state.settings.assist=true');
get('mode').value='party';api.start(1);evaluate('game.distance=1100');for(let i=0;i<3;i++){api.action('single');api.update(.7)}assert.equal(api.getGame().partyScores.length,1);api.next();assert.equal(api.getGame().partyPlayer,2);evaluate('game.distance=1100');for(let i=0;i<3;i++){api.action('single');api.update(.7)}assert.equal(api.getGame().partyScores.length,2);
assert(api.activeSeason('halloween',new Date('2026-10-31T12:00:00')));assert(!api.activeSeason('halloween',new Date('2026-10-01T12:00:00')));assert(api.activeSeason('christmas',new Date('2027-01-02T12:00:00')));
console.log('PASS: 15 malformed backup variants + prototype key, clean round-trip, default progress, level completion/next, no double reward, pause, Zen, race timeout, deterministic daily, 3-round championship, mode-separated progress, local save, complete interface RO/EN. v1 migration, nested v2 rejection, all 100 levels/eight sports, chapter maze solvability, castle/sluice/combo cooldown, step mode and party turns. Browser visual/touch QA unavailable in runtime.');
