const fs=require('fs'),vm=require('vm'),assert=require('assert');const dir=require('path').join(__dirname,'..')+'/',storage={};let random=.4;
function context(){const nodes={};function make(id=''){return nodes[id]||=( {id:id.startsWith('#')?id.slice(1):id,innerHTML:'',textContent:'',dataset:{},style:{},tagName:'DIV',value:'',children:[],disabled:false,checked:false,setAttribute(){},getAttribute(){},addEventListener(){},appendChild(e){this.children.push(e)},querySelectorAll(){return []},querySelector(){return {focus(){}}},focus(){},showModal(){},close(){},remove(){},setSelectionRange(){}})}const optional=new Set(['#search','#metricform','[data-example]','[data-backup]','[data-import]','[data-reset]','[data-office-toggle]','[data-office-full]','[data-transfer-review]','[data-transfer-dismiss]','#suite-search','#pipeline-filter','#record-currency','#record-from','#record-to','#record-project','#utm-form','#price-form','#whatif-form','#ab-form']);const math=Object.create(Math);math.random=()=>random;const ctx={console,Intl,Date,Math:math,JSON,Set,Object,Array,String,Number,URL,URLSearchParams,Blob,structuredClone,crypto:require('crypto').webcrypto,navigator:{onLine:true},location:{href:'',search:'',protocol:'https:'},matchMedia:()=>({matches:false}),localStorage:{getItem:k=>storage[k]??null,setItem:(k,v)=>storage[k]=v,removeItem:k=>delete storage[k]},document:{getElementById:make,querySelector:s=>optional.has(s)?null:make(s),querySelectorAll(){return []},createElement:tag=>({...make('new-'+Math.random()),id:'',tagName:tag.toUpperCase(),dataset:{},style:{},click(){}}),documentElement:{dataset:{}},body:{classList:{toggle(){},add(){},remove(){}},appendChild(){}},activeElement:{dataset:{},focus(){}},addEventListener(){}},setTimeout(){},clearTimeout(){},window:{scrollTo(){}},confirm:()=>true,prompt:()=>null};vm.createContext(ctx);return ctx}
const inline=n=>fs.readFileSync(dir+n+'.html','utf8').split('<script>').at(-1).split('</script>')[0];const fctx=context();vm.runInContext(fs.readFileSync(dir+'scenarios.js','utf8'),fctx);vm.runInContext(inline('funnel-forge').replace('let saved=null;','globalThis.engine={newGame,act,buy,endWeek,validate,eventChoice,transferDossier,get:()=>S,setMode:m=>selectedMode=m,getUndo:()=>gameUndo,configFor};let saved=null;'),fctx);const f=fctx.engine;
assert(f.validate(f.get()));assert.equal(f.get().leads.length,4);f.setMode('training');f.newGame();const l=f.get().leads[1];f.act('qualify',l.id);assert.equal(f.getUndo().length,1);assert(f.validate(f.get()));f.eventChoice('capacity');assert(f.validate(f.get()));f.buy('sdr');assert.equal(f.get().ap,8);assert(f.validate(f.get()));
f.setMode('free');f.newGame();for(let i=0;i<15;i++){f.get().alloc={email:0,social:0,ads:0,content:0,events:0};f.endWeek()}assert.equal(f.get().week,16);assert.equal(f.get().over,null);assert(f.validate(f.get()));
f.setMode('season');const custom={id:'custom-fixture',title:'Custom',client:'Test',audience:'Audience',message:'Message',goal:'20 enquiries',target:3000,cash:12000,weeks:4};f.newGame(custom);assert.equal(f.get().scenario,'custom');for(let i=0;i<4;i++){f.get().alloc={email:0,social:0,ads:0,content:0,events:0};f.endWeek()}assert(f.get().over);assert.equal(f.get().hist.length,4);assert(f.validate(f.get()));
f.setMode('season');f.newGame();f.get().tools.sdr=true;f.get().cash=500;f.get().ap=8;f.endWeek();assert.equal(f.get().over,'bank');assert(f.validate(f.get()));
f.newGame();f.transferDossier();const packet=JSON.parse(storage.ff_transfer_v1);
const ctx=context();vm.runInContext(inline('index'),ctx);vm.runInContext(fs.readFileSync(dir+'scenarios.js','utf8'),ctx);vm.runInContext(fs.readFileSync(dir+'suite.js','utf8'),ctx);const a=ctx.window.GrowthSuite;assert(a);assert(a.normalizeSuite(a.get()));
let bad=a.get();bad.spaces.play.projects=null;assert.equal(a.normalizeSuite(bad),null);bad=a.get();bad.spaces.play.goals={revenue:null,conversion:5};assert.equal(a.normalizeSuite(bad),null);
const result={title:'Test',id:'r1',projectId:'',date:'2026-10-08',channel:'Email',currency:'EUR',visits:1000,leads:80,orders:40,spend:1200,otherCosts:300,revenue:4000,mrr:1000,customers:20,churned:2};const value=a.aggregate([result],[{value:100}]);assert.equal(value.profit,2400);assert.equal(value.conversion,4);assert.equal(value.cpa,40);assert.equal(value.churn,10);assert.equal(value.roas,4000/1200);assert.equal(value.mrr,1000);assert.equal(a.aggregate([]).conversion,null);
const csv='Name,Company,Email,Value,Currency,Stage,Follow-up,Notes\r\n"Ana, A",Studio,ana@example.com,1200,EUR,new,2026-10-08,"Hello\nworld"';const imported=a.contactCSV(csv);assert.equal(imported.contacts.length,1);assert.equal(imported.contacts[0].name,'Ana, A');assert(imported.contacts[0].notes.includes('\n'));assert.equal(a.parseCSV('Name;Company\nAna;Studio').length,2);assert.throws(()=>a.parseCSV('Name\n"open'));assert.equal(a.contactCSV('Name,Value\nAna,-1').errors.length,1);
const before=vm.runInContext('JSON.stringify(state.spaces.work)',ctx);assert(vm.runInContext('acceptTransfer(readTransfer())',ctx));assert.equal(a.get().spaces.play.projects.length,1);assert.deepStrictEqual(JSON.parse(vm.runInContext('JSON.stringify(state.spaces.work)',ctx)),JSON.parse(before));storage.ff_transfer_v1=JSON.stringify(packet);assert(vm.runInContext('acceptTransfer(readTransfer())',ctx));assert.equal(a.get().spaces.play.projects.length,1);
assert(a.readBundle(JSON.parse(storage['growth-suite-v2'])?.version===2?{format:'growth-quest-bundle',version:2,base:JSON.parse(storage['laurai-growth-quest-v1']),suite:a.get()}:null));
const project=a.get().spaces.play.projects[0];assert(a.reportHtml(project).includes('[SIMULARE]'));assert(a.caseText(project).includes('PROBLEMĂ'));assert(a.suggestions({...project,goal:'none'}).some(s=>s.includes('măsurabil')));
for(const lang of ['ro','en'])for(const mode of ['play','work'])for(const tab of ['projects','people','crmplus','tickets','planner','strategy','results','toolsplus','academy','reports','vault','connections']){vm.runInContext(`state.lang='${lang}';state.mode='${mode}';view='suite';render()`,ctx); // selected is closure-private: dispatch coverage via test-only accessor below.
}
const suiteForRender=fs.readFileSync(dir+'suite.js','utf8').replace('window.GrowthSuite={normalizeSuite','window.GrowthSuite={setTab:t=>{selected=t;paint()},normalizeSuite');const ctx2=context();vm.runInContext(inline('index'),ctx2);vm.runInContext(fs.readFileSync(dir+'scenarios.js','utf8'),ctx2);vm.runInContext(suiteForRender,ctx2);for(const lang of ['ro','en'])for(const mode of ['play','work'])for(const tab of ['projects','people','crmplus','tickets','planner','strategy','results','toolsplus','academy','reports','vault','connections']){vm.runInContext(`state.lang='${lang}';state.mode='${mode}'`,ctx2);ctx2.window.GrowthSuite.setTab(tab)}
console.log('PASS: training undo history, free mode beyond 12 weeks, custom 4-week season, bankruptcy, suite migration/schema rejection, financial aggregation, quoted CSV and rejected inputs, idempotent dossier-to-project bridge, Work preservation, bundle/report export and 48 extended-page/language/mode renders.');
// Transaction and recovery checks use the actual Studio implementation with test-only accessors.
const transactionSource=fs.readFileSync(dir+'suite.js','utf8').replace('window.GrowthSuite={normalizeSuite','window.GrowthSuite={commit,undo,doRedo,previewBundle,applyImport,bundle,getHistory:()=>history,normalizeSuite');const tx=context();vm.runInContext(inline('index'),tx);vm.runInContext(fs.readFileSync(dir+'scenarios.js','utf8'),tx);vm.runInContext(transactionSource,tx);const t=tx.window.GrowthSuite,initialCount=vm.runInContext('state.spaces.work.contacts.length',tx);vm.runInContext("state.mode='work';state.spaces.work.contacts.push({id:'transaction-contact',name:'Example',company:'Example Co',email:'example@example.com',value:500,currency:'EUR',stage:'new',followup:'2026-10-08',notes:'Test'})",tx);assert(t.commit('Fixture'));assert.equal(vm.runInContext('state.spaces.work.contacts.length',tx),initialCount+1);t.undo();assert.equal(vm.runInContext('state.spaces.work.contacts.length',tx),initialCount);t.doRedo();assert.equal(vm.runInContext('state.spaces.work.contacts.length',tx),initialCount+1);
const full=t.bundle();assert(t.readBundle(full));const altered=structuredClone(full);altered.base.spaces.work.contacts.push({id:'merged-contact',name:'Merge',company:'Co',email:'merge@example.com',value:10,currency:'RON',stage:'new',followup:'',notes:''});t.previewBundle(altered);t.applyImport('merge');assert.equal(vm.runInContext('state.spaces.work.contacts.length',tx),initialCount+2);t.previewBundle(altered);t.applyImport('merge');assert.equal(vm.runInContext('state.spaces.work.contacts.length',tx),initialCount+2);
let invalidBundle=structuredClone(full);invalidBundle.simulator={state:structuredClone(f.get()),progress:null};invalidBundle.simulator.state.mods={chMult:null};assert.equal(t.readBundle(invalidBundle),null);
const oldCoins=vm.runInContext('state.game.coins',tx),setter=tx.localStorage.setItem;tx.localStorage.setItem=(k,v)=>{if(k==='growth-suite-v2')throw Error('quota');setter(k,v)};vm.runInContext('state.game.coins+=5',tx);assert.equal(t.commit('Quota fixture'),false);assert.equal(vm.runInContext('state.game.coins',tx),oldCoins);assert(storage['growth-recovery-v2']);const reload=context();vm.runInContext(inline('index'),reload);vm.runInContext(fs.readFileSync(dir+'scenarios.js','utf8'),reload);vm.runInContext(transactionSource,reload);assert.equal(vm.runInContext('state.game.coins',reload),oldCoins);assert(reload.window.GrowthSuite.normalizeSuite(reload.window.GrowthSuite.get()));console.log('PASS: undo/redo, merge idempotency, nested simulator rejection, failed-write rollback and recovery after reload.');
