const fs=require('fs'),vm=require('vm'),assert=require('assert');const dir=require('path').join(__dirname,'..')+'/',storage={};let random=.4;
function context(){const nodes={};function make(id=''){return nodes[id]||=( {id:id.startsWith('#')?id.slice(1):id,innerHTML:'',textContent:'',dataset:{},style:{},tagName:'DIV',value:'',children:[],disabled:false,checked:false,setAttribute(){},getAttribute(){},addEventListener(){},appendChild(e){this.children.push(e)},querySelectorAll(){return []},querySelector(){return {focus(){}}},focus(){},showModal(){},close(){},remove(){},setSelectionRange(){}})}const optional=new Set(['#search','#metricform','[data-example]','[data-backup]','[data-import]','[data-reset]','[data-office-toggle]','[data-office-full]','[data-transfer-review]','[data-transfer-dismiss]','#suite-search','#pipeline-filter','#record-currency','#record-from','#record-to','#record-project','#utm-form','#price-form','#whatif-form','#ab-form']);const math=Object.create(Math);math.random=()=>random;const ctx={console,Intl,Date,Math:math,JSON,Set,Object,Array,String,Number,URL,URLSearchParams,Blob,structuredClone,crypto:require('crypto').webcrypto,navigator:{onLine:true},location:{href:'',search:'',protocol:'https:'},matchMedia:()=>({matches:false}),localStorage:{getItem:k=>storage[k]??null,setItem:(k,v)=>storage[k]=v,removeItem:k=>delete storage[k]},document:{getElementById:make,querySelector:s=>optional.has(s)?null:make(s),querySelectorAll(){return []},createElement:tag=>({...make('new-'+Math.random()),id:'',tagName:tag.toUpperCase(),dataset:{},style:{},click(){}}),documentElement:{dataset:{}},body:{classList:{toggle(){},add(){},remove(){}},appendChild(){}},activeElement:{dataset:{},focus(){}},addEventListener(){}},setTimeout(){},clearTimeout(){},window:{scrollTo(){}},confirm:()=>true,prompt:()=>null};vm.createContext(ctx);return ctx}
const inline=n=>fs.readFileSync(dir+n+'.html','utf8').split('<script>').at(-1).split('</script>')[0];const fctx=context();vm.runInContext(fs.readFileSync(dir+'scenarios.js','utf8'),fctx);vm.runInContext(inline('funnel-forge').replace('let saved=null;','globalThis.engine={newGame,act,buy,endWeek,validate,eventChoice,transferDossier,get:()=>S,setMode:m=>selectedMode=m,getUndo:()=>gameUndo,configFor};let saved=null;'),fctx);const f=fctx.engine;

f.setMode('season');f.newGame({id:'demo-luna',title:'Luna Bakery · atelier complet',client:'Luna Bakery',audience:'Locuitori din Iași interesați de produse artizanale',message:'Descoperă oferta sezonieră Luna Bakery.',goal:'Testează un funnel și pregătește trei materiale accesibile',target:6000,cash:12000,weeks:12});
f.buy('scoring');f.buy('sdr');f.buy('automation');
while(!f.get().over){let s=f.get();s.alloc={email:1,social:0,ads:0,content:1,events:0};while(s.ap>0&&s.leads.length){const lead=s.leads.slice().sort((a,b)=>(b.stage==='proposal'?200:b.stage==='qualified'?100:0)+b.score-((a.stage==='proposal'?200:a.stage==='qualified'?100:0)+a.score))[0];f.act(lead.stage==='proposal'?'close':lead.stage==='qualified'?'propose':'qualify',lead.id);assert(f.validate(s));}f.endWeek();assert(f.validate(f.get()));}
f.transferDossier();const packet=JSON.parse(storage.ff_transfer_v1);const ctx=context();vm.runInContext(inline('index'),ctx);vm.runInContext(fs.readFileSync(dir+'scenarios.js','utf8'),ctx);const src=fs.readFileSync(dir+'suite.js','utf8').replace('window.GrowthSuite={normalizeSuite','window.GrowthSuite={bundle,normalizeSuite');vm.runInContext(src,ctx);const a=ctx.window.GrowthSuite;const untouched=vm.runInContext('JSON.stringify(state.spaces.work)',ctx);assert(vm.runInContext('acceptTransfer(readTransfer())',ctx));assert.deepStrictEqual(JSON.parse(vm.runInContext('JSON.stringify(state.spaces.work)',ctx)),JSON.parse(untouched));const p=a.get().spaces.play.projects[0];assert(p.simulated);assert.equal(vm.runInContext('state.spaces.play.posts.length',ctx)>=3,true);const bundle=a.bundle();assert(a.readBundle(bundle));assert(a.validForge(bundle.simulator.state));const copy=JSON.parse(JSON.stringify(bundle));assert(a.readBundle(copy));storage.ff_transfer_v1=JSON.stringify(packet);assert(vm.runInContext('acceptTransfer(readTransfer())',ctx));assert.equal(a.get().spaces.play.projects.length,1);
const result={client:'Luna Bakery',randomFixture:0.4,week:f.get().week,mrr:f.get().mrr,cash:f.get().cash,outcome:f.get().over,clients:f.get().clients.length,generated:f.get().stats.gen,won:f.get().stats.won,marketingSpend:f.get().stats.spend,history:f.get().hist,checks:['12-week engine validation','CRM actions and tool purchases','Dossier transfer','Work data preserved','Repeated transfer has no duplicate project','JSON round-trip validation'],limitations:['Mock DOM and deterministic random fixture; not a prediction','Real-phone, touch and screen-reader tests pending','No browser screenshots captured']};
if(process.argv.includes('--write')){fs.writeFileSync(dir+'demo-backup.json',JSON.stringify(bundle,null,2));fs.writeFileSync(dir+'demo-results.json',JSON.stringify(result,null,2));}console.log(JSON.stringify(result,null,2));
